### ISSUE TITLE
The recorder is not recording.

### ISSUE THREAD

**Issue by LUK3D** [llfbandit/record#10]
When i run the app and start recording all runs fine but in the end the file plays just noises it does not record any sound.

  ```
 if (await Record.hasPermission()) {
          estaGravando.value = await Record.isRecording();
          Directory tempDir = await getExternalStorageDirectory();

          String tempPath = '${tempDir.path}/${DateTime.now().toString()}.m4a';
          if (!estaGravando.value) {
            print("Gravando");
            await Record.start(
              path: tempPath, // required
              encoder: AudioEncoder.AAC, // by default
              bitRate: 128000, // by default
              // sampleRate: 44100, // by default
              samplingRate: 44100,
            );
          } else {
            await Record.stop();
            print("FInalizou a gravacao");
            print(tempPath);
          }
        }
```

**Comment by llfbandit** [comment]
I need info. Earing noise desn't mean the record is wrong...
Did you try to save the output file in external path, and play it on a reliable player from your computer for example ?

**Comment by LUK3D** [comment]
> I need info. Earing noise doesn't mean the record is wrong...
> Did you try to save the output file in external path, and play it on a reliable player from your computer for example ?

Yes, I tried to play with another player, but there are only noises.
What information do you need?

**Comment by llfbandit** [comment]
Did you try the example with same result? (can't remember if I updated it to 2.0...).
Another device?
Another codec? Maybe AAC codec is broken on your device (could be possible).

This package is only a bridge to native recorder given by SDKs, so if you experience issues with recorded data I'm worried to not be able to handle it.
