### ISSUE TITLE
How to increase the recording volume systemically?

### ISSUE THREAD

**Issue by han-tm** [llfbandit/record#100]
I want to have the maximum (or other) volume level when recording. Is it possible to do this with the help of this library or do I need to use flutter methods?

**Comment by llfbandit** [comment]
This is not possible at this moment.
There may be some leads to achieve this on Android. It seems to be dependent of media sound volume (you can check it manually by yourself).
I don't know yet how to achieve this for web, iOS and macOS...
Windows & linux have already the option set (hard coded for now).

**Comment by han-tm** [comment]
> This is not possible at this moment. There may be some leads to achieve this on Android. It seems to be dependent of media sound volume (you can check it manually by yourself). I don't know yet how to achieve this for web, iOS and macOS... Windows & linux have already the option set (hard coded for now).

Thank you
