### ISSUE TITLE
on macOS unable to find device list

### ISSUE THREAD

**Issue by awakelee** [llfbandit/record#101]
**Package version**
4.4.0

**Describe the bug**
invoke start() function and get console logs:
```
flutter: Start recording
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(-3, Failed to start recording, Input device not found from available list., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      LoginPageState.build.<anonymous closure> (package:flutter_chat_demo/page/groupgame/login.dart:79:23)
<asynchronous suspension>

```

**To Reproduce**
Invoke Record#listInputDevices always return enpty list.
The code to execute on macOS in debug mode:
```
child: ElevatedButton(
    onPressed: () async {
      if (await record.hasPermission()) {
        var devs = await record.listInputDevices();
        // Start recording
        await record.start(
          path: 'aFullPath/myFile.m4a',
          encoder: AudioEncoder.aacLc
        );
      }
      bool isRecording = await record.isRecording();
      await record.stop();
    },
    child: const Text(""),
  ),
```
When the code above executed first time, permission window showed.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.5.1

**Additional context**
I have add that config to Info.plist:
```
	<key>NSMicrophoneUsageDescription</key>
	<string></string>
```

**Comment by awakelee** [comment]
I have fixed this problem by add configs to DebugProfile.entitlements:
```
	<key>com.apple.security.device.audio-input</key>
	<true/>
	<key>com.apple.security.device.microphone</key>
    <true/>

```

**Comment by jamescrosswell** [comment]
@awakelee thank you for posting the solution back here. I've been racking my brain for hours trying to figure this one out!

**Comment by csukuangfj** [comment]
> I have fixed this problem by add configs to DebugProfile.entitlements:
> 
> ```
> 	<key>com.apple.security.device.audio-input</key>
> 	<true/>
> 	<key>com.apple.security.device.microphone</key>
>     <true/>
> ```

@awakelee 
Thank you! You saved my life!

By the way, only the following two lines are required!
```
<key>com.apple.security.device.audio-input</key>
	<true/>
```
