### ISSUE TITLE
No signature of method: build_6ewzcqerx5745vz6wbsxn36i5.android()

### ISSUE THREAD

**Issue by xia-weiyang** [llfbandit/record#102]
I run it on android,  it show error:

* What went wrong:
A problem occurred evaluating project ':record'.
> No signature of method: build_6ewzcqerx5745vz6wbsxn36i5.android() is applicable for argument types: (build_6ewzcqerx5745vz6wbsxn36i5$_run_closure2) values: [build_6ewzcqerx5745vz6wbsxn36i5$_run_closure2@777fcd78]

**Comment by llfbandit** [comment]
Please look at this issue https://github.com/llfbandit/record/issues/93
