### ISSUE TITLE
Error while running the app on Android

### ISSUE THREAD

**Issue by iabdousd** [llfbandit/record#106]
**Package version**
Package version 4.4.0

**Describe the bug**
Not working on Android but working on iOS

**Expected behavior**
The app should've been built

**Additional context**
Logs:
```
FAILURE: Build failed with an exception.

* Where:

* What went wrong:
A problem occurred evaluating project ':record'.
> No signature of method: build_66n9qknzot7rkmikhwynesl5y.android() is applicable for argument types: (build_66n9qknzot7rkmikhwynesl5y$_run_closure2) values: [build_66n9qknzot7rkmikhwynesl5y$_run_closure2@26e59094]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by iabdousd** [comment]
CC @kdraa12

**Comment by bhautikGJ05** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\record-4.4.0\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':record'.
> No signature of method: build_2q09az9a2svzh642jq9ff6gyy.android() is applicable for argument types: (build_2q09az9a2svzh642jq9ff6gyy$_run_closure2) values: [build_2q09az9a2svzh642jq9ff6gyy$_run_closure2@3297b7bf]

**Comment by llfbandit** [comment]
Please look at this issue https://github.com/llfbandit/record/issues/93
