### ISSUE TITLE
getting error while recording audio in macOS and Widows

### ISSUE THREAD

**Issue by ShrirangaB** [llfbandit/record#108]
**Package version**
record: ^3.0.0

Getting the following Error when I try to record the audio
(flutter: MissingPluginException(No implementation found for method hasPermission on channel com.llfbandit.record))

**Desktop **
 - macOS: 10.15
 - Windows 10

**Comment by llfbandit** [comment]
Please upate to latest version. Windows and MacOS platforms are available from version 4.
