### ISSUE TITLE
Problem that crash build with Record 4.4.0

### ISSUE THREAD

**Issue by csacchetti** [llfbandit/record#109]
I have a strange error in Android build after update to 4.4.0 version.

* Where:
Build file '/Users/carlosacchetti/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/record-4.4.0/android/build.gradle' line: 34

* What went wrong:
A problem occurred evaluating project ':record'.
> Could not find method disable() for arguments [InvalidPackage] on task ':record:lint' of type com.android.build.gradle.tasks.LintGlobalTask.

**Comment by SnEhERANDE** [comment]
Yes. Same issue here. The second I add record dependencies. I am getting this error. please fix this

**Comment by csacchetti** [comment]
I solved this problem.
For iOS:
```
flutter clean
flutter pub get
flutter pub upgrade
cd iOS
pod install
pod update 
```

for Android I update the Gradle to version 7.0.1 and wrapper to version 7.0.2
and change in app/build.gradle
```
lintOptions {
        disable 'InvalidPackage'
}
```
with this
```
lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
}
```

I hope it can help others

**Comment by llfbandit** [comment]
```
lintOptions {
        disable 'InvalidPackage'
}
```
has been re-inserted in version 4.4.1
