### ISSUE TITLE
App getting crashed in MacOS when custom path is given

### ISSUE THREAD

**Issue by ShrirangaSB** [llfbandit/record#113]
**Package version**
record: ^4.4.0 

**Describe the bug**
App is getting crashed 

**To Reproduce**
to record in the  `_audioRecorder.start();` I'm passing a custom path instead of the temporary folder used

```
Directory? appDocDirectory;
 appDocDirectory = await getApplicationDocumentsDirectory();
          await _audioRecorder.start(
              path: "${appDocDirectory.path}/${uniqueId}.m4a");
```

app will get crashed if i use a custom path but works in iOS and android platforms

**Expected behavior**
macos app should not crash

**Desktop (please complete the following information):**
 - OS: macOS 12.6
-Flutter Verison: 3.3.3

**Comment by llfbandit** [comment]
Can you provide your stack trace?
Why do you think this related to this package?
If I understand the description, you tried with generated file from temporary folder and it worked?

For now, it could be simply the given path format or/and destination which is wrong.

**Comment by NitashEU** [comment]
You have to prefix the custom path with: 'file://' on MacOS.
