### ISSUE TITLE
iOS >=16  Recorder stops when phone call comes in

### ISSUE THREAD

**Issue by utkudenis** [llfbandit/record#115]
**Package version**
latest version 4.4.3 
flutter 3.0.5

**Describe the bug**
In iOS 16 and higher versions, the recorder stops when a phone call comes in. I can't check whether it comes with app life cycle because there is a phone call on top of the current app with the widget from the top. It should not stop when a call comes in. It should pause.
It also stops when you reject the call.

**To Reproduce**
Any implementation you can see it

**Smartphone (please complete the following information):**
 - Device: all iphones
 - OS: 16 16.1

**Comment by llfbandit** [comment]
This package only supports foreground recording. Going to background stops it. This made by design.
Please refer to the pinned issue [here](https://github.com/llfbandit/record/issues/69).

**Comment by utkudenis** [comment]
Hi, but ı need to pause record and continue to recording when call complete or rejected. how can we do that? 
Anythime someone call someone from phone, whatsapp teams or other platfroms :(

**Comment by utkudenis** [comment]
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/68633376/199699640-8d4b2b85-23e5-4b66-9576-c8f999d95f2e.png">
thats is the code and ı cannot catch coming phone call. 
Also your onStateChange Method do not return anyting. But player stop. 

Please  help
