### ISSUE TITLE
Possible to record to ogg?

### ISSUE THREAD

**Issue by skol101** [llfbandit/record#116]
**Is your feature request related to a problem? Please describe.**
Would like to record into ogg format because we're using JUCE library on the backend https://github.com/juce-framework/JUCE , which does not support opus.

**Describe the solution you'd like**
Add libvorbis support

**Describe alternatives you've considered**
Use ffmpeg to convert opus to ogg on device.

**Comment by llfbandit** [comment]
Please see readme.md to check supported formats per platform.

**Comment by skol101** [comment]
I've checked it beforehand. Not possible to have ogg support on iOS?

**Comment by llfbandit** [comment]
As far as I know iOS does not support this format.
