### ISSUE TITLE
Is possible to use audio record when pause

### ISSUE THREAD

**Issue by laldevfr** [llfbandit/record#117]
**Is your feature request related to a problem? Please describe.**
it's possible to use the part recorded from start to pause when we make a pause ? I want to make pause and after user can cut some part to create new audio record and after he can resume the main recorded.

**Additional context**
For Android & iOs

**Comment by llfbandit** [comment]
No, there is no such feature.
Also, on most supported platforms, only a single audio session can be up at the same time.
Unlikely, this request can be achieved.
