### ISSUE TITLE
[web] Cross-platform record compatibility:  Records recorded from web app, can only be played on web app

### ISSUE THREAD

**Issue by mostafaAbdelazim** [llfbandit/record#119]
Records recorded from web app, can only be played on web app and with incorrect duration value.
Other platforms can't play the web recorded audio

**Comment by Musharaf13** [comment]
@mostafaAbdelazim , How did you play it?
I would love to know.
Thanks in advance.

**Comment by llfbandit** [comment]
Without a reproducer, I won't do anything on this issue. The encoding is fully managed by the browser.

How do you retrieve the blob and save it to file system?
Which format do you use, with which parameters?
Which browser on which platform?
Is it reproducible with all the encoders or only one?
