### ISSUE TITLE
Recorded audio on Android is not played on iOS

### ISSUE THREAD

**Issue by codebombi** [llfbandit/record#122]
**Package version**
record: ^4.4.3

**Describe the bug**
Recorded audio on Android 9 is not played on iOS 15 
but if record on IOS -- played on Android - Its ok!

--> ReadBytes Failed

**To Reproduce**
1. Record on Android default
await _audioRecorder.start(
              path: path,
            );
2. Open on Ios

**Smartphone (please complete the following information):**
 - OS: Android 9 - IOS 15

**Comment by llfbandit** [comment]
The output file is entirely managed by the Android SDK and subsequent codecs provided with the device.
As I can't determinate the source of the issue, (is it Android wrong encoding? Is it iOS wrong decoding?)...
There's nothing I can do on this... I would suggest to try with other settings.

**Comment by codebombi** [comment]
> 

if you have Android + iOS phones, you can try to reproduce the problem
Android Ios Settings Plugin by default 
 AudioEncoder encoder = AudioEncoder.aacLc,
    int bitRate = 128000,
    int samplingRate = 44100,
    int numChannels = 2,

**Comment by Rimantovas** [comment]
@codebombi Did you manage to solve the issue?
