### ISSUE TITLE
Do not include fmedia as precompiled x86_64 binary on Linux

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [llfbandit/record#123]
**Package version**

> record_linux: ^0.3.4

**Describe the bug**

The Linux package contains a pre-built x86_64 binary without which the plugin does not work. A cross platform package should definitely not depend on pre-built binaries for a particular platform.

**To Reproduce**

- include `record` into your project
- try to compile on e.g. aarch64

See about this error:

```
 flutter --no-version-check build linux --debug

💪 Building with sound null safety 💪

Building Linux application...
CMake Error at CMakeLists.txt:120 (install):
  install FILES given directory
  "/home/user/path/to/app/linux/flutter/ephemeral/.plugin_symlinks/record_linux/linux/fmedia"
  to install.


Unable to generate build files
```

**Expected behavior**
It should compile the flutter app and all dependencies

**Desktop (please complete the following information):**
 - OS: Linux 6.0.0-rc6-x13s aarch64 GNU/Linux
 - Browser: n.a.
 - Version: n.a.
 - 
**Additional context**

File type: `ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=abf48cbb3c7937e5b8540980d680959fb3e6b4a6, stripped`

**Comment by llfbandit** [comment]
As far as I know, fmedia is not available for arm architecture. So precompiled or not won't change anything.

**Comment by krillefear** [comment]
Please reopen. Adding a precompiled binary will break snap support as it will lead to the issue that the not signed binary is rejected from the snapstore. I had to manually delete the binary inside of the snap after build to make it working again.

Also shipping a precompiled binary might violate their license. It is also just a **very** bad pattern to do this

**Comment by llfbandit** [comment]
From version 0.4, fmedia is no more shipped with the package. See #95.
