### ISSUE TITLE
Not working in IOS when trying to fetch File from path. Unhandled Exception: File file:///....tmp/C2A6E2CA-13CE-443F-968B-B57B4C1077DD.m4a not exists

### ISSUE THREAD

**Issue by rvharjinderbains** [llfbandit/record#124]
**Package version**
record: ^4.4.3

**Describe the bug**
I want to upload audio to server and when trying to pass provided audio path in Multipart it shows following error. However it is working fine in Android.

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: File file:///private/var/mobile/Containers/Data/Application/267071D3-EC01-4B5F-BCDA-3218D208F627/tmp/C2A6E2CA-13CE-443F-968B-B57B4C1077DD.m4a not exists
fileToBytes (package:get/get_connect/http/src/_http/_io/_file_decoder_io.dart:10:7)
new MultipartFile (package:get/get_connect/http/src/multipart/multipart_file.dart:11:25)
_ChatMessageScreenState.getRecordingWidget. (package:gagagonew/view/chat/chat_message_screen.dart:1343:17)
_InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)

i am storing the path in String like this:- String? path = await record.stop();

And trying to add audio in multipart like this:-
form.files.add(MapEntry(
'audio',
MultipartFile(path, filename: basename(path)),
));

**Comment by llfbandit** [comment]
I guess that Android platform does not prefixes the output path with `file` scheme.
Did you try the example? Did you verify that the file exist at this location?
