### ISSUE TITLE
W/MediaRecorder(30216): mediarecorder went away with unhandled events

### ISSUE THREAD

**Issue by csacchetti** [llfbandit/record#13]
I'm testing the package (with your example) and in iOS it doesn't give me any problems. In Android, on the other hand, it works fine on the Device but in the simulator it doesn't. It seems to be recording but when I hit play I don't hear anything. In the device, on the other hand, it is also heard.
I looked for any error messages and noticed this:
W/MediaRecorder(30216): mediarecorder went away with unhandled events

This message appears both when I use it with the Device and when I use it with the simulator, but while in the Device it works the same, in the simulator nothing is heard.
I found this answer to the above problem, hoping it will be helpful.
https://stackoverflow.com/questions/11871421/trying-to-record-audio-but-getting-message-mediarecorder-went-away-with-unhandl

**Comment by llfbandit** [comment]
Thanks for the report.
I'll check it soon.
