### ISSUE TITLE
NSURLConnection finished with error - code -1002

### ISSUE THREAD

**Issue by rvharjinderbains** [llfbandit/record#133]
**Undefined**

**Getting below mentioned error when trying to play audio after recording in IOS. It is working fine in android**

NSURLConnection finished with error - code -1002

**To Reproduce**
1. Go to Chat Screen
2. Click on Audio Recording
3. Stop Audio Recording
5. See error

![Screenshot 2023-01-30 at 4 57 54 PM](https://user-images.githubusercontent.com/105272009/215464880-050b44c7-e4d1-42ef-9b3e-43ddcf2d8c63.png)

**Audio should be played after stopping**

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: 15.4.1

**Additional context**
I am using below mentioned package to play the audio (UI Purposes)
voice_message_package :

**Comment by llfbandit** [comment]
This is a recording package, there is no relevant issue.
