### ISSUE TITLE
Conflicts with Dart 3.x

### ISSUE THREAD

**Issue by stevenosse** [llfbandit/record#134]
Hello !
First of all, thank you for this great package :)

Dart 3.x will introduce a "Record" type which will cause conflicts with the plugin's `Record` class.

**Describe the solution you'd like**
There will be a need to rename the `Record` class to something else, maybe something like `Recorder` ?

**Comment by llfbandit** [comment]
Thanks for the warning.
For now, there's no plan to rename the class, I'll think about it.
Despite dart v3, users can always import it with an alias.

**Comment by llfbandit** [comment]
`Record` will be renamed `AudioRecorder` in v5.
