### ISSUE TITLE
Default temp folder for iOS doesn't work

### ISSUE THREAD

**Issue by MenuItem207** [llfbandit/record#136]
**record: ^4.4.4**

**Describe the bug**
When 
```
record.start()
```
is called with no path provided, the default path becomes tmp/file.m4a. This file with this path does not exist. This issue is present both on the IOS simulator and a physical device. No issue arises when a custom path is provided. Is this the intended behaviour for iOS?

**Comment by llfbandit** [comment]
https://github.com/llfbandit/record/blob/404505e308d21cf7f0dc5ec180b213f7c26d3dd7/record/ios/Classes/SwiftRecordPlugin.swift#L29-L34

The output seems impossible regarding the code above. I don't know where `tmp/file.m4a` comes from.

**Comment by MenuItem207** [comment]
Hi! By file I meant uuid.m4a. tmp/file.m4a was not the actual output. What I wanted to highlight was the fact that record.stop() returns a file located inside the tmp folder. That file does not exist. 
```
File(path).exists()
```
returns false. When a custom path is provided, the file path returned by record.stop() exists.

**Comment by oengmengthong** [comment]
don't use File(path), use this instead: File.fromUri(Uri.parse(path))
