### ISSUE TITLE
Clarification required: Streaming

### ISSUE THREAD

**Issue by TheSingletonDev** [llfbandit/record#140]
I am using this package extensively for wav and flac file generation for Android and iOS.
Thank you so much for this.
However, I also have a requirement of streaming over web socket. Does this library also gives streaming functionality.

Something like 
```
stream.listen((chunk) {
    SocketEmit(chunk)
}) 
```

There is 2 year old issue #22 which says it doesn't.. But since it's been 2 years just wanted to check again.

**Comment by llfbandit** [comment]
Unfortunately, no. People want files and not raw encoded audio data. On those platforms, Android & iOS, there is no way (well I did found it) to encode and fill a file container (MP4 and others) and stream at the same time.

**Comment by TheSingletonDev** [comment]
Thank you man.. For your prompt response.. However, I just want to let you know
1. People do need streaming becase the major use case is of speech recognition.. And with AI at a time high, many dev like us are looking around for it.
2. I have found libraries that independently either stream or record but not both.. So I take your second comment that it might not be possible to fill a file container and stream at the same time. However, my ask was a little different. I was hoping that based on a flag whether a dev want a streaming OR want a file at a time.. Not both together.
I hope your find something around that coz majority of library are not providing that functionality.. Yours would be unique in that way.
Trust me, I have been at it for past 2 weeks. Thank you so much anyway for this awesome light weight library.

**Comment by llfbandit** [comment]
Will be done in next v5... soon hopefully.
Streaming will be only supported for PCM which is the only linear format in the available list.

**Comment by llfbandit** [comment]
Available in v5-beta.1.

**Comment by TheSingletonDev** [comment]
Thank you @llfbandit for this version.. I will try it out and let you know the results.
Meanwhile a quick question, does it support both iOS and Android?
