### ISSUE TITLE
Call not recording

### ISSUE THREAD

**Issue by pirate-007** [llfbandit/record#141]
record: ^4.4.4

When I record a phone call I can't hear the conversation between the users in that audio file

Android
version: 11

if use the record package in the usual way( without recording a call) it works fine I can hear the recorded content in the audio file when I try to record a call  during that time of the call I can't hear anything in the recorded file but the recording process Is Working

Code of recording function

  Future<void> _start() async {
    try {
      if (await _audioRecorder.hasPermission()) {
        final isSupported = await _audioRecorder.isEncoderSupported(
          AudioEncoder.aacLc,
        );
        final session = await AudioSession.instance;
        await session.configure(AudioSessionConfiguration.speech());
        await session.setActive(true);
        await _audioRecorder.start();
        print("recording");
      }
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
    }
  }

**Comment by llfbandit** [comment]
You're not respecting issue templates, you've not searched for similar issues neither.

**Comment by pirate-007** [comment]
i just want to know is it possible to record calls

**Comment by llfbandit** [comment]
No. See https://github.com/llfbandit/record/issues/69
