### ISSUE TITLE
Chrome can't detect audio duration after recording

### ISSUE THREAD

**Issue by youssefali424** [llfbandit/record#145]
**version: 4.4.4**

**Describe the bug**
A chrome bug leads to have wrong encoding with the recorded file and you can't get duration correctly

**To Reproduce**
1. Record on chrome
2. play the recorded audio
3. duration not available while audio is playing

**Expected behavior**
The audio is recorded and encoded with the correct encoding

**Desktop (please complete the following information):**
 - chrome

**Additional context**
Issue discussed here as well https://github.com/ryanheise/just_audio/issues/218
and chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=642012

i already implemented a solution to this issue in my fork with get amplitude on web

**Comment by youssefali424** [comment]
this is the fix ~> https://github.com/llfbandit/record/pull/146

**Comment by youssefali424** [comment]
@jbryanh i think the amplitude for web is now on master
this is a separate issue on chrome

**Comment by youssefali424** [comment]
for context https://github.com/llfbandit/record/pull/147 i was merged with this pr

**Comment by llfbandit** [comment]
Will be merged certainly for next v5... arriving soon hopefully.

**Comment by llfbandit** [comment]
Available in v5-beta.1.
