### ISSUE TITLE
Non-WAV files recorded here crash just_audio_windows

### ISSUE THREAD

**Issue by sunilguptasg** [llfbandit/record#149]
**Package version**
record: ^4.1.1

**Describe the bug**
Recorded files do not play with just_audio (with the windows add-on) - except WAV

**To Reproduce**
1. record a file, select any encoding format other than WAV (audioRecorder.start(
          encoder: AudioEncoder.xxx,
        );
2. the file is saved
3. audioPlayer.setAudioSource(source)
4. [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Loading interrupted

**Expected behavior**
The recorded file should play

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**

**Additional context**
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.19045.2846], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.77.3)
[√] VS Code, 64-bit edition (version 1.64.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

Note: issue was reported to just_audio, who redirected this. I find it odd that the other m4a files from the internet are played without crashing by just_audio_windows but files recorded with this package cause the exception. However, these files are playable on VLC...

**Comment by llfbandit** [comment]
There's nothing more I can do here.
v5, will be implemented via Media Foundation. Hopefully, MPG container will be better supported for readers.
