### ISSUE TITLE
Continue recording while app is in background

### ISSUE THREAD

**Issue by touficzayed** [llfbandit/record#15]
Hi there,

I can record while my app is awake on the foreground. But when I minify my app, when it is put in the background, the recording stop.

For example, I launch my app, I click the record button and I start to talk. After 10 seconds I press the home button of my phone and I continue to talk for 20 seconds more. Then I relaunch my app, and I click the stop button.

Instead of getting a record file of 30 seconds with my full record, I only get the 10 first seconds.

I tried to run the record plugin in an isolate using the flutter_isolate plugin, but it does the same thing.

Do you know a method to keep recording while the app is in the background?

Thanks a lot!

**Comment by llfbandit** [comment]
This is not possible with this package. Also, background recording is not a goal at this current stage.
