### ISSUE TITLE
Crash on Android - java.lang.RuntimeException - Reading of audio buffer failed: AudioRecord.ERROR_INVALID_OPERATION

### ISSUE THREAD

**Issue by patelnirav48** [llfbandit/record#158]
Package version - record 4.4.4

Fatal Exception: java.lang.RuntimeException
Reading of audio buffer failed: AudioRecord.ERROR_INVALID_OPERATION

com.llfbandit.record.AudioRecorder$RecordDataWriter.run (AudioRecorder.java:244)

 - Device: Vivo
 - OS: Android 13

**Comment by llfbandit** [comment]
Duplicate of #135
