### ISSUE TITLE
Recording to WAV is incorrect

### ISSUE THREAD

**Issue by malaschitz** [llfbandit/record#159]
**Package version**
4.4.4

**Describe the bug**
When recording audio to wav format on Android devices (16kHz, mono) a small crackle can be heard. This has been tested on multiple devices (Samsung, Pixel, Xiaomi) and on multiple versions of the operating system. Analyzing the audio in Audacity, it can be seen that exactly every 80ms two values are missing (there are two zeros in a row). Of course it can be recorded to another format but the project required to record wav format. 

For comparison I attach the sound recorded with this library and the flutter_sound_lite library. 

<img width="486" alt="Screenshot 2023-05-25 at 22 14 28" src="https://github.com/llfbandit/record/assets/7115597/4b1d8ad3-ca3b-4493-8721-27c48dce52b1">
[wavs.zip](https://github.com/llfbandit/record/files/11568904/wavs.zip)

**Comment by llfbandit** [comment]
Thanks for the report. It seems to be resolved in next version (v5).
Feedback needed.

**Comment by llfbandit** [comment]
Available in v5-beta.1.
