### ISSUE TITLE
Every recording generates an .m4a file, regardless of the AudioEncoder called

### ISSUE THREAD

**Issue by Mohamedeijy** [llfbandit/record#168]
**Package version**
^4.4.4

**Describe the bug**
I repurposed the example provided to record audio files in pcm16bits (16Hz sampling rate, mono). However every recording generates an .m4a file, based on the path displayed after calling `_audioRecorder.stop()`. This happens for every single encoder supported.

**To Reproduce**
1. Start recording with 
`    await _audioRecorder.start(
      encoder: AudioEncoder.wav,
      samplingRate: 16000,
      numChannels: 1
    );`
Any other encoder leads to the same output.
2. Display the path of the file on stop.
`final path = await _audioRecorder.stop();
    print(path);`

Output: `I/flutter (16271): /data/user/0/com.example.flutter_project/cache/audio5413960857427291804.m4a`

**Expected behavior**
The file should be of format .wav when wav is chosed, .flac when flac is chosen, etc.
 
**Desktop (please complete the following information):**
 - OS: Scibian 10

**Additional context**
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] VS Code (version 1.76.0)
[!] Proxy Configuration
    ! NO_PROXY does not contain localhost
    ! NO_PROXY does not contain 127.0.0.1
    ! NO_PROXY does not contain ::1
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by mregnauld** [comment]
I experience the same problem on both iOS and Android.

**Comment by llfbandit** [comment]
This is just a filename. This won't be fixed as I'm working on next v5 which won't generate temp file.

**Comment by Mohamedeijy** [comment]
> This is just a filename. 

By this you mean the actual temp file being generated is encoded the right way, and the filename is just not the correct one ?

**Comment by llfbandit** [comment]
Yes it should be.
