### ISSUE TITLE
Audio recording starts when app is in background but records empty audio

### ISSUE THREAD

**Issue by 701789262a** [llfbandit/record#169]
Record 4.4.4

When the app is in the background, using flutter_background 1.2.0, makes the app start the recording but resulting audio is empty

1. Install flutter_background 1.2.0
2. Create a timer to start the recording x seconds after the app is in background; x being any small number of seconds
3. Audio file is created (it doesn't show the green microphone in the top right corner though) but is silent.

**Expected behavior**
Audio file should be generated correctly even if in background

**Smartphone:**
 - Device: Samsung S22 ULTRA
 - OS: Android 13

**Comment by llfbandit** [comment]
Please see https://github.com/llfbandit/record/issues/69.
