### ISSUE TITLE
[Question] Dependencies needed? and saving to Firestore

### ISSUE THREAD

**Issue by miriam-z** [llfbandit/record#17]
```
dependencies:  
  path_provider: ^2.0.1  
  just_audio: ^0.7.1
```

as well as: 

flutter:  
  plugin:    
    platforms:      
      android:        
        package: com.llfbandit.record        
    pluginClass: RecordPlugin      
    ios:        pluginClass: RecordPlugin

 
Do we need to install these dependencies as these are in the example pubspec.yaml, but not in main pubspec.yaml?   

and also how to save to Firestore example thanks

**Comment by llfbandit** [comment]
Those dependencies are externals.
You just need record package, path_provider is advised to get directory path on mobile platforms.

Don't know about firestore.

**Comment by miriam-z** [comment]
Thank you, how is the recorded audio saved?

**Comment by miriam-z** [comment]
The example shows main.dart:

import 'package:flutter/material.dart';
import 'package:just_audio/just_audio.dart' as ap;
import 'package:record/record.dart';
import 'package:record_example/audio_player.dart';

final _audioRecorder = Record();

and Record comes from record/record/lib/src/record.dart:

class Record implements RecordPlatform {


But in my example:

import 'package:record/record.dart';

 final _audioRecorder = Record(); 
 
 References .pub-cache/hosted/pub.dartlang.org/record-2.1.1/lib/record.dart:
 
 class Record {
  static const MethodChannel _channel = const MethodChannel(
    'com.llfbandit.record',
  );







class Record {
  static const MethodChannel _channel = const MethodChannel(
    'com.llfbandit.record',
  );

**Comment by miriam-z** [comment]
@llfbandit Could you comment on the difference in classes used?

**Comment by llfbandit** [comment]
Yes, example has been updated to use version 3.0.0.
Code update is minimal to switch to this version or you can stick with version 2 if web platform is not a target. Be aware that I won't support only latest version.

**Comment by miriam-z** [comment]
@llfbandit thanks but when we are starting our new project which libraries to use as it seems like Record class is not the same?

**Comment by llfbandit** [comment]
I guess in your previous project, you used version 2 and in your new, version 3. This is up to you to choose.

**Comment by miriam-z** [comment]
@llfbandit slightly confused, which library should we use if starting a new project?

So we just:

`import 'package:record/record.dart';
`
and this wraps the just_audio under the hood?

**Comment by llfbandit** [comment]
What? Please, read documentation of this package. Learn how to use dart, flutter and associated packages before going further.

**Comment by miriam-z** [comment]
As I understand it "No external dependencies," so what is the  pubspec.yaml for just_audio?

  just_audio: ^0.7.1

**Comment by miriam-z** [comment]
flutter pub get 

flutter pub add just_audio
Because just_audio >=0.7.0-nullsafety.0 <0.7.0-nullsafety.3 depends on rxdart ^0.26.0-nullsafety.1 and just_audio <0.0.5 depends on path_provider ^1.4.5, just_audio <0.0.5-∞ or >=0.7.0-nullsafety.0 <0.7.0-nullsafety.3 requires rxdart ^0.26.0-nullsafety.1 or path_provider ^1.4.5.
And because just_audio >=0.0.5 <0.2.0 depends on path_provider ^1.5.1, just_audio <0.2.0-∞ or >=0.7.0-nullsafety.0 <0.7.0-nullsafety.3 requires rxdart ^0.26.0-nullsafety.1 or path_provider ^1.4.5.
And because just_audio >=0.2.0 <0.7.0-nullsafety.0 depends on path_provider ^1.6.10 and just_audio >=0.7.0-nullsafety.3 <0.7.5 depends on rxdart ^0.26.0, just_audio <0.7.5 requires rxdart ^0.26.0-nullsafety.1 or path_provider ^1.4.5.
And because just_audio >=0.7.5 depends on rxdart >=0.26.0 <0.28.0 and everyvoice depends on rxdart ^0.25.0, every version of just_audio requires path_provider ^1.4.5.
So, because everyvoice depends on both path_provider ^2.0.2 and just_audio any, version solving failed.

Since local project is still at

sdk: ">=2.7.0 <3.0.0"

we cannot install just_audio for playback then, without changing to 

sdk: ">=2.12.1 <3.0.0", is that correct?
