### ISSUE TITLE
Streaming on iOS with 16000/8000 sample rate not working

### ISSUE THREAD

**Issue by mihirjsolguruz** [llfbandit/record#178]
**Package version**
5.0.0-beta.2

**Describe the bug**
We're working on Socket IO with mic streaming and for that we have to send chunk of mic streaming data with 16000 or 8000 sampling rate. Now, it's works perfectly with Android, but in iOS, it not working as expected. I can hear ghost sound if I stream audio with either 16000 or 8000 sample rate. It seems that whatever I pass value in sample rate, it will always stream with 44100 value. I'm using example provided with this package and Audacity for testing audio.

Thanks for your valuable time and this awesome package!

**To Reproduce**
1. Uncomment Streaming code and comment out the record code 
2. Set sampleRate: 16000
3. Do mic streaming 
4. Save raw data file and retrieve it using your preferred method (I'm using share_plus for it)
5. Open Audacity and click on File -> Import -> Raw data
6. Make a necessary adjustment in import settings (make sure to set sample rate to 16000)
7. Play the audio and you will get audio issue
8. Now, import this file again and this time set sample rate to 44100 and you will notice that it's working fine

Here is the code that I use for streaming:

```dart
Future<void> _start() async {
    try {
      if (await _audioRecorder.hasPermission()) {
        const encoder = AudioEncoder.pcm16bits;

        // We don't do anything with this but printing
        final isSupported = await _audioRecorder.isEncoderSupported(
          encoder,
        );

        debugPrint('${encoder.name} supported: $isSupported');

        final devs = await _audioRecorder.listInputDevices();
        debugPrint(devs.toString());

        const config =
            RecordConfig(encoder: encoder, numChannels: 1, sampleRate: 16000);

        
        String path;
        if (kIsWeb) {
          path = '';
        } else {
          final dir = await getApplicationDocumentsDirectory();
          path = p.join(
            dir.path,
            'audio_16000_${DateTime.now().millisecondsSinceEpoch}',
          );
        }

        // Record to file
        // await _audioRecorder.start(config, path: path);

        // Record to stream
        final file = File(path);
        final stream = await _audioRecorder.startStream(config);
        stream.listen(
          (data) {
            // ignore: avoid_print
            print(
              _audioRecorder.convertBytesToInt16(Uint8List.fromList(data)),
            );
            file.writeAsBytesSync(data, mode: FileMode.append);
          },
          // ignore: avoid_print
          onDone: () async {
            print('End of stream: $path');
            await Share.shareXFiles(
              [XFile(path)],
            );
          },
        );

        _recordDuration = 0;

        _startTimer();
      }
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
    }
  }
```

**Expected behavior**
It should record with given sample rate when streaming with either 16000 or 8000.

**Smartphone**
 - Device: iPhone 13 
 - OS: iOS 16.5.1

**Comment by llfbandit** [comment]
Thanks for the report.

I'm AFK until August now.
In the mean time, can you confirm if we're fine on macos?

**Comment by mihirjsolguruz** [comment]
Yes it's working fine on macOS

**Comment by hmm365** [comment]
I checked, but still have the same problem.

**Comment by mihirjsolguruz** [comment]
@llfbandit thanks for the update!
I have checked it and found that 16000 sample rate recording now works fine. 
And 8000 has still the same issue.

Thanks again for the fix!
