### ISSUE TITLE
record_linux-0.6.0: fmedia binary not found

### ISSUE THREAD

**Issue by Alexqwesa** [llfbandit/record#179]
record_linux-0.6.0: fmedia binary not found in package....

**Comment by llfbandit** [comment]
Did you followed linux install steps?

**Comment by Alexqwesa** [comment]
Just found how to install fmedia - ok, it's work)

but, previously fmedia was part of package record_linux - why it's not now?

**Comment by Alexqwesa** [comment]
ok, found https://github.com/llfbandit/record/issues/123
