### ISSUE TITLE
[Question] Working inside a PageView?

### ISSUE THREAD

**Issue by miriam-z** [llfbandit/record#18]
Copied most of the code, but inside a PageView works? As clicking it nothing happens and invalid argument(s)

i.e. 
![Screenshot 2021-06-17 at 20 02 14](https://user-images.githubusercontent.com/19760229/122457771-ea752a80-cfa6-11eb-9c33-ab63088b1ab4.png)

But upon clicking nothing happens

These won't work in sdk >=2.7.0 correct as late keyword is not recognized, but I didn't migrate to null-safety as there are many others that will require refactoring:

```
 /*late*/ Icon icon;
 /*late*/ Color color;
```

Used inside PageView, but not have tried PageView.builder or PageView.custom? 

![Screenshot 2021-06-17 at 20 50 36](https://user-images.githubusercontent.com/19760229/122463602-b5200b00-cfad-11eb-90c9-c16b63877935.png)

Turns out permission is not set? Even though Info.plist is set:

![Screenshot 2021-06-17 at 22 49 45](https://user-images.githubusercontent.com/19760229/122476540-50b97780-cfbe-11eb-91ad-a9036557c489.png)

Tried:
![Screenshot 2021-06-17 at 23 15 05](https://user-images.githubusercontent.com/19760229/122478737-dab70f80-cfc1-11eb-9bcb-281f746554c6.png)

but this no permission as caught by the _start() method

Do we need to migrate to null safety > 2.12.0 as currently on 2.7.0

Clicked to record, and now although permission seems to be granted, but didnt change to red and so clicking again:

![Screenshot 2021-06-18 at 00 25 42](https://user-images.githubusercontent.com/19760229/122484012-b8c28a80-cfcb-11eb-879b-1cea01ddc52c.png)

**Comment by bdremynoel** [comment]
Do you call `hasPermission()`?
PageView has nothing to do with this package.
