### ISSUE TITLE
Problem reading file when record is paused on iOS

### ISSUE THREAD

**Issue by pbaudri** [llfbandit/record#186]
**Package version**
`^5.0.0-beta.1`

**Describe the bug**
I try to record a voice, pause the audio so that I can play it back, and resume if I want to.

All this works on Android but I have a problem on iOS, where, until the record has been stopped, it's impossible to play the file.

It worked in version 4.4.4, but only on iOS, now it's the other way round.

**To Reproduce**
1. Click on record
2. Click on pause record
3. Try to read the file (I'm using `just_audio` or trying to find the file on the device)
4. Can't play the file

**Expected behavior**
I'd like to see the same behaviour between iOS and Android when it comes to using files generated by the record.

**Smartphone (please complete the following information):**
 - Device: Iphone 8 Plus
 - OS: 15.6.1

**Additional context**

Here's the code I'm using (I'd like to add that, even when using the stream on iOS, the behaviour remains the same.) :

```dart
  Future<void> _startRecord() async {
    final filePath = await _generateRecordingPath();
    _filePath = filePath;
    if (Platform.isIOS) {
      await recorderController.start(
        const RecordConfig(),
        path: filePath,
      );
    } else {
      final file = File(filePath);
      _audioRecordSubscription =
          (await recorderController.startStream(const RecordConfig()))
              .listen((bytes) {
        file.writeAsBytesSync(
          bytes,
          mode: FileMode.writeOnlyAppend,
        );
      });
    }
  }

  Future<String> _generateRecordingPath() async {
    final appDirectory = await getApplicationDocumentsDirectory();
    final path = '${appDirectory.path}/audio_${DateTime.now().millisecondsSinceEpoch}.m4a';

    return path;
  }
 ```

**Comment by shtreb** [comment]
The same problem

**Comment by llfbandit** [comment]
Thanks for the report.

Unfornutately, this behaviour has never been supported.
Unlikely, this behaviour can't supported on all platforms. Already, you were quite lucky to be able to read the partial file.

Still, I keep the issue open and maybe I'll revert iOS file recording after v5.0 release.

**Comment by Ali-Assi-AlGooru** [comment]
Hi @pbaudri, I can see that you are using just_audio with combination with record.

I'm using record 4.4.4, and it works fine on Android, but on iOS, I couldn't play the recorded audio. 

Have you faced such an issue? or do u have any suggestion to help me achieving that?

**Comment by llfbandit** [comment]
@pbaudri record_darwin 1.0.1 has been released and should fit you expectations.
Feedback welcome as always.
