### ISSUE TITLE
File doesn't exist on iOS

### ISSUE THREAD

**Issue by RedC4ke** [llfbandit/record#189]
**Package version**
5.0.0-beta.2

**Describe the bug**
Calling stop() on the AudioRecorder class returns the path to a file that doesn't exist

**To Reproduce**
1. Start the recording, providing a file path (temp directory in my case)
2. Record for a few seconds
3. Call stop and retrieve the temporary path
4. Create a File() passing the received path
5. Check the file with .exists() method
6. .exists() returns false

**Expected behavior**
I want the recorded file to be readable so I can copy it to the permanent storage.

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS 16.5.1

**Comment by RedC4ke** [comment]
I'd use the stable version but it throws some native exception, perhaps I'll submit a separate issue

**Comment by llfbandit** [comment]
How do you construct your file path?
What if you don't use temp directory to record?

**Comment by chenenyu** [comment]
The same issue! It wasted my whole day. 😭  @llfbandit

**Comment by llfbandit** [comment]
Please stop complaining and provide useful information or I will close this issue.

Can you, at least, confirm that the example works?

**Comment by tianlang8279** [comment]
so 
every time you record

record = AudioRecorder();
    await record.start(RecordConfig(encoder: GetPlatform.isAndroid ? AudioEncoder.wav : AudioEncoder.aacLc,),
      path: "${widget.dir.path}/audio_${DateTime.now().millisecondsSinceEpoch}.m4a",
    );

you can get the path！

**Comment by priyanshu-cilected** [comment]
> so every time you record
> 
> record = AudioRecorder(); await record.start(RecordConfig(encoder: GetPlatform.isAndroid ? AudioEncoder.wav : AudioEncoder.aacLc,), path: "${widget.dir.path}/audio_${DateTime.now().millisecondsSinceEpoch}.m4a", );
> 
> you can get the path！

On AudioRecoder.dispose() its giving 

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 1'

and app crashed

**Comment by Bernhard602** [comment]
I have the same problem on ios and I think I know what it is.

Right after: 
`final path = await _audioRecorder.stop();`

I get this error:
_Unhandled Exception: PathNotFoundException: Cannot open file, path = 'file:///private/var/mobile/Containers/Data/Application/4AB4A7AD-E252-4D95-8D0B-518F959D3A58/tmp/98114D77-EF3D-4B91-B59D-48B017DA980F.m4a' (OS Error: No such file or directory, errno = 2)_

**And as i see it the link is wrong, it is a mixture of two paths allowed by ios.**
described here: https://developer.apple.com/forums/thread/700772

the allowed paths are:
file:///var/mobile/Containers/Data/Application
file:///private/var/containers/Bundle/Application

the generated path file:///private/var/mobile/Containers/Data/Application is a mixture of both

**Comment by ekalosak** [comment]
I'm running into this issue as well on both 4.4.4 and 5.0.0-beta.2 on an ios 16.x simulator. Specifically, upon awaiting `shouldExist = record.stop()`, the file does not exist. I can create directories and files via `await myDirectory.create()` so it's not a permissions issue.
```
final Directory audioDir = await getApplicationDocumentsDirectory();
final File audioPath = File("${audioDir}.path/test.m4a");
await record.start(audioPath.toString());
... return, do other stuff, come back in separate function ...
shouldExist = await record.stop();
print(shouldExist);
print(File(shouldExist!).exists());
```
^ and the file path is good but the file itself does not exist.

This is a silent failure to flush to disk upon awaiting `record.stop()` as far as I can tell.

**Comment by flutter-painter** [comment]
Hi @llfbandit,

Could you please elaborate ? 
How would this work in https://github.com/llfbandit/record/blob/master/record/example/lib/main.dart

**Comment by llfbandit** [comment]
Getting the path from `stop` method, for now, may lead to this issue because on iOS there's a callback to complete the recording.
`stop` method only signals the action but the result isn't awaited.

This is why I asked to wait for `RecordState.stop` to deal with the file to confirm. The path is already known when starting the recording, it is only mandatory for web platform.

I record myself only few seconds, so completing the file does not take much time. I guess this is why I didn't encountered this issue.

**Comment by llfbandit** [comment]
record_darwin 1.0.0-beta.2+3 has been published to address this.
Upgrade your own dependencies to get the transitive dependency.

Feedback welcome!
