### ISSUE TITLE
Use mp4 for the output File

### ISSUE THREAD

**Issue by enviro-apps** [llfbandit/record#19]
Hello, I love the package. I just wanted to ask if it's possible to convert or directly record the audio in mp4 format. I tried using FFmpeg but it's a bit overpowered and too big. So I thought because I saw its possible on some other audio packages if its also possible here.

Let me know what you think.

Best Regards

**Comment by llfbandit** [comment]
Sure, use AAC variants or OPUS encoders, all are generating outputs with mpeg containers.

**Comment by enviro-apps** [comment]
Ok thank you so just setting the file path to path/filename.mp4 should be fine?

**Comment by llfbandit** [comment]
yes, I prefer the extension `.m4a` but it's up to you, the file name won't change its content.
