### ISSUE TITLE
Some background noise (Static Noise) reported from recorded audio in Android

### ISSUE THREAD

**Issue by patelnirav48** [llfbandit/record#190]
Here is the audio file in this link,
https://drive.google.com/file/d/1xZORGOu_I-BqheWRZsfZ_i4_1dV_M0CB/view?usp=sharing

Below is the device details

Mobile Brand:  Vivo V27
Android:  13 funtouch OS

@llfbandit Could you please help

**Comment by patelnirav48** [comment]
Noticed that on 4.4.4 version 5.0.0-beta.2, its working fine. what could be issue?

**Comment by llfbandit** [comment]
There are tons of improvements/fixes in upcoming v5.
v4 is no more supported, as I have not enough time to backport the changes.
