### ISSUE TITLE
when use listInputDevices function  on windows its notworking

### ISSUE THREAD

**Issue by MhdYhyaAlshaki** [llfbandit/record#192]
5.0.0-beta.2
 
when using the listInputDevices function  on Windows it's not working its shows this bug Unexpected extension byte

 
**Expected behavior**
return list of input devices
 
 - OS: Windows 11

**Comment by llfbandit** [comment]
Are you sure, your `record_windows` package is in version 1.0.0-beta.2?
It should be fixed in this version. Please, have a look to your pubspec.lock file to confirm this.

**Comment by MhdYhyaAlshaki** [comment]
this is the version is my file 
  record:
    dependency: "direct main"
    description:
      name: record
      sha256: e2132b14e061fb6083fd8d19dad6b33f64b0b40a33709724a031fdc090dc9553
      url: "https://pub.dev"
    source: hosted
    version: "5.0.0-beta.2"

**Comment by MxcodeBen** [comment]
I have same problem.
OS: Windows 11
record_windows: 1.0.0-beta.2

**Comment by llfbandit** [comment]
In what language is your OS? Does your language require UTF-16?

**Comment by llfbandit** [comment]
UTF 16 to 8 has been reworked. Please let me know if this solve the issue.
record_windows 1.0.0-beta.2+1
