### ISSUE TITLE
Multi-channel recording feature incomplete

### ISSUE THREAD

**Issue by C-gotoh** [llfbandit/record#193]
**Package version**
4.4.4

**Describe the bug**
`record.start` `numChannels` parameter does not support values bigger than 2.

**To Reproduce**
1. Start a recording using `record.start(numChannels: 6)`
2. The recording fails silently

**Expected behavior**
A recording should be created with 6 channels.
The parameter 6 should be converted to 5.1 for the linux platform implementation using fmedia.

**Additional context**
I'm using the library on linux. fmedia supports multi-channel recording using the `--channels=5.1` flag for example.
The `record_platform_interface` spec only allows int as input for `numChannels`, so the string parameter can not be applied correctly.
The same issue should exist for windows, but I haven't tested it.

**Comment by llfbandit** [comment]
Thanks for the report.
I added this in published version 0.7.0 but you will need v5 of record. Linux package has just been aligned between v4 and v5.
