### ISSUE TITLE
Distorted audio recordings on web

### ISSUE THREAD

**Issue by CedricVandelaer** [llfbandit/record#194]
**Package version**
5.0.0-beta.2

**Describe the bug**
I have been struggling to get correct audio recordings in the browser. The audio sounds slowed down and distorted.

I record a stream, visualize the datachunks, keep each sample in a list and then encode the list of values to wav to send to a speech to text server.

Config:
```
final RecordConfig _config =
      const RecordConfig(encoder: AudioEncoder.pcm16bits, numChannels: 2);
```

Code for recording:
```
   void _startRecording() async {
    setState(() {
      _isRecording = true;
    });

    if (await _recorder.hasPermission() == true) {
      final stream = await _recorder.startStream(_config);

      stream.listen((data) {
        _audioData.addAll(convertBytesToInt16(data));
      });
    }
  }

  void _stopRecording() async {
    await _recorder.stop();

    setState(() {
      _isRecording = false;
    });

    var response = await _sendAudioForInference();
    _audioData = [];

    widget.onSpeechTranscribed(response);
  }
```

Conversion to 16-bit from 8-bit samples:
```
List<int> convertBytesToInt16(Uint8List data) {
    var bytesPerSample = 2;
    var isLittleEndian = true;
    List<int> values = [];

    for (int i = 0; i < data.lengthInBytes; i += bytesPerSample) {
      int sample = 0;
      for (int j = 0; j < bytesPerSample; j++) {
        int byte =
            isLittleEndian ? data[i + j] : data[i + bytesPerSample - j - 1];
        sample |= byte << (j * 8);
      }
      // Process the PCM sample (interpret as signed 16-bit integer)
      values.add(sample.toSigned(16));
    }

    return values;
}
```

Conversion to Wav:
```
Uint8List convertPcmToWav(List<int> pcmData,
    {int sampleRate = 44100, int numChannels = 1, int bitsPerSample = 16}) {
  // Validate that pcmData values are in 16-bit range
  for (int sample in pcmData) {
    if (sample < -32768 || sample > 32767) {
      throw ArgumentError("PCM data value out of range for 16-bit audio");
    }
  }

  // Create a ByteData to write the WAV file
  var wavHeaderSize = 44; // Standard WAV header size
  var totalSize = wavHeaderSize + pcmData.length * 2;
  var byteData = ByteData(totalSize);

  // Write the RIFF header
  byteData.setUint8(0, 'R'.codeUnitAt(0));
  byteData.setUint8(1, 'I'.codeUnitAt(0));
  byteData.setUint8(2, 'F'.codeUnitAt(0));
  byteData.setUint8(3, 'F'.codeUnitAt(0));
  byteData.setUint32(4, totalSize - 8, Endian.little);
  byteData.setUint8(8, 'W'.codeUnitAt(0));
  byteData.setUint8(9, 'A'.codeUnitAt(0));
  byteData.setUint8(10, 'V'.codeUnitAt(0));
  byteData.setUint8(11, 'E'.codeUnitAt(0));

  // Write the fmt subchunk
  byteData.setUint8(12, 'f'.codeUnitAt(0));
  byteData.setUint8(13, 'm'.codeUnitAt(0));
  byteData.setUint8(14, 't'.codeUnitAt(0));
  byteData.setUint8(15, ' '.codeUnitAt(0));
  byteData.setUint32(16, 16, Endian.little); // Subchunk size
  byteData.setUint16(20, 1, Endian.little); // Audio format (1 = PCM)
  byteData.setUint16(22, numChannels, Endian.little);
  byteData.setUint32(24, sampleRate, Endian.little);
  byteData.setUint32(28, sampleRate * numChannels * (bitsPerSample ~/ 8),
      Endian.little); // Byte rate
  byteData.setUint16(
      32, numChannels * (bitsPerSample ~/ 8), Endian.little); // Block align
  byteData.setUint16(34, bitsPerSample, Endian.little);

  // Write the data subchunk
  byteData.setUint8(36, 'd'.codeUnitAt(0));
  byteData.setUint8(37, 'a'.codeUnitAt(0));
  byteData.setUint8(38, 't'.codeUnitAt(0));
  byteData.setUint8(39, 'a'.codeUnitAt(0));
  byteData.setUint32(40, pcmData.length * 2, Endian.little);
  for (int i = 0; i < pcmData.length; i++) {
    byteData.setInt16(wavHeaderSize + i * 2, pcmData[i], Endian.little);
  }

  return byteData.buffer.asUint8List();
}
```

Send audio to server:
```
    final request = http.MultipartRequest('POST', uri)
      ..files.add(http.MultipartFile.fromBytes(
        'audio', // The key for the file
        convertPcmToWav(_audioData), // The binary data
        filename: 'audio.wav',
        contentType: MediaType('audio', 'wav'),
      ));
```

**To Reproduce**
Use the code in the description.

**Expected behavior**
I expected recorded wav file (which is simply being saved on the server) to have clear audio.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version 115.0.5790.171 

I hope this is clear. I'd very much appreciate the help, thank you for creating this package.

**Comment by ocinon** [comment]
I've been running into the same issue. Both streaming and regular recording exhibit the issue (tested with pcm16bits). It works fine with a Windows build but is distorted on any browser (Chrome, Edge, Firefox). All sampling frequencies I tried were distorted (8, 16, 44.1, 48 kHz).

Any help is appreciated.

**Comment by llfbandit** [comment]
Thanks for the report. Looking into this.

**Comment by llfbandit** [comment]
record_web 1.0.0-beta.2+1 has been published to fix this. Let me know.

**Comment by ocinon** [comment]
@llfbandit thank you for the quick reply and update! The update definitely made it quite a bit better, but the recording is still a bit slower and "slurred". It also sounds very harsh/with sound artifacts, which might come from dropped frames.

**Comment by CedricVandelaer** [comment]
I also noticed an improvement, it's less distorted but still very noticeable and slowed down. Thank you for the quick update though!

**Comment by bdremynoel** [comment]
Thanks for the feedback. I found the issue but I discovered another one when recording with more than 1 channel.
Hope to find a definitive very soon.

**Comment by llfbandit** [comment]
Finally fixed it, still need a bit of testing and will release an updated version of the record_web package tomorrow.

**Comment by llfbandit** [comment]
Availlable in record_web 1.0.0-beta.2+2. Feedback needed to close this issue. Thanks.

**Comment by ocinon** [comment]
@llfbandit thank you so much for the quick fix!

On Chrome and Edge, I could get it to work and tested both 16 and 44.1 kHz, which is working great now! On Firefox, I could not get it to work. For one, mismatching sample rates seem to create an issue, but even after setting it to 48 kHz, which it accepted, it threw this error (both when using 1 or 2 channels for the recording):

`TypeError: input[channel] is undefined [record.worklet.js:57:36]`

**Comment by CedricVandelaer** [comment]
@ocinon Do you have the same interpretation of the Uint8list as I have in my code sample? In my latest test, the audio is no longer distorted but the tones seem to be much lower than the original. My encoding can be wrong too but in this case I don't know where the error is.

**Comment by CedricVandelaer** [comment]
Maybe for some additional clarity on what I mean by lower tones I'll upload an audio sample.
[audio_test.zip](https://github.com/llfbandit/record/files/12389039/audio_test.zip)

**Comment by CedricVandelaer** [comment]
My bad, I revisited my code and saw that the number of channels was not matching, which caused the slowed down audio, it is working for me in all chromium based browsers, thank you!

**Comment by llfbandit** [comment]
record_web 1.0.0-beta.2+3 has been published. This issue should be gone now.
As always, feedback welcome!

**Comment by ocinon** [comment]
@llfbandit record_web 1.0.0-beta.2+3 is completely unusable for me. I didn't test it properly but I'm streaming the mic data and that seems to have broken something. I had to downgrade.

**Comment by llfbandit** [comment]
record_web version 1.0.0-beta.2+4 has been published. I re-created an issue when adding constrainsts adjustments.
I don't know if this was the problem you encountered.

**Comment by ocinon** [comment]
For me, record_web version 1.0.0-beta.2+4 is not working either. beta.2+2 was working. I still needed to look into the output being produced, but sending it to a voice recognition service delivered unusable results.

**Comment by llfbandit** [comment]
record v5 has been released with corresponding fix on this.
