### ISSUE TITLE
_audioRecorder.stop() iOS file not present error

### ISSUE THREAD

**Issue by sajanyamaha** [llfbandit/record#20]
Android works fine but in iOS ,

On file length check `onTap()` ,

```
file = File(audioPath);
int sizeInBytes = await file.length();
```

`[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot retrieve length of file, path = 'file:///thefilepath/tmp/CB3B3C63-B2CA-427D-AB23-766F76234413.m4a' (**OS Error: No such file or directory**, errno = 2)`

But when I check the file location its available there . It means the file is not place in that location instantly when the path is returned by `_audioRecorder.stop()` , 

How can this is handled?

**Comment by llfbandit** [comment]
There is no file manipulation, the provided file path is where the data is written.

**Comment by scheung38** [comment]
Hi @llfbandit Also asking same thing: https://github.com/llfbandit/record/issues/26

**Comment by rvndsngwn** [comment]
`Unhandled Exception: FileSystemException: Cannot open file, path = 'file:///private/var/mobile/Containers/Data/Application/02XXXXD-7XX3-4XXX-XXXX-3XXXXXXX3/tmp/9XXXXX-5295-XXX-XXXX-XXXX97E8EE2.m4a' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1362:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
<asynchronous suspension>`

Same issue I have! Any solution for IOS ?

**Comment by rvndsngwn** [comment]
> `Unhandled Exception: FileSystemException: Cannot open file, path = 'file:///private/var/mobile/Containers/Data/Application/02XXXXD-7XX3-4XXX-XXXX-3XXXXXXX3/tmp/9XXXXX-5295-XXX-XXXX-XXXX97E8EE2.m4a' (OS Error: No such file or directory, errno = 2) #0 _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9) #1 _rootRunUnary (dart:async/zone.dart:1362:47) #2 _CustomZone.runUnary (dart:async/zone.dart:1265:19) <asynchronous suspension>`
> 
> Same issue I have! Any solution for IOS ?

I just replace this line file = File(path); to file = File.fromUri(Uri.parse(path)); and error solved. Thanks @scheung38

**Comment by juniorbomb** [comment]
> > `Unhandled Exception: FileSystemException: Cannot open file, path = 'file:///private/var/mobile/Containers/Data/Application/02XXXXD-7XX3-4XXX-XXXX-3XXXXXXX3/tmp/9XXXXX-5295-XXX-XXXX-XXXX97E8EE2.m4a' (OS Error: No such file or directory, errno = 2) #0 _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9) #1 _rootRunUnary (dart:async/zone.dart:1362:47) #2 _CustomZone.runUnary (dart:async/zone.dart:1265:19) <asynchronous suspension>`
> > Same issue I have! Any solution for IOS ?
> 
> I just replace this line file = File(path); to file = File.fromUri(Uri.parse(path)); and error solved. Thanks @scheung38

Thanks @rvndsngwn, works for me
