### ISSUE TITLE
Platformexception on windows 

### ISSUE THREAD

**Issue by moham96** [llfbandit/record#204]
**Package version**
5.0.0-beta.2

**Describe the bug**
Throws `PlatformExeption` when running `start` or `startStream`

**To Reproduce**
1. Git clone the repo
2. Run the example on windows
3. Start the recording
4. It will throw the error

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: windows 11

**Comment by moham96** [comment]
So i did a git bisect and the first bad commit is 
https://github.com/llfbandit/record/commit/a11a5ae79c6ac83dd31ae3befa0db76852c11e83

Since that commit, recording to wav and pcm16bits doesn't work
Aaclc fine though

**Comment by llfbandit** [comment]
Thanks for the report.
A fix has been published in record_windows 1.0.0-beta.2+1.
Feedback welcome!

**Comment by moham96** [comment]
> Thanks for the report. A fix has been published in record_windows 1.0.0-beta.2+1. Feedback welcome!

Yes it works now, please update the `pubspec.yaml` file in the `record` package so that it pulls the "1.0.0-beta.2+1." version of `record_windows`
