### ISSUE TITLE
Package init failed on Android's web browser

### ISSUE THREAD

**Issue by AriHuang** [llfbandit/record#206]
**Package version**
  record: ^5.0.0-beta.3

**Describe the bug**
All API is blocked and not return.( eg. listInputDevices, hasPermission ...). Base on the code that I can, I think the _createCompleter is not completed. The same code is work fine in Chrome in the window computer.  
Since it is in web of the mobile device, I don't know how to capture the log.

**To Reproduce**
run follow code, 
    record??= AudioRecorder();
    onStatusChange('create AudioRecorder');
    var devices = await record?.listInputDevices();
    onStatusChange('devices: ${devices?.first.label}');  ****<=== Never print out****

**Expected behavior**
The function should work in mobile's web browser as desktop's browser. 

**Smartphone (please complete the following information):**
 - Device:  Samsung A71
 - OS: Android 13
 - Browser: Chrome and Firefox
 - Version [114.0.5735.196]/[11.2.1]

**Additional context**

**Comment by llfbandit** [comment]
Just tested it on Firefox mobile (118beta): `hasPermission, start, pause and stop` were working fine.
`_createCompleter` on web platform only instantiate a delegate and there's no reason to fail here. It's not even async.

Be sure to call `hasPermission` before calling any other methods maybe your issue located here.

**Comment by AriHuang** [comment]
After has more testing, I think my local package was broken. It works fine in Android mobile after clean and rebuild. Sorry for inconvenient.
