### ISSUE TITLE
Amplitude Listeners are only updated on the first recording unless subsequent recordnings are paused and resumed.

### ISSUE THREAD

**Issue by adechant** [llfbandit/record#207]
**Package version**
^5.0.0-beta.3

**Describe the bug**
Amplitude subscription does not restart when making a second recording.

**To Reproduce**
Create a new audiorecorder. Add an amplitude subscription. start recording. Amplitude listener will work appropriately. Stop recording. Start a second recordning. Amplitude listener does not get updated. 

**Expected behavior**
Amplitude listeners should be always updated when recording.

**Desktop (please complete the following information):**
 - OS: windows (in looking at the code, this is a flutter issue, so it should be reproducible on all platforms).

**Additional context**
Fix: _startAmplitudeTimer(); should not be called in onAmplitudeChanged, but in the start() method.

**Comment by llfbandit** [comment]
Thanks for the report.

record 5.0.0-beta.3+1 has been published to address this.
