### ISSUE TITLE
While recording cannot able to adjust device volume

### ISSUE THREAD

**Issue by patelnirav48** [llfbandit/record#209]
@llfbandit In Version 4.4.4 it was working fine but in Prerelease: [5.0.0-beta.3] when we start record cannot able to adjust device volume even after stop recording. So with audio player cannot able to hear audio and not allowing to increase volume.

**Comment by llfbandit** [comment]
You mean you can't set the volume from the device buttons?
This is unclear to me sorry.

**Comment by patelnirav48** [comment]
When i start record and press volume up/down button from iPhone (iOS) its not displaying volume control in Prerelease: [5.0.0-beta.3], and even after stopping audio recording its not allowing to increase or decrease volume. (I'm setting this audio session https://prnt.sc/8yDJRcUtPPs6 properties before recording, from audio_session library)

Later after some research i have to set this properties again to make work it before playing audio (https://prnt.sc/p2LdCRue8HqD), this changes were i was not doing in Version 4.4.4. so not sure is it correct way or not?

**Comment by llfbandit** [comment]
I guess you should match what is configured by the pugin to not conflict with it.

Here's the relevant setup for iOS:
https://github.com/llfbandit/record/blob/348dc7140d98e95f725757a2c35d414407272ad0/record_darwin/ios/Classes/RecorderIOS.swift#L5

Can I ask you for what purpose you use audio_session with this plugin?

**Comment by patelnirav48** [comment]
I'm using audio_session to handle interruption scenarios https://prnt.sc/8fLdwYRgfl0Q

**Comment by patelnirav48** [comment]
Okay, let me check. Thanks

**Comment by pye52** [comment]
I am also facing the same issue. On iOS, the sound in version 5.2.0 is very quiet, while it is normal in version 4.4.4. Both versions are normal on Android.

**Comment by hewcheehau** [comment]
@pye52 I am facing this issue too. When upgrade to 5.0.1, iOS record volume become very low compare to v4.

**Comment by llfbandit** [comment]
Should be fixed in `record_darwin: ^1.0.1-beta.1`. You will need to add it manually to test it.

**Comment by llfbandit** [comment]
Released in record_darwin 1.0.1
