### ISSUE TITLE
channel sent a message from native to Flutter on a non-platform thread

### ISSUE THREAD

**Issue by jamescrosswell** [llfbandit/record#210]
**Package version**
5.0.0-beta.2

**Describe the bug**
When deploying to a physcal iOS device (I was testing on an iPhone 11) calling `AudioRecorder.startStream` results in the following error/warning in the DEBUG console:

> [VERBOSE-2:shell.cc(1004)] The 'com.llfbandit.record/events/dc363add-6318-4603-9e58-4b1112927c30' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
 

**To Reproduce**
1. I've got a minimal reproducable example in the repo at https://github.com/jamescrosswell/non-plafrom-thread
2. Clone that repo 
3. Set the TEAM in `Signing & Capabilities` in the Runner targets section of the `ios/Runner.xcodeproj/project.pbxproj` file (since you can't publish to physical devices without signing the application)
4. Run the app on a physical device
5. Give permissino to record audio (of course)
6. Hit the play/record button
7. You should see an error like the following in your debug console

![image](https://github.com/llfbandit/record/assets/728212/98b70fdd-64b5-44c1-9f94-91d2bf865f43)

**Expected behavior**
Platform channel messages should be sent on the platform thread and the app shouldn't generate this warning/error.

**Desktop (please complete the following information):**
 - OS: I'm using macOS Ventura 13.6
 - Browser n/a

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS
 - Version 16.5

**Additional context**
I didn't observe this in the [example project in the record repo](https://github.com/llfbandit/record/tree/master/record/example)... so it may have something to do with providers (which is why I'm doing the recording from a ChangeNotifier in the reproducible example I provided). That probably requires a bit more experimenting to determine.

**Comment by llfbandit** [comment]
Thanks for the report.
record_darwin 1.0.0-beta.2+3 has been published to address this.
Upgrade your own dependencies to get the transitive dependency.

Feedback welcome!

**Comment by jamescrosswell** [comment]
Thanks @llfbandit, that gets rid of the warning!
