### ISSUE TITLE
Recorded audio can't be played using just_audio player on iOS

### ISSUE THREAD

**Issue by Ali-Assi-AlGooru** [llfbandit/record#217]
**Package version**
4.4.4

**Describe the bug**
I'm using just_audio package to play the recorded voice note.
But it seems like there's a problem with the recored audio on iOS, while it works perfectly on Android. 

I've tried to record through Android, upload it to db, then fetch the same recorded audio on iPhone, it worked.

I've tried to download audio sample with .m4a extension, and play it on iPhone, it worked.

I've tried to get the record an audio, and add it as asset then try to play it, it didn't work

I've tried all the possible available encoders, but nothing has changed.

**To Reproduce**
1. Record and audio on iPhone device
2. Play it using just_audio player
3. Audio can't be played

**Expected behavior**
I'd expect to get the recorded audio on iOS, to be playable immediately on the same device.

Is there any issue with using adjust_audio as a player with record package? 
**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.3.1

**Comment by jamescrosswell** [comment]
Not sure if this helps, but it might be [related to this](https://github.com/llfbandit/record/issues/214#issuecomment-1760602129). I'm not familiar with just_audio so don't know if it also exposes the `AVAudioSessionCategory` somehow.

**Comment by llfbandit** [comment]
Thanks for the report.
v4 was pretty messy with file recording and path output.
v5 is out now, please give it a try as there's no more path internal manipulation.

Also, a note, I'm not responsible of playing audio.

**Comment by Ali-Assi-AlGooru** [comment]
Thank you for your help here @jamescrosswell  @llfbandit

With v4, I was able to fix that issue by defining the path. It worked on Android without the optional path, but it didn't on iOS. 

I'm excited about version 5 and will definitely migrate to it.

Thanks again for your help!
