### ISSUE TITLE
AudioRecord.ERROR_INVALID_OPERATION

### ISSUE THREAD

**Issue by ShiChenZhi** [llfbandit/record#218]
**Package version**
Reading of audio buffer failed: AudioRecord.ERROR_INVALID_OPERATION

**Describe the bug**
Reading of audio buffer failed: AudioRecord.ERROR_INVALID_OPERATION

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by llfbandit** [comment]
Please respect the given template. I can't help you from this report.
