### ISSUE TITLE
MacOS's iOS simulator stopped working (Used to work on v4.4.4)

### ISSUE THREAD

**Issue by taufiq-husain** [llfbandit/record#221]
**Package version**
5.0.1

**Describe the bug**
MacOS's iPhone simulator stopped recording audio
I was using 4.4.4 version correctly on the MacOS's iPhone simulator, iPhone device as well as Android device. It was working perfectly fine but upgrading to 5.0.1 stopped it from working on the simulator. I reverted back to version 4.4.4 for my app.

**Expected behavior**
Should play on the MacOS's iPhone simulator just like it used to for version 4.4.4

**Desktop (please complete the following information):**
 - MacOS - Sonoma 14.0
 - iOS Simulator - iPhone 15 Pro Max, iOS 17

**Comment by llfbandit** [comment]
Simulator is not supported, use a real device instead

**Comment by lucasjinreal** [comment]
@llfbandit Hi, macOS itself didn't support as well.!
