### ISSUE TITLE
Not working on a iOS SImulator

### ISSUE THREAD

**Issue by moinsendev** [llfbandit/record#222]
**Package version**
record: ^5.0.1

**Describe the bug**
I just cloned this github repo and run the example on a new iOS 15 Simulator.

I my own app it happens the same thing. It works on a real iOS Device.

**To Reproduce**
clone this repo 
goto example
run the app on a iOS Simulator

** Error**
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
main.dart:1
Xcode build done.                                            7.3s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
Connecting to VM Service at ws://127.0.0.1:51281/VCYC7P59HWg=/ws
flutter: wav supported: true
flutter: []
flutter: PlatformException(record, Failed to start recording, Input device not found., null)

**Expected behavior**
Test the app on a simulator

**Additional context**
This is my first use of this package.

**Comment by StevenMorlier** [comment]
Hello,
I get the same error on MacM1 / IOS Simulator / Iphone SE.

**Comment by llfbandit** [comment]
iOS simulator does not handle/implement input device selection. There's nothing I can do for this.
Unfortunately from here, this issue is more for Apple than me.

**Comment by D-Idan** [comment]
Hi,
Any way to run the example? changes needed?

**Comment by udiedrichsen** [comment]
I think its important to get this on the simulater working. I develop my apps mainly on a simulator.

https://github.com/opunAI/flutter_sound/tree/master

Works on the simulator.

**Comment by willxie** [comment]
I am having the same issue. It was working prior to upgrading to record: 5.0.

**Comment by llfbandit** [comment]
Should be fixed in `record_darwin: ^1.0.1-beta.1`. You will need to add it manually to test it.

**Comment by StevenMorlier** [comment]
> Should be fixed in `record_darwin: ^1.0.1-beta.1`. You will need to add it manually to test it.

It works for me, thanks a lot !

**Comment by PoplarZhaoYang** [comment]
> Should be fixed in `record_darwin: ^1.0.1-beta.1`. You will need to add it manually to test it.应修复在 `record_darwin: ^1.0.1-beta.1` 中。您需要手动添加它来测试它。

yes, just add it. it works!

**Comment by llfbandit** [comment]
Released in record_darwin 1.0.1
