### ISSUE TITLE
Fails to start recording in Safari 16.6 or above on Desktop (Mac OS) (Mobile appears ok.)

### ISSUE THREAD

**Issue by gam-aaron** [llfbandit/record#223]
master / 5.0.1

Using the example code, desktop safari reports -160 Amplitude and quickly fails with:
2-3 instances of: 

"A MediaStreamTrack ended due to a capture failure". 

in logs.

Open example project, build web, deploy or run, run in Safari on same port if run directly, or against deploy build.  
Safari desktop 16.6 or above (quick tests show 17 fails similarly) will error as above

Other versions of Safari appear to work correctly - Tested 16.2, 16.3.

As this is not limited to an old Safari only and appears to be across latest releases., I would assume that this is a change in Safari that may persist going forward.  Online mic tests in safari still work as well.  

Working to find issue to fix, but any assistance would be very helpful.

Mac OS Ventura 13.5
Safari 16.6

**Comment by llfbandit** [comment]
Thanks for the report.
record_web 1.0.2 has fixes with audio thread. It may worth a try.
I suppose that your output is WAV or PCM.

**Comment by gam-aaron** [comment]
Attempted with:
  record: ^5.0.1
  record_web: ^1.0.2

and AudioEncoder.wav

Safari 16.6 on OSX still errors after around 4 seconds.

**Comment by willxie** [comment]
I am also having trouble with running on MacOS safari

Using `.wav`, start recording get's stuck for some 5 seconds. And the resulting audio file has no content in it. Mic is detected. 

Using `.opus`, I cannot get the recording to finish.

Using `.pcm`, I am not very familiar with this format. Opening it on Audacity shows no data.

Same code works on Chrome well. Same logic also worked on record 4.4.4 on Safari. 

I'm on
Safari 17
MacOs 14

**Comment by gam-aaron** [comment]
Update: This seems to work now.

- Make sure you are using latest flutter. (Flutter 3.13.9 • channel stable)
- For wav, you may need to set specific sample rate - 24000

Not sure if related, but record_web 1.0.3.
