### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)

### ISSUE THREAD

**Issue by lucasjinreal** [llfbandit/record#226]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, AVPlayerItem.Status.failed on setSourceUrl, null)

**Comment by lucasjinreal** [comment]
not work on macOS at all.

**Comment by llfbandit** [comment]
Should be fixed in `record_darwin: ^1.0.1-beta.1`. You will need to add it manually to test it.

**Comment by lucasjinreal** [comment]
hi, android not work as well..... the whole lib just didn't get record path correctly, the path specified but returns are not exist, which means the voice didn't get saved in local..

**Comment by llfbandit** [comment]
My previous comment was a mistake, it should be here. First, respecting the issue template is more than helpful to get all information.
Second, stick to the reported issue and don't mix subjects. 
If you are in version 4. This version is not supported anymore. There was path issues back then.
Otherwise, have a look to the example to know how to provide a correct path.

Finally, open a new issue with detailed info if you confirm this.

**Comment by lucasjinreal** [comment]
@llfbandit  Hello, I'm not here to nitpick, this project is great, my questions may be some small issues, but it seems that they can't be used out-of-the-box.

First of all, this is version I use: `record: ^5.0.0-beta.3`


And this is how the simplest way I try to record:

```dart
...
  final record = AudioRecorder();
...

if (await record.hasPermission()) {
                // 震动反馈
                HapticFeedback.heavyImpact();

                setState(() {
                  _voiceRecording = true;
                  _voiceStartTime = DateTime.now();
                });

                final directory = await getTemporaryDirectory();
                if (!await directory.exists()) {
                  await directory.create();
                }
                String tmpPath = directory.path + '/a.mp3';
                // Start recording
                await record.start(
                    RecordConfig(
                        encoder: AudioEncoder.aacLc, // by default
                        bitRate: 128000, // by default
                        sampleRate: 44100),
                    path: tmpPath);

                setState(() {
                  _millSeconds = 0;
                });
                if (_timer != null) {
                  _timer!.cancel();
                  _timer = null;
                }

                _timer = Timer.periodic(const Duration(milliseconds: 100),
                    (timer) async {
                  if (_voiceStartTime == null) {
                    timer.cancel();
                    return;
                  }

                  if (DateTime.now().difference(_voiceStartTime!).inSeconds >=
                      60) {
                    await onRecordStop();
                    return;
                  }

                  setState(() {
                    _millSeconds = DateTime.now()
                        .difference(_voiceStartTime!)
                        .inMilliseconds;
                  });
                });
              }

```

Unless I miss something, otherwise this should work as expected. 

But tmp path I send, after record, I open it just always not exist.
