### ISSUE TITLE
"Content size exceeds specified contentLength" error when load the audio file immediately after executing the await stop() method in Android OS

### ISSUE THREAD

**Issue by pkh31337** [llfbandit/record#227]
**Package version**
5.0.1 

**Describe the bug**
In Android OS, if you try to load the audio file of the path in your local device immediately after executing the await stop() method asynchronously, an error("Content size exceeds specified contentLength") occurs because MediaWriter and MPEG4Writer have not yet completed execution.

Please note that this bug does not exist in 4.x versions. So I'm currently using an older version. Nevertheless, I appreciate your management of such a valuable package.

**To Reproduce**
1. Specify the path as local to the device.
2. Execute the await stop() method asynchronously.
3. Run the audio file saved in the returned path without any delay.
4. See error.

If you add the code below after the await stop() method, no error will occur. 
`await Future.delayed(const Duration(milliseconds: 100));
`

**Expected behavior**
No error occurred.

**Smartphone**
 - Device: Pixel 7 Pro 
 - OS: Android 13.0
 - Version: API 33
(Only tested it on Android)

**Additional context**

Here is the log for comparison. When there is an error, Logger shows the contents of the corrupted audio file. Considering that MediaWriter and MPEG4Writer are outputting logs in between Loggers, it is assumed that asynchronous processing is being performed inappropriately.

1. Logging without any delay: error
D/CCodecBufferChannel(21220): [c2.android.aac.encoder#141] buffers after EOS ignored (0 us)
D/CCodecBufferChannel(21220): [c2.android.aac.encoder#141] buffers after EOS ignored (0 us)
I/flutter (21220): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (21220): │ #0   Test._record.<anonymous closure> (package:test/test.dart:91:38)
I/flutter (21220): │ #1   <asynchronous suspension>
I/flutter (21220): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (21220): │ 🐛 ClientException: Content size exceeds specified contentLength. 24562 bytes written while expected 23527. [
I/flutter (21220): │ 🐛 ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ]é´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´¼!æ Y]\S.U&I´¢J ²8ÿ# 6¬% ÕâRÉñð^J­r,8¼´¾GàÄ!»C=ÆHì5ä´Û<KjMD!S
I/flutter (21220): │ 🐛 Æ¦
D/CCodecBufferChannel(21220): [c2.android.aac.encoder#141] buffers after EOS ignored (0 us)
I/flutter (21220): │ 🐛 
V/MediaWriter(21220): Track event err/info msg:101, trackId:1, type:1000,val:0
I/MPEG4Writer(21220): Received total/0-length (57/0) buffers and encoded 57 frames. - Audio
I/MPEG4Writer(21220): Audio track drift time: 0 us
I/flutter (21220): │ 🐛 ðe<ÛõQ6}zû¨¿²þëds87]se»ÎM n¾ÏE®Äj÷þB1/íUïå®÷OÖUäK­¦@òoíË5^ÏÅ#åf^^Vàûþ'â±-¾º$}¾ÏFÔ#
D/MPEG4Writer(21220): reset()
D/MPEG4Writer(21220): Audio track stopping. Stop source
D/MPEG4Writer(21220): Audio track source stopping
D/MPEG4Writer(21220): Audio track source stopped
I/flutter (21220): │ 🐛 (Aí|ÛURÑQU2ÒÊ×jXJð
D/MPEG4Writer(21220): Audio track stopped. Status:0. Stop source
D/MPEG4Writer(21220): 0 chunks are written in the last batch
D/MPEG4Writer(21220): WriterThread stopped. Status:0
I/MPEG4Writer(21220): Adjust the moov start time from 0 us -> 0 us
I/MPEG4Writer(21220): MOOV atom was written to the file
D/MPEG4Writer(21220): release()
D/MPEG4Writer(21220): ftruncate mPreAllocateFileEndOffset:25859 mOffset:933 mMdatEndOffset:24207 diff:1652
I/flutter (21220): │ 🐛 ªk
I/flutter (21220): │ 🐛 ®|µô`¸KCìX·íU{­k{Ò·È×òÇÍ5W¢ÈæF#U£\/ ôM<-RCR»åÑìô;@+áÜ;^S­#IºNý,ä¦±'ÐR£ÈÝ®³+&ä±ÆhÝÈÊSb²ËMëKF
I/flutter (21220): │ 🐛 ¨Õm}^¥ó4VÖ¿k¡jqùÞÏtl­YNéÕ:ù@ß66pÇ$s¿ÿOÓþÒ	Oé¼á=w{óxOØòú¤t×!¸!p;-×ÆøÜ÷3°mÅÕíOd!Øý}*
I/flutter (21220): │ 🐛 s»|
I/flutter (21220): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/MPEG4Writer(21220): final fsync() takes 9 ms, file size 24207
D/MPEG4Writer(21220): MP4WtrCtrlHlpLooper stopped
D/MPEG4Writer(21220): Top 5 write durations(microseconds): #1:21 #2:27 #3:28 #4:35 #5:108
D/MPEG4Writer(21220): reset()
D/MPEG4Writer(21220): Audio track stopping. Stop source
E/MPEG4Writer(21220): Stop() called but track is not started or stopped
I/hw-BpHwBinder(21220): onLastStrongRef automatically unlinking death recipients

2. Logging with delay: no error
D/CCodecBufferChannel(20027): [c2.android.aac.encoder#288] buffers after EOS ignored (0 us)
D/CCodecBufferChannel(20027): [c2.android.aac.encoder#288] buffers after EOS ignored (0 us)
D/CCodecBufferChannel(20027): [c2.android.aac.encoder#288] buffers after EOS ignored (0 us)
V/MediaWriter(20027): Track event err/info msg:101, trackId:1, type:1000,val:0
I/MPEG4Writer(20027): Received total/0-length (59/0) buffers and encoded 59 frames. - Audio
I/MPEG4Writer(20027): Audio track drift time: 0 us
D/MPEG4Writer(20027): reset()
D/MPEG4Writer(20027): Audio track stopping. Stop source
D/MPEG4Writer(20027): Audio track source stopping
D/MPEG4Writer(20027): Audio track source stopped
D/MPEG4Writer(20027): Audio track stopped. Status:0. Stop source
D/MPEG4Writer(20027): 0 chunks are written in the last batch
D/MPEG4Writer(20027): WriterThread stopped. Status:0
I/MPEG4Writer(20027): Adjust the moov start time from 0 us -> 0 us
I/MPEG4Writer(20027): MOOV atom was written to the file
D/MPEG4Writer(20027): release()
D/MPEG4Writer(20027): ftruncate mPreAllocateFileEndOffset:26616 mOffset:941 mMdatEndOffset:24956 diff:1660
D/MPEG4Writer(20027): final fsync() takes 4 ms, file size 24956
D/MPEG4Writer(20027): MP4WtrCtrlHlpLooper stopped
D/MPEG4Writer(20027): Top 5 write durations(microseconds): #1:28 #2:53 #3:57 #4:67 #5:119
D/MPEG4Writer(20027): reset()
D/MPEG4Writer(20027): Audio track stopping. Stop source
E/MPEG4Writer(20027): Stop() called but track is not started or stopped
I/hw-BpHwBinder(20027): onLastStrongRef automatically unlinking death recipients
I/flutter (20027): [RecordingService] updateRecordState() update _recordState from RecordState.record to RecordState.stop
I/flutter (20027): [ProfileCircleAvatar] No profile photo is set. (localProfilePhotoFilePath: "")
D/BufferPoolAccessor2.0(20027): bufferpool2 0x7f4e13500898 : 0(0 size) total buffers - 0(0 size) used buffers - 39/44 (recycle/alloc) - 5/80 (fetch/transfer)
D/BufferPoolAccessor2.0(20027): evictor expired: 1, evicted: 1

**Comment by llfbandit** [comment]
Thanks for the report. It should be fixed in record_android 1.0.3.
