### ISSUE TITLE
When "_recorderId" is the same, the file is overwritten only with the first path, even if the path is specified differently in Android OS

### ISSUE THREAD

**Issue by pkh31337** [llfbandit/record#228]
**Package version**
5.0.1 

**Describe the bug**
When "_recorderId" is the same (i.e., unless initialized by executing the constructor of the AudioRecorder class), the file is overwritten only with the first path even if the path is specified differently.

Please note that this bug does not exist in 4.x versions. So I'm currently using an older version. Nevertheless, I appreciate your management of such a valuable package.

**To Reproduce**
1. Specify the path as local to the device.
2. Execute the await start() and await stop() method asynchronously.
3. Check the device's local drive and listen to the saved recording file.
4. Change the path.
5. Execute the await start() and await stop() method asynchronously again without calling the constructor of the AudioRecorder class.
6. If you check the device's local drive, the file will be overwritten on the existing path, not the changed path.

**Expected behavior**
No error occurred.

**Smartphone**
 - Device: Pixel 7 Pro 
 - OS: Android 13.0
 - Version: API 33
(Only tested it on Android)

**Additional context**
If calling a new constructor of the AudioRecorder class every time you start and stop recording is not a bug but just a new version of the policy, it would be better to provide guidance to users. This is because the code worked without problems in the previous version.

**Comment by llfbandit** [comment]
Thanks for the report. It should be fixed in record_android 1.0.3.

**Comment by hioshih** [comment]
Having the same issue, after starting a new record on a different file it gets stuck on the file specified on the first recording.
