### ISSUE TITLE
macOs not start record

### ISSUE THREAD

**Issue by hatemragab** [llfbandit/record#229]
i have downloaded the example and run it on macOs 14.0 
and click to start record but nothing happens and no log appears!

**Comment by llfbandit** [comment]
Well...

**Comment by hatemragab** [comment]
i feel better now

**Comment by Abdelazeem777** [comment]
@llfbandit 
Well...

If don't know how to fix your issues, then why did you start an open source package from the beginning??

I can just say "I am sorry, but I don't know how to fix this issue or I don't have enough time to fix it"

How easy is that?? 😊

**Comment by amrahmed242** [comment]
> Well...

Maybe the AI took control of his machine and decided just "eh.. got no time for that I've bigger plans"

**Comment by llfbandit** [comment]
This is not a help center.
You're absolutely right, this is an open sourced project which implies contribution in a way or another.
Issue template is not respected and I'm tired of consumers.
I won't spend my time to dig for you.

So, finally, where's the issue?

Feel free to open a new one with correct info next time.
