### ISSUE TITLE
Record_web update broke pcm16bits audio streaming

### ISSUE THREAD

**Issue by lemonderon** [llfbandit/record#234]
**Package version**
record_web: 1.0.2

**Describe the bug**
Streaming with pcm16bits on web does not work on the latest record_web transitive dependency.
The issue occurs on at least multiple browsers: Chrome, Edge on Android/iOS/Windows/MacOS.

**To Reproduce**
1. Run flutter pub get with pubspec.lock removed.
2. Check that new transitive dependency is record_web of v1.0.2
3. Use audioRecorder.startStream to listen for new recorded data.

**Expected behavior**
The stream recording contains some data and does not close immediately.

**Additional context**
The audio stream recording feature on web has worked flawlessly until I have removed pubspec.lock and got a new transitive dependency record_web of v1.0.2. If I force the usage of record_web v1.0.0 inside pubspec.yaml then everything works as before.

**Comment by llfbandit** [comment]
Thanks for the report but I don't understand.
What do you mean by it does not work?

I just retested the sample on Edge & Firefox; I had no issue.

Do you have any log error from the console?
Can you check from the sample provided with the repository?

**Comment by lemonderon** [comment]
I've forgot to list my RecordConfig that was the culprit behind this issue on new record_web version:

Just checked the example project and found out that the stream recording does not work if `numChannels` is set to `1`. Whenever I remove this parameter for `RecordConfig` - the stream recording works perfectly on my side. 
        
        // Works perfectly
        const config = RecordConfig(encoder: encoder);
        // With numChannels set I am unable to get a stream to record anything
        const config = RecordConfig(encoder: encoder, numChannels: 1);
        

The screenshot of web console output in Edge for example project (when I have set numChannels parameter).       
![image](https://github.com/llfbandit/record/assets/45392009/ceeb1caa-b621-4f61-9e12-848b409caf32)

**Comment by llfbandit** [comment]
Fix available in record_web 1.0.3.
