### ISSUE TITLE
录音时更改了AudioSession的配置

### ISSUE THREAD

**Issue by ShiChenZhi** [llfbandit/record#237]
**Package version**
5.0.1

**Describe the bug**
音频播放器配置的默认Session：
final session = await AudioSession.instance;
await session.configure(AudioSessionConfiguration(
  avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
  avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.defaultToSpeaker | AVAudioSessionCategoryOptions.allowBluetooth,
  avAudioSessionMode: AVAudioSessionMode.spokenAudio,
  avAudioSessionRouteSharingPolicy: AVAudioSessionRouteSharingPolicy.defaultPolicy,
  androidAudioAttributes: const AndroidAudioAttributes(
    contentType: AndroidAudioContentType.music,
    flags: AndroidAudioFlags.none,
    usage: AndroidAudioUsage.media,
  ),
  androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
  androidWillPauseWhenDucked: true
));
使用该录音插件进行录音时，发现session变成了：
AudioSessionConfiguration(
  avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
  androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
);
导致原本音频是在设备外音播放，录音后再次播放音频，就变成了听筒播放

**Additional context**
我已经在停止录音的函数中重新设置了session：
  Future<void> stopRecord() async {
    _timer?.cancel();
    _isRecording = false;
    await _audioRecorder.stop();
    final session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration(
      avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
      avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.defaultToSpeaker | AVAudioSessionCategoryOptions.allowBluetooth
    ));
  }
这样更改可以解决上述的问题，但是我希望session可以作为一个配置项。因为设置session是耗时的，录音前和录音后的更改累计耗时300毫秒，这样导致用户体验比较差

**Comment by ShiChenZhi** [comment]
4.4.4版本没有这样的问题，更新到5.0.1版本就有这样的问题

**Comment by llfbandit** [comment]
Should be fixed in `record_darwin: ^1.0.1-beta.1`. You will need to add it manually to test it.

**Comment by ShiChenZhi** [comment]
> Should be fixed in `record_darwin: ^1.0.1-beta.1`. You will need to add it manually to test it.
抱歉，我没找到该插件，能否提供一个链接？我希望作者你可以在现有的record插件上进行修改，非常感谢~

**Comment by hewcheehau** [comment]
@ShiChenZhi  https://pub.dev/packages/record_darwin/versions/1.0.1-beta.1 。我相信開發者很快就會更新新的包了

**Comment by llfbandit** [comment]
Released in record_darwin 1.0.1
