### ISSUE TITLE
record_darwin 1.0.1-beta.1 source code

### ISSUE THREAD

**Issue by EvertonMJunior** [llfbandit/record#242]
Hi!

Sorry for not following the issue guidelines, but none fit this problem. I am working with record_darwin, version 1.0.1-beta.1, and would like to have access to its source code to understand somethings and problems I've been facing, even so to be able to bring more details here.

Could you direct me to where I could find it here on GitHub? I could only get it through pub.dev.

Thanks.

**Comment by hewcheehau** [comment]
@EvertonMJunior You should get the source code from your local pub: .pub-cache/hosted/pub.dev/record_darwin-1.0.1-beta.1

**Comment by EvertonMJunior** [comment]
Thanks @hewcheehau 
I already got it from there, problem is there's no way to contribute if the code is not here on GitHub 😬
@llfbandit any plans on this? I found a bug on iOS's initialization of the AV Audio Session, more specifically when setting the number of channels. Still working on getting to the bottom of it, but would like to contribute here.

**Comment by llfbandit** [comment]
The code was not published on github. This is now done on master.
