### ISSUE TITLE
Recording not working when I call the resume method on IOS

### ISSUE THREAD

**Issue by Enri-code** [llfbandit/record#244]
**Package version**
Version 5.0.1

**Environment**
 - OS: iOS

**Describe the bug**

Add your record configuration `RecordConfig(bitRate: 256000)` but falls back to 192000

**To Reproduce**

1. Call the pause function
2. Call the resume function afterwards
3. Call the stop function after you complete recording
4. No audio is recorded after the resume function is called

**Expected behavior**

**Additional context**

**Comment by llfbandit** [comment]
Released in record_darwin 1.0.1

**Comment by atoka93** [comment]
Hey @llfbandit, unfortunately I get this issue with `record_darwin 1.0.1` as well.
I use stop and start again to get around it.
