### ISSUE TITLE
[BUG] audioRecording not working on firefox

### ISSUE THREAD

**Issue by patrikheinonen** [llfbandit/record#246]
**Package version**

5.0.1

**Environment**
 - OS: macOS
 - Browser Firefox

**Describe the bug**

Recording audio fails

Error:
Uncaught (in promise) DOMException: AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.

Add your record configuration `RecordConfig(...)`

```
     RecordConfig(
            encoder: AudioEncoder.pcm16bits,
            device: _selectedAudioDevice,
            ),
      );
```

**To Reproduce**

1. try to record on flutter web on Firefox.

**Expected behavior**

I expect it to work on all browsers

**Additional context**

**Comment by llfbandit** [comment]
Thanks for the report.
Fixed in record_web 1.0.4.
