### ISSUE TITLE
Support of echo cancel , noise suppresion for iOS

### ISSUE THREAD

**Issue by niravp-cliqbux** [llfbandit/record#247]
I checked Readme file for echo cancel , noise suppresion, wanted to check is this going to available for iOS?

**Comment by llfbandit** [comment]
There's no plan for now. Maybe later next year if I find the way to (and time also...)

**Comment by Youngjun97** [comment]
Is there any updates on this? It seems like there is a merge request that was made a month ago. wondering when it is gonna be finalized

**Comment by llfbandit** [comment]
AGC & echo cancel are supported when streaming on latest version. When recording to a file, I don't know if there's support to prevent API to use them... Docs are very unclear...
