### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method create on channel com.llfbandit.record/messages)

### ISSUE THREAD

**Issue by 2426232528** [llfbandit/record#259]
**record: ^5.0.1**

**Environment**
 - OS: android
 - Flutter 3.16.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0366e0a3f (9 days ago) • 2023-12-05 19:46:39 -0800
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4

**Describe the bug**

Import record 5.0.1, After "flutter run", exceptions reported in an infinite loop in terminal  :

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel com.llfbandit.record/messages)
E/flutter (26097): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
E/flutter (26097): <asynchronous suspension>
E/flutter (26097): #1      AudioRecorder._create (package:record/src/record.dart:34:7)
E/flutter (26097): <asynchronous suspension>
E/flutter (26097): 

Then I clone this github project for the example and run it, the problem is the same. 

Could you help me how to fix this?

Thanks.

**Comment by ghzeni** [comment]
Having the same issue here.
