### ISSUE TITLE
[Question] Pass as string or File?

### ISSUE THREAD

**Issue by scheung38** [llfbandit/record#26]
Hi @llfbandit, the audio is located at:

file:///$HOME/Library/Developer/CoreSimulator/Devices/XXXXXXXX-XXXX-XXXX-XXXX-BE4E4FB87E55/
        data/Containers/Data/Application/
        XXXXXXXX-XXXX-XXXX-XXXX-9127A4823432/
        tmp/XXXXXXXX-XXXX-4BEC-B6BD-2FE9A15A9811.m4a
        
Should we pass it as a String or as File? If String then we use absolute or relative  path ? 

say 

```
  Future<void> uploadFilePath(String filePath) async {
  }
```
  
  or 
  
```
  Future<void> uploadFile(File filePath) async {
      File file = File(filePath);
  }
```
as I am getting

Unhandled Exception: 'package:firebase_storage/src/reference.dart': Failed
assertion: line 126 pos 12: 'file.absolute.existsSync()': is not true.

```
  Future<void> uploadFile(String filePath) async {
 
    File file = File(filePath);

   print("File inside uploadFile: " + filePath.toString());

////////////////////////////////////
//File inside uploadFile
file:///$HOME/Library/Developer/CoreSimulator/Devices/7705E1AF-FA63-4E6A-B3F2-BE4E4FB87E55/data/Containers/Data/Applic
ation/XXXXXXXX-XXXX-XXXX-XXXX-74B3B588FAA4/tmp/XXXXXXXX-XXXX-XXXX-XXXX-1D7571130760.m4a
////////////////////////////////////



    firebase_storage.SettableMetadata metadata =
        firebase_storage.SettableMetadata(
      cacheControl: 'max-age=60',
      contentType: 'audio/m4a',
      customMetadata: <String, String>{'file': 'audio'},
    );

    try {
      await firebase_storage.FirebaseStorage.instance
          .ref('file')
          .putFile(file, metadata);  <---- Unhandled Exception: 
          
    } on firebase_core.FirebaseException catch (e) {
      print("error: " + e.toString());
    }
  }
}
```

**Comment by bafplus** [comment]
This is partly what i need to....Im trying to email the resulting audio file yet i cant seem to get the variable to get the full path so my mailer can attach the audiofile.  Im trying to use this code, maybe you know how or what to put in place of "FULL_PATH_TO_AUDIOFILE"?

```
mailer() async {
    final smtpServer = SmtpServer("smtp.server.com",
        username: 'username',
        password: 'passwd',
        allowInsecure: true,
        ignoreBadCertificate: true);

    final datumOpmaak = DateFormat('dd-MM-yyyy H:mm');

    // Create our message.
    final message = Message()
      ..from = Address('fromadress@mail.nl', 'Me')
      ..recipients.add('recipient@gmail.com')
      ..subject =
          'Test Dart Mailer library :: ðŸ˜€ :: ${datumOpmaak.format(DateTime.now())}'
      ..text = 'This is the plain text.\nThis is line 2 of the text part.'
      ..attachments = [
        FileAttachment(File('FULL_PATH_TO_AUDIOFILE'))
          ..location = Location.inline
          ..cid = '<myimg@3.141>'
      ];

    try {
      final sendReport = await send(message, smtpServer);
      print('Message sent: ' + sendReport.toString());
    } on MailerException catch (e) {
      print('Message not sent.');
      for (var p in e.problems) {
        print('Problem: ${p.code}: ${p.msg}');
      }
    }
  }
// DONE
```

**Comment by scheung38** [comment]
Hi @bafplus 

I think this is the path:

file:///$HOME/Library/Developer/CoreSimulator/Devices/7705E1AF-FA63-4E6A-B3F2-BE4E4FB87E55/data/Containers/Data/Applic
ation/XXXXXXXX-XXXX-XXXX-XXXX-74B3B588FAA4/tmp/XXXXXXXX-XXXX-XXXX-XXXX-1D7571130760.m4a

but I cannot seem to upload this to Firebase Storage as outlined as it is saying:

'file.absolute.existsSync()': is not true

**Comment by bafplus** [comment]
Im quite the noob so pardon if i say something stupid or abvious :-)....But isnt that path different on both android and IOS and even per device? If i'm correct the recorder/player is using string, and we are (trying) to use file, maybe thats the issue?  So big questions remains...where and how does it store the audiofile and how to get said file to send to firebase (or mail in my case)?

**Comment by scheung38** [comment]
Hi @bafplus, just copy and paste your filepath found into browser, if it works then thats your audio.

**Comment by bafplus** [comment]
Thats my first problem...i havent found it yet :-)
And in browser? Does that also work in android (i think you are using web?)?

**Comment by scheung38** [comment]
Working on iOS side, but when we paste into browser we should get:

![Screenshot 2021-07-30 at 21 17 47](https://user-images.githubusercontent.com/1273014/127707360-041156e5-5aa0-433b-926f-026d7e592b67.png)

**Comment by bafplus** [comment]
Yes but what variable holds that path/url in the first place?
That path is not the same for all devices, so hardcoding will definatly not work. I'm very new to coding in the first place (but learning ;-)) so its very hard for me to pinpoint where and how that path is declared in the first place...

**Comment by llfbandit** [comment]
If you do not provide your own path, path is returned from stop method as uri string. You should try Uri.parse and toFilePath or File.fromUri if you need file handler.

**Comment by bafplus** [comment]
> If you do not provide your own path, path is returned from stop method as uri string. You should try Uri.parse and toFilePath or File.fromUri if you need file handler.

That sounds good...but could you help this noob with some code or example? (see my code above)

**Comment by scheung38** [comment]
@llfbandit why do we need to parse when we can pass the whole

file:/// into this:

```
Future<void> uploadFile(String filePath) async {
  File file = File(filePath);

  try {
    await firebase_storage.FirebaseStorage.instance
        .ref('uploads/file-to-upload.png')
        .putFile(file);
  } on firebase_core.FirebaseException catch (e) {
    // e.g, e.code == 'canceled'
  }
}
```

**Comment by bafplus** [comment]
Any luck yet @scheung38 ?

**Comment by amitkhairnar44** [comment]
@scheung38 The path which you get after recording is actually an `Uri`. If you want to upload the file then you can do something like this:

```dart
    File file = File.fromUri(Uri.parse(filePath));
```

**Comment by bafplus** [comment]
Great @amitkhairnar44 thanks! However....what is the exact code? Could you taka a look at my snippet in the second post?
I'm still very puzzled on what exactly should be placed in the "FULL_PATH_TO_AUDIOFILE" part. Would you be so kind to help me out?

**Comment by amitkhairnar44** [comment]
> Great @amitkhairnar44 thanks! However....what is the exact code? Could you taka a look at my snippet in the second post?
> I'm still very puzzled on what exactly should be placed in the "FULL_PATH_TO_AUDIOFILE" part. Would you be so kind to help me out?

You can use the same code as I have mentioned above.

```dart
FileAttachment(File.fromUri(Uri.parse(filePath)))
          ..location = Location.inline
          ..cid = '<myimg@3.141>'
```

`filePath` here would be the path received after recording.

**Comment by bafplus** [comment]
> ```dart
> File.fromUri(Uri.parse(filePath))
> ```

Thanks,

Yet i get this error: Undefined name 'filePath'.
If i change it to "Path" it says: The argument type 'Type' can't be assigned to the parameter type 'String'. 
If i then make it 'Path as String' i have no errors, but if i try to send it i get: 'Unhandled Exception: type '_Type' is not a subtype of type 'String' in type cast...'

**Comment by amitkhairnar44** [comment]
> > ```dart
> 
> > File.fromUri(Uri.parse(filePath))
> 
> > ```
> 
> 
> 
> Thanks,
> 
> 
> 
> Yet i get this error: Undefined name 'filePath'.
> 
> If i change it to "Path" it says: The argument type 'Type' can't be assigned to the parameter type 'String'. 
> 
> If i then make it 'Path as String' i have no errors, but if i try to send it i get: 'Unhandled Exception: type '_Type' is not a subtype of type 'String' in type cast...'

filePath should be the path of the file that you are trying to send.

**Comment by bafplus** [comment]
> > > 
> > 
> > 
> > > File.fromUri(Uri.parse(filePath))
> > 
> > 
> > > 
> > 
> > 
> > Thanks,
> > Yet i get this error: Undefined name 'filePath'.
> > If i change it to "Path" it says: The argument type 'Type' can't be assigned to the parameter type 'String'.
> > If i then make it 'Path as String' i have no errors, but if i try to send it i get: 'Unhandled Exception: type '_Type' is not a subtype of type 'String' in type cast...'
> 
> filePath should be the path of the file that you are trying to send.

And thats the problem...we dont know the actual path. It is generated upon recorder_start and put in a variable, yet i dont know what variable exactly or how to (re)call it.

**Comment by amitkhairnar44** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > File.fromUri(Uri.parse(filePath))
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > Thanks,
> 
> > > Yet i get this error: Undefined name 'filePath'.
> 
> > > If i change it to "Path" it says: The argument type 'Type' can't be assigned to the parameter type 'String'.
> 
> > > If i then make it 'Path as String' i have no errors, but if i try to send it i get: 'Unhandled Exception: type '_Type' is not a subtype of type 'String' in type cast...'
> 
> > 
> 
> > filePath should be the path of the file that you are trying to send.
> 
> 
> 
> And thats the problem...we dont know the actual path. It is generated upon recorder_start and put in a variable, yet i dont know what variable exactly or how to (re)call it.

You'll get the path upon stopping the recorder. 

Share the code snippet where you're stopping the recorder.

**Comment by bafplus** [comment]
I used the example: https://github.com/llfbandit/record/blob/master/record/example/lib/main.dart 

Here is my full main.dart: https://pastebin.com/XX42RjLd

Thanks allot for helping out!

**Comment by bafplus** [comment]
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > File.fromUri(Uri.parse(filePath))
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Thanks,
> > 
> > 
> > > > Yet i get this error: Undefined name 'filePath'.
> > 
> > 
> > > > If i change it to "Path" it says: The argument type 'Type' can't be assigned to the parameter type 'String'.
> > 
> > 
> > > > If i then make it 'Path as String' i have no errors, but if i try to send it i get: 'Unhandled Exception: type '_Type' is not a subtype of type 'String' in type cast...'
> > 
> > 
> > > 
> > 
> > 
> > > filePath should be the path of the file that you are trying to send.
> > 
> > 
> > And thats the problem...we dont know the actual path. It is generated upon recorder_start and put in a variable, yet i dont know what variable exactly or how to (re)call it.
> 
> You'll get the path upon stopping the recorder.
> 
> Share the code snippet where you're stopping the recorder.

I used the example: https://github.com/llfbandit/record/blob/master/record/example/lib/main.dart

Here is my full main.dart: https://pastebin.com/XX42RjLd

Thanks allot for helping out!

**Comment by bafplus** [comment]
@amitkhairnar44 I have tried different ways yet still without succes, help in any kind is much apriciated :-)

**Comment by amitkhairnar44** [comment]
@bafplus I have checked your code.
In your `_MyAppState` class you have this code:
```dart
AudioRecorder(
              onStop: (path) {
                setState(() {
                  audioSource = ap.AudioSource.uri(Uri.parse(path));
                  showPlayer = true;
                });
              },
            )
```

You are getting the path in this widget's callback `onStop`.

**Comment by bafplus** [comment]
> @bafplus I have checked your code.
> In your `_MyAppState` class you have this code:
> 
> ```dart
> AudioRecorder(
>               onStop: (path) {
>                 setState(() {
>                   audioSource = ap.AudioSource.uri(Uri.parse(path));
>                   showPlayer = true;
>                 });
>               },
>             )
> ```
> 
> You are getting the path in this widget's callback `onStop`. Assign that path to some variable and use it to upload the file.

Thanks, and that variable would be "audioSource"?

Again, pardon my noobness...im learning here :-)

**Comment by amitkhairnar44** [comment]
@bafplus Try this code: https://pastebin.com/nbbkSUk6

**Comment by bafplus** [comment]
> @bafplus Try this code: https://pastebin.com/nbbkSUk6

Almost :-)

The named parameter 'path' isn't defined. :236
All final variables must be initialized, but 'path' isn't. :268

**Comment by amitkhairnar44** [comment]
Add it to the constructor like this:
```dart
const AudioPlayer({
    required this.path,
    required this.source,
    required this.onDelete,
  });
```

**Comment by bafplus** [comment]
> Add it to the constructor like this:
> 
> ```dart
> const AudioPlayer({
>     required this.path,
>     required this.source,
>     required this.onDelete,
>   });
> ```

Thats it! many many thanks, you eurned yourself a beer! :-)

**Comment by bafplus** [comment]
> Add it to the constructor like this:
> 
> ```dart
> const AudioPlayer({
>     required this.path,
>     required this.source,
>     required this.onDelete,
>   });
> ```

This works on emulator but not on device (release.apk)....next stop: permissions :-)

**Comment by rvndsngwn** [comment]
> @scheung38 The path which you are getting after recording is actually an `Uri`. If you want to upload the file then you can do something like this:
> 
> ```dart
>     File file = File.fromUri(Uri.parse(filePath));
> ```

`Unhandled Exception: FileSystemException: Cannot open file, path = 'file:///private/var/mobile/Containers/Data/Application/02XXXXD-7XX3-4XXX-XXXX-3XXXXXXX3/tmp/9XXXXX-5295-XXX-XXXX-XXXX97E8EE2.m4a' (OS Error: No such file or directory, errno = 2) #0 _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9) #1 _rootRunUnary (dart:async/zone.dart:1362:47) #2 _CustomZone.runUnary (dart:async/zone.dart:1265:19) <asynchronous suspension>`

I'm getting this error and I just replace this line `  file = File(path);` to `  file = File.fromUri(Uri.parse(path));` and error solved. Thanks @scheung38
