### ISSUE TITLE
Mic Icon not properly disappearing when audioRecord checks for permission from browser

### ISSUE THREAD

**Issue by austinlee1993** [llfbandit/record#260]
**Package version**
5.0.1

**Environment**
 - OS: Mac
 - Browser: Chrome, Safari

**Describe the bug**
When I add the check for permission (from the browser) before I start recording, the browser still says I'm using the mic icon even when I'm done recording, using the microphone. When I remove the check for permission, the browser correctly releases the mic, hence I believe the issue is with the checking for permission

Config I use for Chrome: const RecordConfig(encoder: AudioEncoder.opus)

**To Reproduce**
Code I use in the demo (video attached) - this functions fire when I press record

Code Snippet: https://goonlinetools.com/snapshot/code/#yi5r5r19xzlc609ctycjh5

Video: https://github.com/llfbandit/record/assets/8631395/5d03d875-5fa8-4d6b-b0b9-162cb5ec79ca

**Expected behavior**

The mic should disappear from the browser when the recording is done

**Additional context**

**Comment by llfbandit** [comment]
Thanks for the report.
Fixed in record_web 1.0.4.

**Comment by austinlee1993** [comment]
@llfbandit appreciate the quick response! Can you show me the implementation of a recorder instance in recorder_web? It seems in the repo it says go to the "main record package" but the web directory in the example directory just has html instead of dart code

**Comment by llfbandit** [comment]
record_web is a transitive dependency you get from record. Just upgrade your own pubspec.

**Comment by austinlee1993** [comment]
@llfbandit - looks like its working well on my end after a few flutter cleans/remove and reinstalling! 
It does however, seem to load a bit slow for the recording function to initialize on Safari (I'm using a default const RecordConfig() in the start method instead of  RecordConfig(encoder: AudioEncoder.opus) for Chrome) - but the mic issue now disappears when I stop recording -- thanks!
