### ISSUE TITLE
uploading audio web by MultipartFile

### ISSUE THREAD

**Issue by tas-unn** [llfbandit/record#262]
**Package version**
5.0.2

**Environment**
Windows 10 Pro

**Describe the bug**

how to upload a file via dio that was recorded via web?

const encoder = AudioEncoder.wav;
const config = RecordConfig(encoder: encoder);

**To Reproduce**

1) took an example from the site
2) Changed the config
3) Added dio package
4) Commented out the write to the file, uncommented the write to the stream
5) In the audio_recorder_web.dart file, in the recordStream function, I replaced part of the code:

    stream.listen(
      (data) => b.add(data),
      onDone: () async {
        var formData=FormData();
          formData.files.add(MapEntry(
              "message_bytes",
              MultipartFile.fromBytes(
                  b[0])));
        var response = await Dio().post(
          "https://my.site/sendtest.php",
          data: formData,
        );
        //downloadWebData(html.Url.createObjectUrl(html.Blob(b)));
        },
    );

6) The sent data contains some bytes (the array is not empty), but the file is broken

**Expected behavior**

successful file upload

**Additional context**

-

**Comment by llfbandit** [comment]
You only pick the first chunk of data. This is why you can't read it.
Also, you can't stream with wav format. This an error and shouldn't be allowed, this will be fixed in a next release.
Please read the README.md for available features.

**Comment by tas-unn** [comment]
the error remains(((.
Updated to 5.0.3, changed the codec.
List<Uint8List>? mybytes;
mybytes= await recordStream(_audioRecorder, config);
and sent this array through dio. I only hear crackling noises in the file.
And also - what format should this file have?
