### ISSUE TITLE
PlatformException(record, The operation couldn’t be completed. (OSStatus error 1718449215.), null, null)

### ISSUE THREAD

**Issue by asadbekdev** [llfbandit/record#272]
**record: 5.0.4**

**Environment**
 - OS: MacOS

**When i use await _recorder.start(const RecordConfig(), path: _path!); function, it's not working and showing error.**

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(record, The operation couldn’t be completed. (OSStatus error 1718449215.), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
<asynchronous suspension>
#2      AudioRecorder.start (package:record/src/record.dart:53:5)
<asynchronous suspension>

**Comment by starscreamnik** [comment]
I catch the same error, when use .wav on iOS, show please your full path and platform?

**Comment by asadbekdev** [comment]
After I changed the file mime-type to .m4a from wav, everything started working
