### ISSUE TITLE
Expose AVAudioSession interface

### ISSUE THREAD

**Issue by ajsharp** [llfbandit/record#279]
**Is your feature request related to a problem? Please describe.**
I need access to the `AVAudioSession` swift class. This is useful and necessary sometimes, such as when connected to a car bluetooth device to "end the call" that cars will "start" when you are using the mic when in the car.

**Describe the solution you'd like**
Make a method available that allows setting the `AVAudioSession` category.

**Comment by llfbandit** [comment]
This package won't expose this.
What can be done is to restore the previous category before the recording.

**Comment by mynlexi** [comment]
This is also quite a big painpoint for our project

**Comment by bbjay** [comment]
There is a new option `IosRecordConfig.manageAudioSession` (in master, but not yet released) which you can set to false and then use the [audio_session](https://pub.dev/packages/audio_session) plugin to manage the AVAudioSession all by yourself.

**Comment by llfbandit** [comment]
manageAudioSession & category options ref: d25e64ca67f269ce732af86b617be89e2b358ef7 8485404cc397786f8ea71cc1982bc1ebfead7e28
