### ISSUE TITLE
Recording [0,0,0,0,0,...] on iOS Simulator

### ISSUE THREAD

**Issue by jtdLab** [llfbandit/record#281]
**Package version**  5.0.4

**Environment**
 - iOS Simulator (tested on 15.5, 17.2)

**Describe the bug**

Recording audio (with permission granted) using:

```dart
 final audioStream = await _record.startStream(
        const RecordConfig(
          encoder: AudioEncoder.pcm16bits,
          sampleRate: kSampleRate,
          numChannels: 1,
        ),
      );
```
leads to [0,0,0,0,...] lists being emitted by the audio stream.

**Comment by llfbandit** [comment]
I guess this is working on a real device?

**Comment by jtdLab** [comment]
Is the package not intended to support simulator as stated in darwin package?

**Comment by llfbandit** [comment]
Changes where made for file recording only.
