### ISSUE TITLE
 record.cancel() method isn't available

### ISSUE THREAD

**Issue by asadbekdev** [llfbandit/record#282]
Package version
record: ^5.0.4

**Comment by llfbandit** [comment]
On which platform?
Please, also fill the log.

**Comment by asadbekdev** [comment]
> On which platform? Please, also fill the log.
.cancel method isn't just available.

<img width="1058" alt="image" src="https://github.com/llfbandit/record/assets/67022917/2b991661-170e-47e4-a660-ce93173fb0e9">

**Comment by asadbekdev** [comment]
@llfbandit Why I can't call .cancel() method? 👀

**Comment by asadbekdev** [comment]
@llfbandit 👀 Can you help me?

**Comment by llfbandit** [comment]
Closed by 57fc9912

**Comment by asadbekdev** [comment]
When will you publish it to pub.dev?  
I tried using it from github, but I couldn't.  It'd be cool if you submit a new version. It's really urgent for me. 😅
