### ISSUE TITLE
In browser, is that only use stream ? beacuse i can't create file on web.

### ISSUE THREAD

**Issue by li-xiaojun** [llfbandit/record#283]

**Comment by mellowcello77** [comment]
This question might not be clear,  but valid. Using the location of a file in Flutter web is extremely hard to find a documented solution for.

**Comment by llfbandit** [comment]
Really? Here's the `start` method documentation.
https://github.com/llfbandit/record/blob/d289492ca18e623c8b0ba3ffe799be81b0c04266/record/lib/src/record.dart#L41-L47

You can't use files on web platform, only blobs. This is why `stop` method returns the path of the audio recorded.
The browser generates an internal URL to access the blob.
You can use `cross_file` package to deal with blobs/files for cross platform.

**Comment by AliKarimiENT** [comment]
Hi there,
Are you saying that we just need to pass the provided URL from the stop function to the cross-file loading method?

**Comment by llfbandit** [comment]
Yes.
