### ISSUE TITLE
Doesn't see Sampling frequency change when analyze with MKVToolNix

### ISSUE THREAD

**Issue by Malyasse** [llfbandit/record#287]
**Package Version**
5.0.4

**Environment**
 - OS: [e.g. iOS/Windows/...]
 - Browser [e.g. Chrome, Safari]
 - Version 121.0.6167.185 (Official Build) (64 bits)

**Bug Description**
I initiate this with:
```dart
await _audioRecorder.start(RecordConfig(
            bitRate: 1152000,///128000
            encoder: AudioEncoder.opus,
            numChannels: 1,
            sampleRate: 41000,
        ), path: '');
```
I modify the sampling rate and bit rate, but the changes are not reflected in the Matroska format fields:
0xb5 (sampling frequency) = 48000
0x6265 (bit depth) = 32 bits

**Configuration: bitRate 128000, sampleRate 44100**
![image](https://github.com/llfbandit/record/assets/32846698/6bf70257-4dbc-46e5-8814-6d8430d2cec2)
Here, it's observed that what's displayed doesn't align, and we're at position 16667 to reach 1.02 seconds.

16386 if we keep only the pure size data
17368 if we include the last

**Configuration: bitRate 128000, sampleRate 48000**
![image](https://github.com/llfbandit/record/assets/32846698/9876f23c-bccf-4014-83fb-7c51c81e652c)
The issue here is that we need exactly the same number of hexadecimals to reach 1.02 seconds, which is 16667.
Same as for the previous test: 16386 if we keep only the pure size data, 17368 if we include the last.

Shouldn't these be different? Or is it just the bitRate that is considered? It's not clear.

44100 Hz or 44100 measurements per second equate to one measurement every 0.023 ms.
48000 Hz or 48000 measurements per second equate to one measurement every 0.021 ms.

If the number of samples per second is supposed to be different, why do we seemingly have the same thing? And why 16667 (I don't understand this)?

**Test by changing only the bitRate**

**BitRate:11523000, SamplingRate: 44100**
![image](https://github.com/llfbandit/record/assets/32846698/fb7b7830-fc87-4530-8402-24537d32b31b)

**BitRate:11523000, SamplingRate: 48000**
![image](https://github.com/llfbandit/record/assets/32846698/5b30edbc-0c9e-4a1b-8c21-a868fd8a23fd)

In both cases, the sampling rate isn't updated, but we have different positions for 00:00:01.02 seconds.

**Expected Behavior**

-Change the sample rate and test the output content in the container
-Simply request Sample Rate and Bit Depth to determine our Bit Rate. (Bit Rate = Sample Rate * Bit Depth)
-Or add the explanation when we hover over the constructor that we choose only one parameter (sampleRate or bitRate) and that there is a bit depth chosen which does not change

**Additional Context**

I'm attempting to figure out how many hexadecimals correspond to 1 sample.
I'm not entirely sure I comprehend how the relationships work to determine how many hexadecimals correspond to 1 sample.

I'm not 100% sure about what I mentioned above in terms of relationships; that's what I understood.If I really didn't understand I would be happy if my errors were clarified :)

But if someone would like to explain to me—especially how we find out how many hexadecimals make 1 sample (so, 0.020 ms in the context of 48000 and 32-bit depth)—what I don't understand is that "32-bit" is supposed to represent a sample of 0.020 ms, but 4 bits = 1 Hexa. So, you need 8 hexadecimal digits to have a sample. But here, there is much less (a position is a couple of two-digit Hexa (4F, E7...), with 16386 of data it gives 32772 hexadecimals for one second).
48000 samples/s * 32 bits = 1536000 Bit Rate
1536000/4 bits = 384,000 hexa/s
384,000/2 (because we have a couple of hexa in position) = 192,000 positions to have 1 second.

BUT (I just realized) if we have just 128000 Bit Rate:
128000/4 = 32000 hexadecimal
32000/2 = 16000 positions (which is therefore consistent with the 16386 before)

But, what is the use of the sampling frequency and bit depth? 8000Hz and 16bits/s ? I really don't understand anything at this point. ^^'

**Comment by llfbandit** [comment]
Browsers take OS parameters for compressed recording.
This only works for pcm and wave at this moment.
