### ISSUE TITLE
Playback slider is glitchy

### ISSUE THREAD

**Issue by iosephmagno** [llfbandit/record#29]
I discovered a bug related to playback slider. If you move it while it is playing, it gets glitchy and you cannot really use it.

I attach a video where I use official demo.
Any help with this would be much appreciated!

https://user-images.githubusercontent.com/83366073/133576927-6ad49c77-b01f-483d-8944-4837e6af54cd.mov

**Comment by llfbandit** [comment]
This is unrelated to the package.
