### ISSUE TITLE
Darwin installation

### ISSUE THREAD

**Issue by Solido** [llfbandit/record#291]
**latest**

**Environment**
 - OS: macos latest
 - cocoapods-1.15.2
 - flutter master

**Describe the bug**

```
[!] CocoaPods could not find compatible versions for pod "record_darwin":
  In Podfile:
    record_darwin (from `Flutter/ephemeral/.symlinks/plugins/record_darwin/macos`)

Specs satisfying the `record_darwin (from `Flutter/ephemeral/.symlinks/plugins/record_darwin/macos`)` dependency were found, but they required a higher minimum deployment target.
```

**To Reproduce**
pod install

My configuration target macos 11 but even trying different version fail.
I checked your pod spec that also target 11.

Maybe I missed something...

**Comment by llfbandit** [comment]
This package requires macos version 10.15.
Ensure that your podfile also set this minimum value. Take a look at the example if needed.

**Comment by Solido** [comment]
You nailed it, it forgot the podfile header! 
Thank you for this package!
