### ISSUE TITLE
define AudioRecorder in initstate without arguments

### ISSUE THREAD

**Issue by pishguy** [llfbandit/record#293]
how can i define AudioRecorder() without any arguments in `initState` like with the sample code?

<img width="920" alt="Screenshot 2024-03-07 at 10 31 00 AM" src="https://github.com/llfbandit/record/assets/6617583/ca5bc2bd-ba19-4c98-a3b3-c9b16d34d761">

implemented sample code:

https://github.com/llfbandit/record/blob/8e06a9e7f4a9241dedf7b56c47f049c27009bc18/record/example/lib/audio_recorder.dart#L29

**Comment by llfbandit** [comment]
I guess you're not in version 5.x.x.
