### ISSUE TITLE
iOS AudioEncoder.wav Not supported

### ISSUE THREAD

**Issue by xhzth70911** [llfbandit/record#302]
**Package version**
record: ^5.0.4

**Environment**
 - OS: iOS 13.3.1，iPhone 6 plus
**Describe the bug**

Add your record configuration `RecordConfig(...)`
const RecordConfig(
                  encoder: AudioEncoder.wav,
                ),
**To Reproduce**

**Expected behavior**

**Additional context**

AudioEncoder.aacLc normal，AudioEncoder.wav Error

await record.start(
                const RecordConfig(
                  encoder: AudioEncoder.wav,
                ),
                path: "${PathHelper().getCachePath}/${123}.m4a",
              );

Error reporting：
flutter：
![ea8670238b9dc54ff106178750b0c55e](https://github.com/llfbandit/record/assets/24982706/75a76b17-d595-4391-b00a-a64ad3209e63)
![093a7a9235e75432b93cf6f10570a593](https://github.com/llfbandit/record/assets/24982706/8d4e9e16-fe99-4699-a455-d6d1d60d81be)
![e8b023616f113d37562e6f1b20a7ac95](https://github.com/llfbandit/record/assets/24982706/42e1f2f2-776e-4bcc-9856-55d689f4c9fb)

xcode：
Unhandled Exception: PlatformException(record, The operation couldn’t be completed. (OSStatus error 1718449215.), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      AudioRecorder.start (package:record/src/record.dart:53:5)
<asynchronous suspension>
#3      _VoiceRecordState.build.<anonymous closure> (package:askaide/page/component/chat/voice_record.dart:119:15)
<asynchronous suspension>

**Comment by nitinrgadhiya** [comment]
@xhzth70911 did you find any alternative solution?
