### ISSUE TITLE
Error while trying to record

### ISSUE THREAD

**Issue by iamasher0** [llfbandit/record#307]
**Package version**
record: ^5.0.5

**Environment**
 - Android 7

**Describe the bug**
I get an error when I try to start record to a file

E/AudioRecorder(15204): No encoder found for {aac-profile=2, bitrate=128000, mime=audio/mp4a-latm, channel-count=2, sample-rate=44100}
E/AudioRecorder(15204): java.lang.Exception: No encoder found for {aac-profile=2, bitrate=128000, mime=audio/mp4a-latm, channel-count=2, sample-rate=44100}
E/AudioRecorder(15204): 	at com.llfbandit.record.record.encoder.MediaCodecEncoder.createCodec(MediaCodecEncoder.kt:70)
E/AudioRecorder(15204): 	at com.llfbandit.record.record.encoder.MediaCodecEncoder.<init>(MediaCodecEncoder.kt:17)
E/AudioRecorder(15204): 	at com.llfbandit.record.record.format.Format.getEncoder(Format.kt:42)
E/AudioRecorder(15204): 	at com.llfbandit.record.record.RecordThread.run(RecordThread.kt:110)
I/HwAudioRecordImpl(15204): sendStateChangedIntent, state=1

Record configuration: RecordConfig(encoder: AudioEncoder.aacLc)

**To Reproduce**

1. Run this function when the user presses the record button:
```dart
Future<void> startRecording() async {
    try {
      if (await audioRecorder.hasPermission()) {
        await audioRecorder.start(const RecordConfig(encoder: AudioEncoder.aacLc),
            path: '${appDirectory.path}/myFile.m4a');
      }
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
    }
  }
```
2. See error

**Comment by llfbandit** [comment]
Try with a single channel for example.
