### ISSUE TITLE
IOS 17.4.1 Recording False

### ISSUE THREAD

**Issue by liugong86** [llfbandit/record#309]
record 5.0.5 

**Environment**
 - OS: IOS 17.4.1
 - flutter 3.19.4
 - iphone 15

**Describe the bug**
record can start, and there has no any error. but the audio file length only 28. Amplitude always the same value
AudioPlayer the audio file also false;

The same code on android work well.

const config = RecordConfig(
            encoder: encoder,
            numChannels: 1,
            sampleRate: 8000,
            bitRate: 64 * 1024);

can somebody help me?

**Comment by liugong86** [comment]
> record 5.0.5
> 
> **Environment**
> 
>     * OS: IOS 17.4.1
> 
>     * flutter 3.19.4
> 
>     * iphone 15
> 
> 
> **Describe the bug** record can start, and there has no any error. but the audio file length only 28. Amplitude always the same value AudioPlayer the audio file also false;
> 
> The same code on android work well.
> 
> const config = RecordConfig( encoder: encoder, numChannels: 1, sampleRate: 8000, bitRate: 64 * 1024);
> 
> can somebody help me?

when delete the params sampleRate:8000, it work well.
const config = RecordConfig(
encoder: encoder,
numChannels: 1,
// sampleRate: 8000,
bitRate: 64 * 1024);

**Comment by llfbandit** [comment]
If I remember well, iOS doesn't record below 16k...
