### ISSUE TITLE
Migrate to package:web

### ISSUE THREAD

**Issue by Fraa-124** [llfbandit/record#311]
Flutter web apps are required to migrate from dart:html to package:web to use WASM.

See https://docs.flutter.dev/platform-integration/web/wasm and https://pub.dev/packages/web for more information.

**Comment by FeodorFitsner** [comment]
`recorder.dart` still uses `dart:html`:https://github.com/llfbandit/record/blob/8dd7a075fccaec8e1e390ef29eb7a54f99410149/record_web/lib/recorder/recorder.dart

**Comment by FeodorFitsner** [comment]
All occurrences of `dart:html`: https://github.com/search?q=repo%3Allfbandit%2Frecord%20dart%3Ahtml&type=code
