### ISSUE TITLE
App crashes on Android 10

### ISSUE THREAD

**Issue by Somtobro** [llfbandit/record#312]
**5.0.5**

**Environment**
 - OS: Windows
 

**Describe the bug**
I'm using the example project.
Immediately I click the record button on any Android 10 project the app crashes. Also I have put all necessary permissions I even tried storage permission.

Add your record configuration `RecordConfig(...)`// check example project for more
channels:1
aacLc

**To Reproduce**

1. Go to example project
2. Clone it and build for Android 10

**Comment by llfbandit** [comment]
Log and stacktrace could help.

**Comment by llfbandit** [comment]
Version 5.1.1 has been released to fix this.
Feedback welcomed!
