### ISSUE TITLE
Set AVSession.Mode to "measurement" on iOS

### ISSUE THREAD

**Issue by akreal** [llfbandit/record#315]
**Is your feature request related to a problem? Please describe.**

I'd like to set AVSession.Mode to "measurement" on iOS to disable  pre-processing like echo cancellation and noise suppression (it seems to remove background music that I'd like to record).

**Describe the solution you'd like**

Would you accept such code change at all?

What configuration parameter should be used for this?
 - new parameter `mode` with additional possible values for iOS modes;
 - existing parameter `autoGain`: which it's false, set the mode to "measurement" on iOS.

**Describe alternatives you've considered**

None

**Additional context**

https://stackoverflow.com/questions/58472683/cancel-ios-microphone-echo-cancellation-and-noise-suppression
https://developer.apple.com/documentation/avfaudio/avaudiosession/mode/1616608-measurement

**Comment by akreal** [comment]
Never mind, this actually did not help me. I'm looking for other options to disable the denoising.

**Comment by llfbandit** [comment]
So I'm closing this since this is irrelevant.
