### ISSUE TITLE
Pause and resume on Chrome are giving only half of the audio data

### ISSUE THREAD

**Issue by jemisgoti** [llfbandit/record#316]
**Package version**
5.1.0

**Environment**
 - OS: [Web (android, ios and macos)]
 - Browser [e.g. chrome, edge]

I am using a recording package to record audio files. I have pause and resume functionality. On Safari, I am getting the complete audio when the user pauses and resumes recording after a few seconds. On Chromium-based browsers, it only provides the audio data that is recorded before pausing.

My record config is 
`        RecordConfig(
          sampleRate: sampleRate,
          encoder: AudioEncoder.wav,
          bitRate: bitRate,
          numChannels: 1,
        ),`

 

**Expected behavior**

It should give the full audio containing data from both before and after pausing.

**Additional context**

My web app also uses https://github.com/pkjy/pcm-player/blob/master/src/pcm-player.js to play the audio data, which depends on the AudioContext. However, it is working fine, and I am encountering this issue only in Chromium-based browsers.

**Comment by llfbandit** [comment]
Thanks for the report!
I reproduced it with Edge from ~15 seconds in pause state. Somehow, it feels that the audio worklet is disconnected. No error, audio worklet is still here but never called again...

Notice, you must use record_web > 1.1.0 to get the fix that will land soon.
