### ISSUE TITLE
SWIFT_VERSION attribute error on iOS

### ISSUE THREAD

**Issue by jt274** [llfbandit/record#319]
**Package version**
`5.1.0`

**Environment**
 - OS: `iOS`

**Describe the bug**

When running `pod install` in the project, the following error is given:
```
- `record_darwin` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrates this pod.
```

As a result, `pod install` fails and the app will not build.

Seems like something that should be set within the plugin?

**Comment by llfbandit** [comment]
Is cocoapod is up to date?
I use myself version 1.15.2.
Searching on web gives me old answers on this error.

**Comment by llfbandit** [comment]
I'll check again. I just upgraded XCode to latest version. As you reference swift 5.10 I guess you're on latest too. So maybe...

**Comment by llfbandit** [comment]
Checked again on two different projects. No issue on my side.
Can you check with a new project or the example project?

**Comment by llfbandit** [comment]
Fixed with https://github.com/llfbandit/record/commit/8e86c76af34f68de147174b37aec7f88bd04b9ce
