### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by quseappdeveloper** [llfbandit/record#32]
Record is not working in iOS but same is working fine in Android. Permissions has been added. Audio Encoder used is AAC and bitrate, samplingrate are default values. Anyone encountered issue with iOS?

**Comment by shalikhshab00** [comment]
Did you come across any situation where it throws this error : 

PlatformException(, Failed to start recording, null, null)

**Comment by bhargav6744** [comment]
@quseappdeveloper can you please post how you managed with file path.
