### ISSUE TITLE
Record 5 . . .  does not allow to build for Android

### ISSUE THREAD

**Issue by Hopheylalal** [llfbandit/record#329]
varsion 4.4.4 working fine

Flutter Fix 
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                                                                        │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update /Users/ivanov/StudioProjects/untitled/android/build.gradle: │
│ ext.kotlin_version = '<latest-version>'   

Settings.gradle:

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "2.0.0" apply false
}

**Comment by llfbandit** [comment]
I'm not sure `org.jetbrains.kotlin.android 2.0.0` is supported for now. Anyway, I discourage you to use it, as it is too new...

Here's the latest versions of the plugins.
```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.4.1" apply false
    id "org.jetbrains.kotlin.android" version "1.9.24" apply false
}
```

Be sure to use an updated version of gradle itself from `gradle-wrapper.properties`
`distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip`

**Comment by hatemragab** [comment]
Same problem here happens after upgrade to flutter 3.22 and with last verion of the package which is `record: ^5.1.1` 
![image](https://github.com/llfbandit/record/assets/37384769/ffef10be-ebf8-47eb-a602-e5dcacf6d3f1)

**Comment by EMUNES** [comment]
I have this problem, too. Version 5.1.1 and Flutter 3.22.1 for Android platform.

**Comment by sidhu-patil** [comment]
Follow below step to fix these problems:

step 1: 
add jvmTarget to 1.8 & ndkVersion  26.1 in android/app/build.gradle
```dart  
android {
    compileSdk = flutter.compileSdkVersion
    ndkVersion = "26.1.10909125"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

}
```

step 2: update android/settings.gradle

```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.4.1" apply false
    id "org.jetbrains.kotlin.android" version "1.9.24" apply false
}
```

step 3: update android/gradle/wrapper/gradle-wrapper.properties 

```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip
```

**Comment by hatemragab** [comment]
> To fix these issues, follow the steps below:
> 
> Step 1: Update android/app/build.gradle
> 
> 1. Add jvmTarget
> 2. Set ndkVersion to 26.1 (optional):
> 
> ```groovy-gradle
> android {
>     compileSdk = flutter.compileSdkVersion
>     ndkVersion = "26.1.10909125"
> 
>     compileOptions {
>         sourceCompatibility = JavaVersion.VERSION_1_8
>         targetCompatibility = JavaVersion.VERSION_1_8
>     }
> 
>     kotlinOptions {
>         jvmTarget = '1.8'
>     }
> }
> ```
> 
> Step 2: Update android/settings.gradle
> 
> Update the Kotlin plugin and the Android Gradle Plugin (AGP) versions:
> 
> ```groovy-gradle
> plugins {
>     id "dev.flutter.flutter-plugin-loader" version "1.0.0"
>     id "com.android.application" version "8.4.1" apply false
>     id "org.jetbrains.kotlin.android" version "1.9.24" apply false
> }
> ```
> 
> Step 3: Update android/gradle/wrapper/gradle-wrapper.properties
> 
> Set the distributionUrl to use Gradle 8.6:
> 
> ```groovy-gradle
> distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip
> ```
> 
> Following these steps will resolve the issues.

Thanks it works now

**Comment by llfbandit** [comment]
Have a look to updated readme.md.
