### ISSUE TITLE
As a Flutter SDK package, the versions of its sub-SDKs should be fixed

### ISSUE THREAD

**Issue by GordonWu** [llfbandit/record#330]
I am using version 5.1.0, but suddenly, in the middle of development, I needed to use flutter clean and flutter pub get due to using another SDK. As a result, I encountered an issue where the Android min SDK version had to be 23 to compile. 

Previously, everything built fine until I noticed the error message mentioned the record_android keyword. 
I realized that version 5.1.1 had been released and it updated the record_android min SDK from 21 to 23. However, because version 5.1.0 only locks the major version number, it caused the update. 

I hope that future releases can have fixed sub-SDK version numbers to avoid inconvenience for external developers.

**Comment by llfbandit** [comment]
I understand your point of view but it will be always this way.
To fix issues on `record_android 1.2.1` I had to raise the minimum Android SDK.

Also, you can pin yourself dependencies in your project, stick to lower bounds when using `pub upgrade` and don't upgrade Flutter in the "middle of development"...

Finally, raising minimum Android SDK is far from a common task. Last time was about a year.
