### ISSUE TITLE
[BUG - Android] Cannot select mic in Android

### ISSUE THREAD

**Issue by Sp4Rx** [llfbandit/record#331]
**Package version**
  `record: ^5.1.1`

**Environment**
 - OS: Andorid

**Describe the bug**

Facing the same issue like #296  for Android also, if I have BT headset it's picking up the BT mic irrespective of device selection.
Sample code:
```
await record?.start(
  RecordConfig(encoder: AudioEncoder.wav, device: _selectedMic),
  path: vocalPath!,
);
```

I am also doing `_micList = await record?.listInputDevices();` from which I'm selecting the mic

Also I have another query. While recording is it possible to cancel out phones internal sounds like a music is playing or notification sounds.
@llfbandit

**Comment by llfbandit** [comment]
Did you set `MODIFY_AUDIO_SETTINGS` in your manifest?
There may be an issue in this area.

For internal sounds, yes, check `RecordConfig#androidConfig`.

**Comment by Sp4Rx** [comment]
Hey @llfbandit sorry for the delayed response.
Yes I have added the permission in the manifest as mentioned in the readme

```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<!-- Bluetooth telephony device like headset/earbuds (min SDK: 23) -->
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<!-- Optional: Add this permission if you want to save your recordings in public folders -->
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
And what should I look into this  `RecordConfig#androidConfig` ?
You meant this class right? 
https://github.com/llfbandit/record/blob/0bc1bbefaa9813d891e7ef5c0a81918acd4cf896/record_android/android/src/main/kotlin/com/llfbandit/record/record/RecordConfig.kt#L5-L19
