### ISSUE TITLE
Execution failed for task ':app:mergeLibDexDebug'. [record_android]

### ISSUE THREAD

**Issue by devbathani** [llfbandit/record#335]
* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform classes.jar (project :record_android) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.3.0, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.jvm.environment=android, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/devbathani/Desktop/Work/tambez_app/build/record_android/intermediates/runtime_library_classes_jar/debug/classes.jar.
         > Error while dexing.

**Comment by An5675** [comment]
Same problem

**Comment by Schefferbird** [comment]
I also get this

**Comment by itsPedro231** [comment]
I am having the same issue, and changing to a previous version did not work.
