### ISSUE TITLE
Build error: Execution failed for task ':app:mergeLibDexDebug'.

### ISSUE THREAD

**Issue by MRtootisabz** [llfbandit/record#338]
**Package version**

**Environment**
 - Flutter version: 3.22.0
 - Dart: 3.4.0
 - Android studio Jellyfish Patch 1
 - emulator API 30 android version 11
 - Windows 11 

**Describe the bug**

when running flutter project during build this error comes:
project\build\record_android\intermediates\runtime_library_classes_dir\debug\com\llfbandit\record\record\format\Format.class: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform debug (project :record_android) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.3.0, com.android.build.api.attributes.BuildT
ypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.jvm.environment=android, org.gradle.libraryelements=classes, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\info\Documents\GitHub\Tooti\build\record_android\intermediates\runtime_library_classes_dir\debug.
         > Error while dexing.

1. record flutter package 5.1.1 or 5.0.1

**Expected behavior**

flutter run fails during build

**Comment by llfbandit** [comment]
Duplicate #333
