### ISSUE TITLE
Flutter 3.22 - Android Build Issue

### ISSUE THREAD

**Issue by hrantotheden** [llfbandit/record#344]
**Package version**
5.1.1

**Environment**
 - OS: Android

**Describe the bug**
Unable to build on Android.

`Execution failed for task ':app:mergeLibDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform classes.jar (project :record_android) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, com.android.build.api.attributes.AgpVersionAttr=7.3.0, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.jvm.environment=android, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingNoClasspathTransform: /xxxxx/xxxx/.gradle/caches/8.8/transforms/2dfbd639791235749302364502298ee9/transformed/classes.jar.
         > Error while dexing.
`

**To Reproduce**

1. flutter build android

**Expected behavior**

App Builds

**Comment by llfbandit** [comment]
Duplicates #335
