### ISSUE TITLE
How to disable Logs BufferPoolAccessor

### ISSUE THREAD

**Issue by dkliss** [llfbandit/record#346]
Package: record: ^5.1.1

Android Emulator. 

**Details:**

I have recently tested this package. I have one issue. Even after disposing recorder, I am getting below logs specifically on Android emulator ONLY (VS code). How to disable these when using this package on android?  

D/BufferPoolAccessor2.0(29794): bufferpool2 0xec37eb28 : 7(14336 size) total buffers - 4(8192 size) used buffers - 30722/30755 (recycle/alloc) - 101/61501 (fetch/transfer)
D/BufferPoolAccessor2.0(29794): bufferpool2 0xcddb8b88 : 7(14336 size) total buffers - 4(8192 size) used buffers - 31317/31355 (recycle/alloc) - 118/62701 (fetch/transfer)
D/BufferPoolAccessor2.0(29794): bufferpool2 0xec37eb28 : 7(14336 size) total buffers - 4(8192 size) used buffers - 30992/31025 (recycle/alloc) - 101/62041 (fetch/transfer)
D/BufferPoolAccessor2.0(29794): bufferpool2 0xcddb8b88 : 7(14336 size) total buffers - 4(8192 size) used buffers - 31587/31625 (recycle/alloc) - 118/63241 (fetch/transfer)
D/BufferPoolAccessor2.0(29794): bufferpool2 0xec37eb28 : 7(14336 size) total buffers - 4(8192 size) used buffers - 31262/31295 (recycle/alloc) - 102/62581 (fetch/transfer)

Add your record configuration `RecordConfig(...)`

 const encoder = AudioEncoder.aacLc;
  const config = RecordConfig(encoder: encoder, numChannels: 1);

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by llfbandit** [comment]
Thanks for the report.

Why are you sure this log is from the recorder?
What are you doing after stopping the recorder? Do you give the audio file to an audio player or this is the end of your process?

**Comment by llfbandit** [comment]
I tried to figure out what was going on but it seems there's nothing wrong in package source code.
Unless, you catch something for further investigation I won't spend more time on this because apps are not run on emulators in real life.
