### ISSUE TITLE
echo cancellation (ignoring device speakers while listing) 

### ISSUE THREAD

**Issue by amirharati** [llfbandit/record#355]
**Is your feature request related to a problem? Please describe.**
echo cancellation (ignoring device speakers while listing) 

**Describe the solution you'd like**
currently, the microphone pick up all the audio coming from speakers even when i set the echo cancellation in the config to true (tested on both android and ios, if possible  I like to reduce or completely suppress the speaker's input to microphone. the use case is ASR/TTS  where we want to allow ASR listen to user inputs rather than its own TTS when TTS is also running.

**Describe alternatives you've considered**
I have not yet any alternative. Checked the webrtc but i could not make it work yet and I am not sure if it solve the issue, base on my research there are some platform specific libraries but I am not familiar with platform coding,  

**Additional context**
-

**Comment by llfbandit** [comment]
On Android, you can set RecordConfig#androidConfig#muteAudio to true to completly mute all audio streams.

On iOS, just set RecordConfig#echoCancel to true, this works only when streaming for now (also support is not publicly documented). You must use latest version for this to work.
