### ISSUE TITLE
After using record, my apk size changed from 30MB to 68MB。Is that a bug?

### ISSUE THREAD

**Issue by tfn290181662** [llfbandit/record#357]
**Package version**

**Environment**
 - OS: [e.g. iOS/Windows/...]
 - Browser [e.g. chrome, safari] if issue is on web platform.

**Describe the bug**

Add your record configuration `RecordConfig(...)`

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tfn290181662** [comment]
It's too large for me . How can i fix this？

**Comment by llfbandit** [comment]
Since you don't provide any info I suggest you to analyse your apk before assuming this is due to the package.

**Comment by tfn290181662** [comment]
I

> Since you don't provide any info I suggest you to analyse your apk before assuming this is due to the package.

I just created a new Flutter project and built an APK. The resulting APK size was 18MB. After adding the record package, the APK size increased to 40MB. I didn’t make any other changes besides adding this package.So I think the increase in size is caused by the record package.

**Comment by llfbandit** [comment]
I agree, it may be quite surprising when building with APK type.
Building with `appbundle` reveals that default Flutter project is around 17MB and building example project leads to almost the same output size without any optimization for both.

Closing this, there's nothing wrong.

**Comment by echogit** [comment]
With appbundle it seems there is no noticeable chave, but with APK it really increases the size, which I haven't seem before

**Comment by zhangdc** [comment]
flutter build apk --release
 APK(37mb) -> APK(80mb)
