### ISSUE TITLE
throwing -1  when echoCancel is true on IOS

### ISSUE THREAD

**Issue by amirharati** [llfbandit/record#358]
**Package version**
5.1.2

**Environment**
 - OS: IOS app  (IOS 17.5.1)

**Describe the bug**
When EchoCancel is true produce the following (Also echo cancellations seems to be working and so far not crashing)
throwing -1
  from AU (0x155f97270): auou/vpio/appl, render err: -1

Add your record configuration `RecordConfig(...)`
RecordConfig(
      encoder: AudioEncoder.pcm16bits,
      sampleRate: 16000,
      numChannels: 1,
      echoCancel: true, 
    ));

**To Reproduce**

when echoCancel is active and stream starts the above error start to fill the console screen in xcode. 

**Expected behavior**

to not throw this exception. 

**Additional context**

**Comment by jaween** [comment]
Related: https://github.com/llfbandit/record/issues/341#issuecomment-2185072607
