### ISSUE TITLE
Continuously outputting after stop recording

### ISSUE THREAD

**Issue by dbb987** [llfbandit/record#360]
**Package version**
5.1.2

**Environment**
 - OS:  android app(30 and 34)

**Describe the bug**
On the Android end, the recording function is normal, but after calling stop to end the recording, the console still keeps outputting the following continuously

Add your record configuration `RecordConfig(...)`
await _record.start(
          const RecordConfig(),
          path: path
      );
_record.stop()

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by llfbandit** [comment]
Could you provide what output is it? Are you using an emulator?

**Comment by dbb987** [comment]
I did not use it on the emulator. I debug it on Android 14 (34), Android 13 (33), and Android 10 (29). I have found on these phones that even after stop recording, the console still outputs and writes information，

**The output is as follows:**  
D/MPEG4Writer(18575): + mBufferedDataSize(16371), chunk->mDataSize(16371) D/MPEG4Writer(18575): - mBufferedDataSize(0), chunk->mDataSize(16371)

**Comment by DanielusG** [comment]
I don't know if it is related, but i have a similar problem on linux, when i start the recording and stop, the file continue to grow after the stop, in fact if i send the file through http is says:
`HttpException: Content size exceeds specified contentLength. 671800 bytes written while expected 655529.`
