### ISSUE TITLE
Error while dexing

### ISSUE THREAD

**Issue by Roee-Tsur** [llfbandit/record#361]
**Package version**
5.1.2

**Environment**
 - OS: Android

**Describe the bug**
When trying to run the app on my pixel 6 (Android 14) I get the following error:

ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexBaseDebug'.
> Could not resolve all files for configuration ':app:baseDebugRuntimeClasspath'.
   > Failed to transform kotlin-stdlib-1.9.22.jar (org.jetbrains.kotlin:kotlin-stdlib:1.9.22) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=28, org.gradle.category=library, org.gradle.jvm.environment=standard-jvm, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for DexingNoClasspathTransform: /Users/roeetsur/.gradle/caches/transforms-3/50434e2ca90bd33b59b7d2306d134cbd/transformed/jetified-kotlin-stdlib-1.9.22.jar.
         > Error while dexing.

**Expected behavior**
Expected the app to build

**Additional context**
1. I followed the new 5.1.2 android configuration instructions
2. My project's kotlin version is 1.9.23, not 1.9.22, so I don't know how this error is related.

**Comment by elijahloola** [comment]
Package version
record 5.1.2

Environment
OS: Android
Describe the bug
When trying to run the app on my pixel 4 (Android 14) I get the following error:

> ERROR:C:\Users\elija\StudioProjects\AppName\build\record_android\intermediates\runtime_library_classes_jar\debug\classes.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.       
   > Failed to transform classes.jar (project :record_android) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.3.0, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.jvm.environment=android, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\elija\StudioProjects\AppName\build\record_android\intermediates\runtime_library_classes_jar\debug\classes.jar.
         > Error while dexing.

**Comment by pierremrtn** [comment]
Same problem

**Comment by llfbandit** [comment]
record_android published to 1.2.4. Revert to Java 8.
If you still encounter issue, please refer to https://github.com/llfbandit/record/tree/master/record_android to update AGP plugin.
