### ISSUE TITLE
Is there any way to save the output audio file to phone storage where i could actually decide where to save and can manually get the file?

### ISSUE THREAD

**Issue by mzramle** [llfbandit/record#364]
I have gotten to record and playback the file but somehow i could not get to find any saved audio recorded files on my phone. Where is it? I would like to see a list of recorded audio files to fetch. 

one thing im noticing upon using stop(), it will save the file to an audio platform object but im not sure where to manipulate the data for saving files directly on phone storage. How can i do this?

```
Recorder(
                      onStop: (path) {
                        if (kDebugMode) print('Recorded file path: $path');
                        setState(() {
                          audioPath = path;
                          showPlayer = true;
                        });
                      },
                    ),
```

```
  Future<void> _stop() async {
    final path = await _audioRecorder.stop();

    if (path != null) {
      widget.onStop(path);

      downloadWebData(path);
    }
  }
```

**Comment by llfbandit** [comment]
Yes upgrade the package and read the readme.md
