### ISSUE TITLE
hasPermission does nothing in mobile browsers

### ISSUE THREAD

**Issue by giaesp** [llfbandit/record#368]
**Package version**
5.1.2

**Environment**
 - OS: Android, iOS
 - Browser: Chrome, Safari

I'm trying to record an audio in a Flutter Web project. It works very fine in desktop browsers, but it lacks the permission requests in mobile browsers, so it doesn't record anything. I have a simple button with this code associated:

```
startRecording() async {
    if (await _audioRecorder.hasPermission()) {
      _isRecording = true;
      notifyListeners();
      await _audioRecorder.start(
          const RecordConfig(
            encoder: AudioEncoder.wav,
          ),
          path: 'ONWEBTHISPARAMETERISIGNORED :)');
    }
  }
```

Just a note: I'm running in **HTTP**. Does permission requests require **HTTPS**?

**Comment by llfbandit** [comment]
There's nothing different between mobile or desktop browsers, web API is the same. Secured layer shouldn't be a part of this issue.
What do you mean by "does nothing"? I guess you had an exception that you didn't handle. If so, could you provide info about it?

**Comment by giaesp** [comment]
I'm expecting to see the classic authorization request dialog but it doesn't appear. 
I have no messages in web console and in debug console. 
I'm pretty sure this is not a package bug, but a browser standard security behavior: when I'm running in debug in http://localhost it works in every browser, desktop and mobile, I've tested. In the deployed version, running in http due to some my restrictions, it simply does absolutely nothing. I'll try in an https environment so I'll confirm to you. Thank u!

**Comment by giaesp** [comment]
I can confirm, under https everything works like a charm.
Sorry for opening the bug, this is not a package bug, just a browser security settings! Thank u!
