### ISSUE TITLE
Allow mp3 enconding

### ISSUE THREAD

**Issue by TimeLord2010** [llfbandit/record#37]
Is there any way to create an mp3 from the recorded audio?

**Comment by llfbandit** [comment]
Mp3 is not supported since underlying sdk don't have this codec.

**Comment by TimeLord2010** [comment]
I did manage to create a playable audio mp3 file. But I need to send an audio file in mp3's mpeg format to another service, which doesn't seen to be possible inside a flutter project right now.

I have tow options right now:

- Create my own algorithm to convert acc enconding to mpeg. Which is [hard](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.26.5956&rep=rep1&type=pdf);
- Create a server that received a aac enconded file and converts it to mped enconding using [ffmpeg](http://www.ffmpeg.org/);
