### ISSUE TITLE
Recorded file on android couldn't play on iOS

### ISSUE THREAD

**Issue by nzackoya** [llfbandit/record#370]
**Package version**
5.1.2

**Environment**
 - OS: android

**Describe the bug**

Recorded on android file doesn't play on iOS.

Default settings of `RecordConfig`

**To Reproduce**

Simply play file on iOS recorded on android

**Expected behavior**

Should play

**Comment by llfbandit** [comment]
It should play, be sure to set .m4a extension or something understandable for iOS.
