### ISSUE TITLE
Noise supression on iOS

### ISSUE THREAD

**Issue by alexgrusu** [llfbandit/record#380]
**Is your feature request related to a problem? Please describe.**
I see we have an option for noise suppression, but the documentation highlights that this feature is available for Android only.

**Describe the solution you'd like**
I would like that option to be available on iOS as well and enable noise suppression while recording.

**Describe alternatives you've considered**
I'm still researching this field, but there are a few options. Most are not open-source, involve costs, or apply noise suppression on an existing file.

**Additional context**

**Comment by llfbandit** [comment]
As far as I know, there's no noise suppression filter available for iOS. If it's not provided by the SDK, there will be no implementation for this plugin.
FYI, while undocumented, echo cancel and auto gain are implemented when streaming.
