### ISSUE TITLE
[IOS] PlatformException setPreferredInputNumberOfChannels

### ISSUE THREAD

**Issue by PhuCG** [llfbandit/record#384]
**Package version**
`record 5.1.2`

**Environment**
 - IOS: IPhone 12Promax - v17.5.1
 - Flutter: 3.24.0
 - Dart: 3.5.0

**Describe the bug**
When I call the recording stream function a few times, the following error starts appearing.
`PlatformException (PlatformException(record, Failed to start recording, setPreferredInputNumberOfChannels: The operation couldn’t be completed. (OSStatus error -50.), null))`
My config:
```dart
  const config = RecordConfig(
    encoder: AudioEncoder.pcm16bits,
    numChannels: 1,
    bitRate: 16,
    sampleRate: 16000,
  );
```

**Comment by llfbandit** [comment]
Value for bitRate is very wrong.
