### ISSUE TITLE
File not saving after stopping the recording in linux 

### ISSUE THREAD

**Issue by arxlan30** [llfbandit/record#385]
**Package version**

**Environment**
 - OS: [Linux]
 - Browser [e.g. chrome, safari] if issue is on web platform.

**Describe the bug**

 recording audio on linux desktop application but the issue is that when i stop recording its not saving the file. So I am unable to play the audio.
 
Add your record configuration `RecordConfig(...)`
 record.start(const RecordConfig(), path: filePath,);

**To Reproduce**

  void _startRecording() async {
    setState(() {
      _isRecording = true;
      _recordDuration = 0;
    });
    String audioRecordId = DateTime.now().millisecondsSinceEpoch.toString();

    String dir = (await getApplicationDocumentsDirectory()).path;
    final String filePath = '$dir/$audioRecordId$audioExtension';

    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      setState(() {
        _recordDuration++;
      });
    });
    await record.start(const RecordConfig(), path: filePath,);

  }

  void _stopRecording() async {
    if (_timer != null) {
      _timer!.cancel();
    }

    setState(() {
      _isRecording = false;
    });
    final path = await record.stop();
    await record.cancel();

  }

**Expected behavior**

**Additional context**

**Comment by llfbandit** [comment]
`await record.cancel();` deletes the file...

**Comment by arxlan30** [comment]
> `await record.cancel();` deletes the file...

Still not saving the file I am using your provided example. On stop its showing the path but this path has no audio file. 
My OS is  Ubuntu 22.04.3 LTS
I am building application for linux desktop.

file path I get onStop :/home/abc/audio_1724627047648.m4a

error if try to read the file 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Cannot retrieve length of file, path = '/home/abc/audio_1724627047648.m4a' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:389:7)
<asynchronous suspension>
