### ISSUE TITLE
upgrade web dependecy to ^1.0.0.

### ISSUE THREAD

**Issue by Ali-Fadaei** [llfbandit/record#389]
current web: 0.5.1 dependency got incompatibly error with some other packages.

**Comment by llfbandit** [comment]
Current dependency is already set at `web: ">=0.5.1 <2.0.0"`
Please ensure you upgraded to record_web: 1.1.2 in pubspec.lock file.

**Comment by Ali-Fadaei** [comment]
![Screenshot 2024-08-27 115016](https://github.com/user-attachments/assets/cedd9c91-0364-44c1-ae1b-83077f9e1ad8)

thanks for response.

why it won't set to 1.1.2 automatically?
pubspec.lock file is generated by pub get and can't be edited when CI/CD builds the App.

**Comment by rnl-veolys** [comment]
Running `pub get` doesn't upgrade your dependencies.
You need to use `pub upgrade` for this, especially for transitive dependencies.

Like in this issue, `record` package hasn't changed while sub-packages have.

With, `pub get`, Your CI just takes the lock file to retrieve the dependencies and stay constitent with the state of your development. This is absolutly normal, you don't want any diff between what you had on your side and what you will push to your users.

Note: each time I release `record` root package, I try to update the dependencies to enforce a seamless upgrade for you.

**Comment by llfbandit** [comment]
Running pub get doesn't upgrade your dependencies.
You need to use pub upgrade for this, especially for transitive dependencies.

Like in this issue, record package hasn't changed while sub-packages have.

With, pub get, Your CI just takes the lock file to retrieve the dependencies and stay constitent with the state of your development. This is absolutly normal, you don't want any diff between what you had on your side and what you will push to your users.

Note: each time I release record root package, I try to update the dependencies to enforce a seamless upgrade for you.
