### ISSUE TITLE
Unexpected behaviour: can't play/pause audio using headphones after starting and stopping recording

### ISSUE THREAD

**Issue by bartolomej** [llfbandit/record#391]
**Package version**
- record: 5.1.2
-  audio_service: 0.18.15

**Environment**
 - OS: IOS

**Describe the bug**

I'm using [audio service](https://github.com/ryanheise/audio_service) lib to play audio and receive play/pause events. It all works as expected, but once I start (and later stop) recording using [recorder](https://pub.dev/packages/record) library, the play/pause events are not received anymore. And that's even after I dispose of the recorder (call `_audioRecorder.dispose()`).

**To Reproduce**

Here is a reproducible example (hit the microphone button to start recording, and then hit it again to stop recording): https://github.com/bartolomej/audio-service-headset-controls-example

**Expected behavior**

I would expect the play/pause events to be received even if the audio is being recorded (or a configuration option that allows that). Note that I can play the audio while recording, but only by calling play/pause explicitly on the audio player, and not by using the headphone controls.

**Comment by llfbandit** [comment]
Package now has specific iOS config to bypass `AudioSession` setup: `manageAudioSession`.
