### ISSUE TITLE
record issue on second time

### ISSUE THREAD

**Issue by itsdani121** [llfbandit/record#40]
When i record start and stop then check the record file it works perfect but when i again want to record with same name and path then it did replace with previous one but when i want to play it did not play it suppose my file path is 'directory.path/myfile.mp3'  first time record file perfect after again record same name it replace but not played. kindly look into this matter what issue is even i delete directory but still facing this issue.

                 var dir= await getExternalStorageDirectory();

// for start record
           
               await Record().start(
                        path: '${dir!.path}/myFile.m4a', // required
                        encoder: AudioEncoder.AAC, // by default
                        bitRate: 128000, // by default
                        samplingRate: 44100, // by default
                      );

//for stop record
             
            var value =await Record().stop();

// for delete file 
             
             var file = File('${dir.path}/myFile.m4a');
                      if(await file.exists()){
                        await file.delete();
                        dir.delete();

                      }

**Comment by bhargav6744** [comment]
change myFile to : ${DateTime.now().millisecondsSinceEpoch.toString()}

**Comment by llfbandit** [comment]
It's hard to help since there is no stacktrace. But, with the provided code, I guess deleting the parent directory `dir.delete();` is not a good idea.
The file can be overwritten but the directory must be available before recording.

Anyway, the seems not related to the package.
