### ISSUE TITLE
[Web] Using default microphone even when selecting other input device

### ISSUE THREAD

**Issue by bloemy7** [llfbandit/record#408]
**Package version**: 5.1.2

**Environment**
 - OS: [e.g. iOS/Windows/...]: MacOS
 - Browser [e.g. chrome, safari]: Chrome

**Describe the bug**

When passing a non-null input device:
```
    RecordConfig config = RecordConfig(
      encoder: _codec,
      numChannels: 1,
      device: recordInputDevice,
    );
```
where I verify it is non null, and the ID is valid and taken from the list retrieved just before, it still just records with the default macOS microphone.

**To Reproduce**

1. Start recording on web and pass it an input device that is non-null.

**Expected behavior**

Expect it to use the input device as microphone.

**Comment by llfbandit** [comment]
Thanks for the report.
