### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by shalikhshab00** [llfbandit/record#41]
When tapping on the record button I'm getting this error:

PlatformException(, Failed to start recording, null, null)

It works perfectly on android and I'm able to play the recording too

**Comment by mhstoller** [comment]
Please provide the code you are using to invoke and start the recorder

**Comment by llfbandit** [comment]
Did you use the example? Also not sure if it works OK on simulator...

**Comment by sapun4ik** [comment]
Your example works fine on ios simulator
