### ISSUE TITLE
startStream issues

### ISSUE THREAD

**Issue by JinYi-Tsinghua** [llfbandit/record#414]
**Package version**
5.1.2

**Environment**
 - OS: Android

**Describe the bug**

.listen has no data unless `encoder: AudioEncoder.pcm16bits` is used, yet no error is triggered. All other AudioEncoders fail silently, despite working just fine when start() is used instead of startStream().

Furthermore, even if pcm16bits is used with startStream(), there is no documented way to play it back.

Furthermore, when pcm16bits is used with start(), it produces a file that cannot be played back via AudioPlayer(), unlike all other AudioEncoder formats.

If I am wrong and startStream is not unusable (either with pcm16bits or other), then an example file needs to be written to show how to utilize startStream to produce an output that can be played back with AudioPlayer().

**Comment by JinYi-Tsinghua** [comment]
....yeah so this issue shouldn't be closed. It is unresolved. startStream is broken on Android except for PCM.

**Comment by tauqeer-batman** [comment]
It is still broken on Android.

**Comment by JinYi-Tsinghua** [comment]
If anyone else comes across this issue:

https://github.com/llfbandit/record/blob/8293d049715c4048e4abc51d4240eea1891a15d5/record/example/android/settings.gradle#L22

Set the id "com.android.application" version from 8.1.0 or whatever to 8.7.0 or whatever, and fix all the build errors that occur.

This should be documented, and there should be errors.
