### ISSUE TITLE
echoCancel doesn't work on Samsung devices

### ISSUE THREAD

**Issue by gaochang1993** [llfbandit/record#418]
**Package version**
5.1.2

**Environment**
 - OS: Android
 - devices: samsung S9010,

**Describe the bug**

On samsung device with echoCancel enabled, the currently playing audio is still packed up in the recording stream. It does not work on Samsung phones, but works on other brands of Android phones and ios devices. Here is the RecordConfig:
`_audioRecorder.startStream(const RecordConfig(
        sampleRate: 24000,
        numChannels: 1,
        bitRate: 24000,
        echoCancel: true,
        noiseSuppress: true,
        encoder: AudioEncoder.pcm16bits,
      )
`

And I found the same issue[373](https://github.com/llfbandit/record/issues/373)，fixed in record_android version 1.2.6. But the record_android version that record 5.1.2 depends on is 1.2.3. So I add `dependency_overrides:
  record_android: 1.2.6`  to my pubsec.yaml，but it seems not work. What can I do to fix it.

**Comment by llfbandit** [comment]
Effects may or may not be available on the device as I do not implement these algorithms myself.

You can already use `record_android`: 1.2.6. Just use `flutter pub upgrade` to upgrade your transitive dependencies.

**Comment by gaochang1993** [comment]
> Effects may or may not be available on the device as I do not implement these algorithms myself.
> 
> You can already use `record_android`: 1.2.6. Just use `flutter pub upgrade` to upgrade your transitive dependencies.

I have upgraded, but this bug always ocurred.

**Comment by iak-a-dev** [comment]
@gaochang1993 do you found any solution ?

**Comment by gaochang1993** [comment]
> @gaochang1993 do you found any solution ?

No, I had tried to set AudioManager.mode=MODE_COMMUNICATION,  but it didn't work. It seems we need to implement the echo cancellation algorithm ourselves or seek official help from Samsung.
