### ISSUE TITLE
[Windows] Cant recording  when path contains CJK character

### ISSUE THREAD

**Issue by ZhuJHua** [llfbandit/record#422]
**Package version**
record: 5.1.2

**Environment**
 - OS: Windows

**Describe the bug**

Cant recording on windows, I used the `path_provider` package to get the cache directory of the application.The path contains a username which is a CJK character like `C:\Users\住京华\AppData\Local\cn.yooss\mood_diary\audio-0192ce6d-ad7c-7386-9ac5-69adf5557f64.m4a`. Then recording threw this exception after calling the start method.
![image](https://github.com/user-attachments/assets/a89adb9b-d861-4c81-8421-ed90708600a3)

However, when using a latin only path, it works well.

**My Code**
This is my code
```dart
state.fileName = 'audio-${const Uuid().v7()}.m4a';
await audioRecorder.start(
          const RecordConfig(androidConfig: AndroidRecordConfig(muteAudio: true, useLegacy: true)),
          path: Utils().fileUtil.getCachePath(state.fileName));
```
The `getCachePath()` method is just used the `getApplicationCacheDirectory()` method in `path_provider` package.

It work well on Android devices, but not windows.

**Comment by llfbandit** [comment]
Thanks for the report. This should be fixed with the corresponding commit but I can't test it myself.
So feedback is very welcome!

**Comment by ZhuJHua** [comment]
It works fine as you can publish it into pub, thanks a lot!🥰
