### ISSUE TITLE
No longer able to record with wav encoding on mobile web (Chrome or Safari on iOS)

### ISSUE THREAD

**Issue by drdevinhopkins** [llfbandit/record#424]
**Package version**
record 5.1.2

**Environment**
- Chrome & Safari browsers on iOS

**Describe the bug**

Ever since record_web 1.1.0, recording in wav on mobile browser in iOS sends an empty file to the transcription API I'm using.

const RecordConfig({
    this.encoder = AudioEncoder.wav,
    this.bitRate = 128000,
    this.sampleRate = 44100,
    this.numChannels = 2,
    this.device,
    this.autoGain = false,
    this.echoCancel = false,
    this.noiseSuppress = false,
  });

Downgrading to record_web 1.0.5 seems to fix the problem

Thanks!

**Comment by AhmedAbogameel** [comment]
any updates ?

**Comment by drdevinhopkins** [comment]
> i am facing the same error any updates ?

Seems to be fixed in 1.1.4
