### ISSUE TITLE
Missing macOS privacy manifests

### ISSUE THREAD

**Issue by bishalstha** [llfbandit/record#425]
**Package version**
5.1.2

**Environment**
 - OS: MacOS

**Describe the bug**

macOS privacy manifest enforcement has rolled out and it is mandatory for submission of the app. So, it is required by this package for macOS

**To Reproduce**

1. Just try to submit the build app to the app store

**Comment by llfbandit** [comment]
Thanks for the report. Manifests were added to iOS & macOS.
ed927c754692a9433dbcb9ae89dd780bc5e472e0
