### ISSUE TITLE
[MacOS] Can't build on mac os

### ISSUE THREAD

**Issue by ZhuJHua** [llfbandit/record#428]
**Package version**
5.2.0

**Environment**
 - OS: [MacOS]

**Describe the bug**

It seems like u forget to update the file on MacOS? after ba201f6?

I got this error:
<img width="1314" alt="截屏2024-11-04 02 18 48" src="https://github.com/user-attachments/assets/a9571be7-4723-4286-9dfa-b5384f33cd47">

**Comment by llfbandit** [comment]
Thanks for the report. Sorry about that, record_darwin: 1.2.2 will be published in few minutes.

**Comment by llfbandit** [comment]
Fixed in dee6ea8f09ee58bc0a1b54fbd5d8472dc8d41dbe
