### ISSUE TITLE
[Android] Low microphone quality through Bluetooth audio

### ISSUE THREAD

**Issue by Zazo032** [llfbandit/record#431]
## Package version
`5.2.0` and `5.1.2`

## Environment
 - OS: Android (14)
 - Flutter: 3.22.3

## Describe the bug

When performing an audio recording with a Galaxy device (I couldn't test other brands but this is reproducible in different Galaxy models) with a Bluetooth headset connected (I used AirPods Pro for testing but we have reports of other standard Bluetooth devices), the audio quality of the recordings is _bad_. The audio seems to be recorded through Bluetooth SCO and there's no way to do it through A2DP, so all audio recorded through Bluetooth devices has a low audio quality. I tried setting `manageBluetooth` to `false` but then the audio is recorded through the device microphone and not through the Bluetooth one. Setting `numChannels` to `1`, `useLegacy` to `true` or modifying the `audioSource` also doesn't seem to have any effect in the recording quality.

## Record configuration
```dart
const RecordConfig()
```

## Steps to reproduce

1. Run `example` project on an Android device (only tested it in Galaxy devices)
2. Connect a Bluetooth headset that supports "Calls" audio profile/channel (screenshot attached)
3. Record and play some audio through the Bluetooth device (input and output).

<details>
<summary>Bluetooth device settings</summary>

![Screenshot_20241106_154228_Settings](https://github.com/user-attachments/assets/d91b4342-dd40-4936-9325-cea926a37e46)
</details>

## Expected behavior

Audio gets recorded with the same or similar audio quality to the native recorder app.

## Actual behavior

Audio gets recorded with a significantly worse quality than expected when recording through a Bluetooth microphone.

## Additional context

Disabling the "Calls" option in the Bluetooth device settings is a workaround to get the expected audio recording quality.

**Comment by llfbandit** [comment]
Thanks for the report.
What if you try the set the device? There's no automatic selection of the device but with `manageBluetooth` SCO flag.

**Comment by Zazo032** [comment]
> Thanks for the report. What if you try to set the device? There's no automatic selection of the device but with `manageBluetooth` SCO flag.

Do you mean through `RecordConfig.device`? There doesn't seem to be a way to retrieve an `InputDevice` from Android to pass it to that parameter

**Comment by Zazo032** [comment]
`listInputDevices()` is documented as returning an empty list in Android: https://pub.dev/documentation/record/latest/record/AudioRecorder/listInputDevices.html

I know the `id` and `label` from the device I'm using through a different plugin (`mic_info`), I tried with the following configuration but the recorded audio quality is still the same:

```dart
const RecordConfig(
  device: InputDevice(id: '309', label: 'AirPods Pro de Cristian'),
  androidConfig: AndroidRecordConfig(
    manageBluetooth: false,
  ),
),
```

**Comment by Zazo032** [comment]
I just tried with `listInputDevices()` by hardcoding the object from the list that corresponds to the Bluetooth device with `manageBluetooth: false`, but the issue still persists

**Comment by llfbandit** [comment]
There's nothing I can do if your device is recognized as a telephony device.
SCO is very limited, that's why you get low quality. You can try to look for settings in your phone to enable it as A2DP if available.
