### ISSUE TITLE
[Feature Request] Echo Cancellation on macOS

### ISSUE THREAD

**Issue by keyur2maru** [llfbandit/record#439]
Thank you for developing this package! The echo cancellation feature works flawlessly on iOS, Android, and Web. However, I noticed that it is not supported on macOS or Windows. For macOS, According to the [AVAudioIONode](https://developer.apple.com/documentation/avfaudio/avaudioionode) documentation, the [setVoiceProcessingEnabled](https://developer.apple.com/documentation/avfaudio/avaudioionode/3152100-setvoiceprocessingenabled) method is supported on macOS 10.15 and later. If this documentation is accurate, is there another reason why echo cancellation is not supported on macOS?

To troubleshoot, I tried removing the `if #available(iOS 13.0, *)` and `#if os(iOS)` checks in the `record_darwin/darwin/Classes/delegate/RecorderStreamDelegate.swift` file, but this didn’t resolve the issue. 

If needed, I’ve shared the full diff of my changes [here](https://gist.github.com/keyur2maru/3a8fc64cfa2230eb5eca389c65875cd8).

**Comment by llfbandit** [comment]
This is not enabled for macOS because I was getting errors when dealing with this activation.
By the way, AGC & echo cancel does not work for file recording.

**Comment by keyur2maru** [comment]
Makes sense. Thank you for the explanation. I am closing the issue.
