### ISSUE TITLE
Question/Request Can we save files without using `stop()`?

### ISSUE THREAD

**Issue by darajava** [llfbandit/record#440]
**Is your feature request related to a problem? Please describe.**
Sometimes my users pause the recording, minimize the app, and after some time the OS flushes the app out of memory, causing a restart and losing their partial recording. I want to be able to save the recording and load it up again.

The files generated before calling `stop()` are corrupted and cannot be used.

**Describe the solution you'd like**
This actually requires 2 different features:
 - The file generated to `path` is usable after only calling `pause()`
 - Being able to start a recording from a "half-baked" path.

**Describe alternatives you've considered**
I'd love a simpler solution to this, like being able to save the entire app state or something and thus preventing the OS from flushing the app out of memory. If anyone knows how to fix this problem please let me know!

**Comment by darajava** [comment]
I think this is probably unrealistic to implement.

**Comment by ismail-go** [comment]
This is absoulutly needed use case scenario. Because the user data must not be lost ever. We need to backup the record in any time interval while recording is continuing @darajava @james-pellow @bbjay @t-unit @pallopmax
