### ISSUE TITLE
For ios recording is not auto resuming while getting a call or mic is used by another app while recording is ongoing

### ISSUE THREAD

**Issue by rushik01provoyants** [llfbandit/record#442]
**record: ^5.0.5**

**Environment**
 - OS: iOS

**Description**

When recording is ongoing on an iPhone & the user puts the app in the background & if a user receives any call & after attending call & the user goes back to the app, the recording is stopped.

<img width="929" alt="Screenshot 2024-11-26 at 8 55 02 PM" src="https://github.com/user-attachments/assets/22f3d3d8-5fce-4d47-b75d-d39eba719012">

**To Reproduce**

1. Go to App
2. Start recording
3. Go to background & if the user gets any call & he receives
4. The recording will stop & never work again, the user has to start it manually.

**Expected behavior**
If Mic is in use by another app or priority service, that time recording should pause & once that task is done the again package should get the control back & continue the recording.

**Additional context**
If the app is in the background & the user will move to any other app that is expecting mic permission, in that case as well it's not working,

**Comment by llfbandit** [comment]
This package is not responsible of the lifecycle of your app.
You should get an event to warn you that the recording has been paused.

When, resuming your app, you can also resume the recording depending on your own factors.
