### ISSUE TITLE
ClassNotFoundException  

### ISSUE THREAD

**Issue by Abyj269** [llfbandit/record#444]
**Package version**
record: ^5.0.4

**Environment**
 - OS: [e.g. Android]
 
Device: Family
I2219

**Describe the bug**

Exception - This event

NoClassDefFoundError: Failed resolution of: Lcom/llfbandit/record/Utils;

The problem primarily arises with the device's release build.

**Comment by llfbandit** [comment]
Upgrade your package and transitive dependencies.
