### ISSUE TITLE
duration returns null on web

### ISSUE THREAD

**Issue by sunilguptasg** [llfbandit/record#45]
Widget _buildSlider(double widgetWidth) {
    final position = _audioPlayer.position;
    final duration = _audioPlayer.duration;

the 'duration' call returns null on Chrome - works on actual android devices.

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)

**Comment by llfbandit** [comment]
Yes, web platform implementation is basic for now.
Most of the features are stubs on it.

**Comment by sunilguptasg** [comment]
Thanks! Would you know of another other method to query the duration of the audio file - I could use this method when _audioPlayer.duration returns null..

**Comment by llfbandit** [comment]
You can setup your own timer when starting and stopping the record.

**Comment by llfbandit** [comment]
Closed because unrelated to record package.

**Comment by GauravCalidig** [comment]
This is a feature request, can you keep this open please @llfbandit
