### ISSUE TITLE
Swift Compiler Error (Xcode): Reference to member 'mixWithOthers' cannot be resolved without a contextual type

### ISSUE THREAD

**Issue by AmirK102** [llfbandit/record#450]
I am using flutter version: 3.22.3

Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           124.2s
Failed to build iOS app
Swift Compiler Error (Xcode): Reference to member 'mixWithOthers' cannot be resolved without a contextual type
/Users/amirk/.pub-cache/hosted/pub.dev/record_darwin-1.2.2/ios/Classes/RecordConfig.swift:79:11

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

**Comment by quensh93** [comment]
same as here
[ver](record: ^5.1.2)

**Comment by llfbandit** [comment]
Thanks for reporting.
I updated the code to call explicitly enum values. But I suggest you to update your setup. It should already compile.

**Comment by githubdoandre** [comment]
> Thanks for reporting. I updated the code to call explicitly enum values. But I suggest you to update your setup. It should already compile.

What is the solution? the last package version is 5.2.0 (50+ days ago..)
