### ISSUE TITLE
iOS - Resume record issue after lock iPhone device or simulator

### ISSUE THREAD

**Issue by doshikh** [llfbandit/record#50]
I have used SystemChannels.lifecycle.setMessageHandler method to get Phone OS App Lifecycle state 

When iPhone lock onPause called and I have user pause method to pause audio recording but when I unlock screen and call resume method it will only give recording before Lock Screen happened.

Example :
1. Record 4 sec audio and than lock device
2. Unlock device resume recording upto 10 sec
3. Stop Recording on 10 sec
4. It only gives 4 sec audio recorded file as source.

Please help me out.

**Comment by llfbandit** [comment]
There is no support for recording in background state. The current record is automatically stopped.

**Comment by doshikh** [comment]
yes , but why we can not pause recording and resume it again ?
is It not supported too ?

**Comment by llfbandit** [comment]
Yes it is supported. But you need to stay with an active application (and controller/activity).
