### ISSUE TITLE
Please provide the support for AudioEncoding.Linear16 for transcribing audio files

### ISSUE THREAD

**Issue by ajinkya446** [llfbandit/record#52]
## Description:

Need to record audio file whose sample rate is 16000 and encoder is linear 16 for transcribing audio files using goggle_speech.

## Need support:

Future<void> start({
    String? path,
    AudioEncoder encoder = AudioEncoder.AAC,
    int bitRate = 128000,
    double samplingRate = 44100.0,
  }) 

Change encoder to linear16 and sample rate to 16000.0 also change audio file type to to audio and it is showing on metadata as video file after recording 

![image](https://user-images.githubusercontent.com/49361315/161010052-e3daa9be-ab8b-4f7d-b0c1-24219c10b436.png)

**Comment by llfbandit** [comment]
Unlikely, MediaRecorder on Android does not provide a way to record to PCM.
So we must use AudioRecord instead.

On iOS it seems ok to implement directly those settings.

**Comment by ajinkya446** [comment]
@llfbandit so could you please provide this support using AudioRecord instead of MediaRecorder on android. If it is possible to mark this as feature request.

**Comment by llfbandit** [comment]
This is now available in new 4.0.0 version.
