### ISSUE TITLE
[MacOS] File audio recorded but it is empty

### ISSUE THREAD

**Issue by Fraa-124** [llfbandit/record#57]
Hello, I'm testing it in my mac (m1), I was able to record it like in the other platforms (ios, android), the file is generated but when I want to listen it is empty. I tried to listen with external players like VLC.

I'm using a external mic (integrated with the camera) So maybe the library is not using it, I don't know.

**Comment by llfbandit** [comment]
Thanks for the report.
It is a possibility, for now, the package has no option to select the capture device. So the default one is taken.
