### ISSUE TITLE
Feature: add device selection

### ISSUE THREAD

**Issue by llfbandit** [llfbandit/record#58]
For now, the package does not allow to select the input device.
Let's provide a way to list and use them where applicable.

**Comment by Fraa-124** [comment]
@llfbandit are you working on this? If not, can you provide me some guide or tips so I can try to implement this?

**Comment by llfbandit** [comment]
Sorry, not enough spare time to make progress on this for now.

Android and iOS are not really considered for this issue. We should stick with automatic selection between microphone and bluetooth (which is not implemented for Android).

For other platforms:
Listing available devices:
- macOS: The documentation entrypoint is: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/choosing_a_capture_device
This list should be filtered with AVMediaType.audio.
- windows, linux: fmedia provides `--list-dev`. I currently don't know the output format (position + label certainly).

Setting input device:
- Additional and optional argument to `start` method defining the device position.

**Comment by DomingoMG** [comment]
I'm going to try to pick up this plugin and add new features as per official fmedia documentation

**Comment by DomingoMG** [comment]
![image](https://user-images.githubusercontent.com/36201422/174931550-9ebc9e56-8864-41d6-9f32-8db073dee32d.png)

I already have separate input and output devices.

I still need to adjust the code a bit, it is only tested on Windows, it would be necessary to see if it works on Linux, MacOS.

In Android and iOS I don't know if this is possible and in WEB I haven't tried it, by default it will return an empty list.

**Comment by DomingoMG** [comment]
![image](https://user-images.githubusercontent.com/36201422/174944621-1f33a7ca-37a3-48da-b7a4-a5ef10b30c35.png)

To start recording I have added Device? captureDevice.

If it is null, it will obtain the default device of the system. In case of assigning a capture device, it will record through that input line.

**Comment by llfbandit** [comment]
Thanks for your time.
Please fill a PR, to follow any progress. Set it as WIP for clarity.
'output' or 'playback' devices are out of scope, this package is only related to recording features.

**Comment by DomingoMG** [comment]
I have done my first PR on input and output devices.

Regarding the package, I find it interesting that PC users have the possibility to select the input device for their recording, since the default microphone may not be the one you want to use.

I have left a unit test called => devices_test.dart so that you can evaluate what has been developed, we can close the problem until further notice.

**Comment by llfbandit** [comment]
Available from 4.2.0-dev.3. Fedbacks welcomed!

**Comment by Fraa-124** [comment]
I tried on Macos with a minimal example and an exception was thrown 

```dart
print('device ${device!.toMap()}');
await _audioRecorder.start(device: device);
```
```
flutter: device {id: AppleUSBAudioEngine:Unknown Manufacturer:HD Pro Webcam C920:FDBF5BBF:3, label: HD Pro Webcam C920, channels: null, samplingRate: null}
flutter: PlatformException(-2, Failed to start recording, Input device not found or not suitable., null)
```

let me know if you need more details

**Comment by llfbandit** [comment]
I'm sad to read this.
This error message means you can't select this device for audio (only?) recordings... I'll double check but...

**Comment by llfbandit** [comment]
@Fraa-124  I uploaded record_macos 0.2.1 to better see what the issue could be.
If you can retry?

**Comment by Fraa-124** [comment]
I keep getting the same error but It should be a different one, right? I tried to rebuild podspec and doing flutter clean but I don't get it to work

**Comment by llfbandit** [comment]
Yes, are you trying with the example?
If you upgrade its `pubspec.yaml` you should see record_macos in version 0.2.1 in `pubspec.lock` file.

**Comment by Fraa-124** [comment]
You are right, now it works.

It's a permission issue, I'm researching how to activate them because when the app started It didn't requested it.

`flutter: PlatformException(-2, Failed to start recording, Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use HD Pro Webcam C920" UserInfo={NSLocalizedFailureReason=This app is not authorized to use HD Pro Webcam C920., AVErrorDeviceKey=<AVCaptureHALDevice: 0x600001145d00 [HD Pro Webcam C920][AppleUSBAudioEngine:Unknown Manufacturer:HD Pro Webcam C920:FDBF5BBF:3]>, NSLocalizedDescription=Cannot use HD Pro Webcam C920}, null)`

When done, I'll test it on Windows and Linux as well

**Comment by llfbandit** [comment]
I think you need to add [NSCameraUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nscamerausagedescription) in your `Info.plist` file and this package will only request for audio permission not video. Even if the camera has a microphone and be can be used for audio recording, I guess the OS still needs permission for video in your case.

**Comment by Fraa-124** [comment]
It doesn't seem to work with [NSCameraUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nscamerausagedescription) either. Tested with blueetooth mic as well.

I checked OS permissions but I'm afraid the app has to request it first to enable or disable in OS settings.

It is working on Windows & Linux as expected. 

Maybe is bypassing this method returning default? I tried to debug but I don't get it working. Swift is a nightmare for me.

```dart
      final hasPermission = await _audioRecorder.hasPermission();
      print('hasPermission $hasPermission');
```
```
     flutter: hasPermission false
```

```swift
fileprivate func hasPermission(_ result: @escaping FlutterResult) {
    switch AVCaptureDevice.authorizationStatus(for: .audio) {
      case .authorized:
        result(true)
        break
      case .denied:
        result(false)
        break
      case .notDetermined:
        AVCaptureDevice.requestAccess(for: .audio) { allowed in
          DispatchQueue.main.async {
            result(allowed)
          }
        }
        break
      default:
        break
    }
  }
```

**Comment by llfbandit** [comment]
You're right, there's a missing case (.restricted) in there. But this will not solve the permission issue, as I should return false also.
There's no permission check on Windows and Linux at this moment, it's always `true`.
If you have the code locally, you can try with .video.

For your bluetooth device, I think there's a capability to activate and permission to request also. Yes, it's boring...

**Comment by skol101** [comment]
Will this allow selection of microphone input on iOS for instance? We need to use bottom only microphone to record speech.

**Comment by skol101** [comment]
I meant having an ability to select input device like this
https://developer.apple.com/documentation/avfaudio/avaudiosession/capturing_stereo_audio_from_built-in_microphones

**Comment by skol101** [comment]
Understood . Cheers.
