### ISSUE TITLE
Dispose recording on web

### ISSUE THREAD

**Issue by dannycortesv** [llfbandit/record#59]
Once i stop recording i dispose the record instance, but this doesn't stops audio stream from the broswer, still mic icon active on the browser status bar, am i missing something?

BTW thanks for this amazing plugin!!!

**Comment by llfbandit** [comment]
Thanks for the report.

I guess there's something missing in the package then.
I just saw that MediaStream should be processed to close all tracks.
```dart
stream.getTracks().forEach( track => track.stop() );
```

https://stackoverflow.com/questions/44274410/mediarecorder-stop-doesnt-clear-the-recording-icon-in-the-tab

**Comment by llfbandit** [comment]
record_web "0.3.1" has been published.
Feedback welcome!

**Comment by dannycortesv** [comment]
recordInstance.dispose() should be enough? It still continue showing me Icon icon after i stop and dispose...

**Comment by llfbandit** [comment]
Can you confirm that you have upgraded the package?
You have nothing more to do than stop and dispose.
