### ISSUE TITLE
hasPermission() call not working on macOS

### ISSUE THREAD

**Issue by hey-nicolasklein** [llfbandit/record#62]
I'm currently in the process of porting my iOS App to MacOS.

The `hasPermission()` call on the `audioRecorder` instance throws the following error:
`No implementation found for method hasPermission on channel com.llfbandit.record`

As permission_handler is not available for macos, I imagine that this call is not working either.

Is it safe to assume that the user has already granted the microphone privilege just by setting up the capabilities in xcode and adding the entitlements to the info.plist? 

Which other ways are there to check if the permissions have been granted by the user on macos?

Thanks for any advice :)

**Comment by llfbandit** [comment]
Please ensure that you have record_macos in your `pubspec.lock` file.
Otherwise, as usual run: `flutter clean && flutter pub get`

**Comment by hey-nicolasklein** [comment]
Flutter clean and pub get didn't do it for me. The pubspec.lock was still missing the macos version. But adding ` record_macos` as a dependency in the pubspec solved the problem.

**Comment by llfbandit** [comment]
Ok for the workaround but your setup is still missing something.
I guess you declared macOS platform for your project but did you enable macos platform in your flutter install?

**Comment by hey-nicolasklein** [comment]
I've added the macos support with `flutter create .` Running `flutter install -d Chrome` added the` record_macos` package to my lock file. And now recording works even without explicitly adding the macos version to my pubspec. Thanks :)
