### ISSUE TITLE
File is not created

### ISSUE THREAD

**Issue by LenhartStephan** [llfbandit/record#65]
I use this library as a small voice recording tool in my Android and iOS app. On Android everything is fine. The file gets created in the temp directory and on saving I copy the file to a different location. But on iOS, the file isn't even created and I'm getting a "No such file or directory". 

Do I have to consider anything special for iOS? I did already specify the NSMicrophoneUsageDescription.

**Comment by llfbandit** [comment]
You should not have to do additional things on iOS.
Are you sure to use a supported configuration? Most recording failures are not reported by the SDK so if you got the permission it should work already.
Can you try with the default settings?
As a further test, specifying a path should help to clarify the issue.

**Comment by singh-karan-7** [comment]
I have the same issue on iOS. It says following error:

`CreateDataFile failed`

**Comment by LenhartStephan** [comment]
This is my code and the console output:
```dart
  void startRecording() async {
    setState(() => isRecording = true);
    timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      setState(() => duration = Duration(seconds: duration.inSeconds + 1));
    });
    await record.start();
  }

  void stopRecording() async {
    timer!.cancel();
    filePath = await record.stop();
    print(filePath);
    setState(() => isRecording = false);
  }

  void saveRecording() async {
    if (filePath != null) {
      Directory dir = await getApplicationDocumentsDirectory();
      File tempFile = File(filePath!);
      String destinationPath = path.join(dir.path, path.basename(tempFile.path));
      File destinationFile = await tempFile.copy(destinationPath);
      Navigator.pop(context);
    }
  }
```

```
file:///private/var/mobile/Containers/Data/Application/A4CC8BC0-4553-4633-B3BD-87D5A3406BE9/tmp/955DD37B-20E2-4B44-8E79-48FBD13D9D76.m4a
"iOS => call startHeadlessService, playerId 98de53e2-c14e-49b9-b0a5-4638623cf23d"
"calling start headless service (\n \"-6035574777829228503\"\n)"
"iOS => call setUrl, playerId 98de53e2-c14e-49b9-b0a5-4638623cf23d"
""
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: FileSystemException: Cannot copy file to '/var/mobile/Containers/Data/Application/A4CC8BC0-4553-4633-B3BD-87D5A3406BE9/Documents/955DD37B-20E2-4B44-8E79-48FBD13D9D76.m4a', path = 'file:///private/var/mobile/Containers/Data/Application/A4CC8BC0-4553-4633-B3BD-87D5A3406BE9/tmp/955DD37B-20E2-4B44-8E79-48FBD13D9D76.m4a' (OS Error: No such file or
directory, errno = 2)
#0 _File.copy.<anonymous closure> (dart:io/file_impl.dart:328:9)
#1 _rootRunUnary (dart:async/zone.dart:1434:47)
#2 _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
#3 _RecordAudioState.saveRecording (package:kronos/ui_elements/
record_audio.dart:168:30)
<asynchronous suspension>
```

**Comment by LenhartStephan** [comment]
So, I have confirmed that the file gets created (at least in my case). I just had to parse the URI like so `File.fromUri(Uri.parse(filePath))`. I still have a problem with the file not being played by the player library I'm using, but that's seems like another problem.
Thank you for your support @llfbandit .

**Comment by llfbandit** [comment]
Thanks for the feedback.
@singh-karan-7 please provide complete information in another issue if you want some help.
