### ISSUE TITLE
Background recording?

### ISSUE THREAD

**Issue by Shawn-sudo** [llfbandit/record#69]
Hi, I saw @llfbandit saying that this package would never support background recording (like at [here](https://github.com/llfbandit/record/issues/38#issuecomment-975722455), [here](https://github.com/llfbandit/record/issues/4#issuecomment-771872197), [here](https://github.com/llfbandit/record/issues/15#issuecomment-834147556), and [here](https://github.com/llfbandit/record/issues/50#issuecomment-1070917702)).
Is there any reason for it? I mean, if it is not planned due to its difficulty, maybe we can clarify what the difficulties are and let others solve it later on.

**Comment by llfbandit** [comment]
This is not a matter of technical difficulties. Choice has been made to not allow this behaviour.

Here are the reasons:
- Security(privacy): to not allow to record ambient and personal conversations. iOS has no guard to trully protect users from this. Android has made progress with P version (see 2nd bullet). Only very latest OSs show microphone icon (meaning recording is not blocked anyway and well... In short, we can't trust users 🤕). I don't want to be part of this.
- From Android P, we shouldn't be able to record from background state so there is no point to implement this. Also, custom Android ROMs are far from supporting sepolicy by default too. Again, stopping the flaw at base is the best option I think.

Ultimately, I don't see any decent and respectful scenario regarding user where this feature would be useful.

**Comment by Shawn-sudo** [comment]
Aha that’s why. I also somewhat agree with you.

**Comment by s-gbz** [comment]
> Ultimately, I don't see any decent and respectful scenario regarding user where this feature would be useful.

@llfbandit  Here are two very simple, very crucial ones: 
- Recording vocals for a song and looking up lyrics or 
- Recording an interview and viewing a conversation outline in a document

It would be rather frustrating to see such an awesome library as this one being unusable in these scenarios.

If I may provide another perspective:
Covert recording is more about how you place your phone (and if this app requires to be active, one might just as well flip the display to hide the recording).

After all, people with malicious intents will find ways to do them, so why obstruse users with good ones?
Any chance to change your mind or at least give it another thought?

**Comment by Shawn-sudo** [comment]
@appinteractive @s-gbz Despite what was said in the previous comment, I think @llfbandit started supporting background recording.

I'm on iOS 17.2.1 & record 5.0.4, and I'm not sure if this also works on Android.

https://github.com/llfbandit/record/assets/60294318/7b94729c-19f4-4de9-8ac8-f6b6a7a3a160

**Comment by appinteractive** [comment]
Hey @Shawn-sudo thanks for your reply! Is this also working when the phone is locked? That's the case I'm looking for.

**Comment by Shawn-sudo** [comment]
@appinteractive Yes, it works even when the phone is locked

It works on Android too! (I used Samsung S9 Android 10)

**Comment by appinteractive** [comment]
Hey cool, thank you @Shawn-sudo very much for that info! 💯

**Comment by erdnj** [comment]
@appinteractive @Shawn-sudo On my android phone, after 1 minute only silence recorded. How could you achieve that? Do you use another package too?

**Comment by appinteractive** [comment]
@erdnj I'm still in the discovery phase for a product where I need this in a way like the ChatGPT app does it in the background. But I did not test it until now. I will report if I find a solution to this.

**Comment by Shawn-sudo** [comment]
If background recording doesn't work out of the box for iOS, try enabling the background mode for the audio by adding these lines to the info.plist file

```xml
  <key>UIBackgroundModes</key>
  <array>
    <string>audio</string>
  </array>
```

I enabled that about a year ago, so I didn't realize that at first 😅

Credit to a developer @atomsbox.com 👍 (unsure if the person wants anonymity or not)

**Comment by fredchung** [comment]
I just submitted a [PR](https://github.com/llfbandit/record/pull/310/commits) to provide some support on iOS. You have to start the recording while the app is up. Recording should continue when the user switches to another app or turns off the screen. This is useful for voice recording apps.
