### ISSUE TITLE
Problem writing to DCIM folder (Android 12)

### ISSUE THREAD

**Issue by fabiotavares** [llfbandit/record#70]
I use this package to record audio through the microphone in my app.

Using an S22 Ultra (Android 12), I can't save the file to
...DCIM/myapp/
but it works perfectly for 
...Documents/myapp/

I know the limitations of Android 11 and up, but if it works in Documents/myapp/ it should also work in DCIM/myapp/

Where am I wrong?

```
final _audioRecorder = Record();

Future<void> _start() async {
    try {
      if (await _audioRecorder.hasPermission()) {
        await _audioRecorder.start(path: widget.path);

        bool isRecording = await _audioRecorder.isRecording();
        setState(() {
          _isRecording = isRecording;
          _recordDuration = 0;
        });

        _startTimer();
      }
    } catch (e) {
      print('Erro: $e');
    }
  }
```

**Comment by llfbandit** [comment]
This issue is not related to the plugin.
DCIM folder is for photo files. I suspect you'll need camera permission to be allowed to write in it.
