### ISSUE TITLE
Stream recording state

### ISSUE THREAD

**Issue by Shawn-sudo** [llfbandit/record#71]
(Feature request)

Is there any plan to provide [`stream`](https://dart.dev/tutorials/language/streams) that updates the recording state (`isRecording`, `isPaused`, `amplitude`, ...) in real time?

With the stream, it would be much easier to real-time update the state of the recorder, like this:
```
AudioRecorder audioRecorder = AudioRecorder();
...
StreamBuilder(
   stream: audioRecorder.aplitudeStream()
   builder: (context, snapshot) {
      return Text(snapshot.data.toString());
   }
)
```

----------
For `amplitudeStream`, I just made one like this. This gets and updates the amplitude every 150 milliseconds.
```
  Stream<double> aplitudeStream() async* {
    while (await _audioRecorder.isRecording()) {
      await Future.delayed(Duration(milliseconds: 150));
      final ap = await _audioRecorder.getAmplitude();
      yield ap.current;
    }
  }
```

**Comment by llfbandit** [comment]
Now available in 4.2.0.beta.1. Please, give me feedback as it's barely tested.

**Comment by Shawn-sudo** [comment]
@llfbandit It works perfect! 
Can you make `onStateChanged()` to be called also when it starts recording tho? I want to update the widgets (UI) also when the record starts (like to show "Record" button before it starts recording and amplitude visualizer after it starts recording).

**Comment by llfbandit** [comment]
Yes, this was an oversight.

**Comment by llfbandit** [comment]
Updated in version 4.2.0-dev.2.

**Comment by Shawn-sudo** [comment]
@llfbandit It works perfect for me!
