### ISSUE TITLE
glitch noise for wave codec

### ISSUE THREAD

**Issue by youngjamespark** [llfbandit/record#73]
When I changed the audio setting to ".wav", glitch noise is heard.
Actually two null data are inserted for every read buffer from microphone.
I can't find the reason.
And I change read,
read(ByteBuffer audioBuffer, int sizeInBytes) → read(byte[] audioData, int offsetInBytes, int sizeInBytes)
buffer data is correct.
This is the modification for run
I hope it help you.
----------------------------------------------------------------------------------------------------
@Override
    public void run() {
      try (final RandomAccessFile out = new RandomAccessFile(path, "rw")) {
        byte[] byteBuffer = new byte[bufferSize];

        // Clears file content. Prevents wrong output if file was existing.
        out.setLength(0);

        while (isRecording.get()) {
          if (isPaused.get()) {
            sleep(100);
          }

          int result = recorder.read(byteBuffer, 0, bufferSize);
          if (result < 0) {
            throw new RuntimeException(getFailureReason(result));
          } else if (result > 0) {
            audioDataLength += result;

            // Update amplitude
           updateAmplitude(byteBuffer, result);
            // Write to file
            out.write(byteBuffer, 0, result);
          }
        }

        if (encoder.equals("wav")) {
          writeWavHeader(out);
        }
      } catch (IOException e) {
        throw new RuntimeException("Writing of recorded audio failed", e);
      } finally {
        completion.countDown();
      }
    }

**Comment by llfbandit** [comment]
What are your settings? It should be 44100 for `samplingRate` and 8 or 16 for `bitRate`.
I couldn't reproduce it on my side.

**Comment by youngjamespark** [comment]
My setting is 
    AudioEncoder encoder = AudioEncoder.wav,    // aacLc => wav
    int bitRate = 256000,                       // 128000 => 256000
    int samplingRate = 16000,                   // 44100 => 16000

I am using your record package for ASR interface.
You should change encoder from aacLc to pcm(wav). Because the compressing encoder is working like a filter.

**Comment by llfbandit** [comment]
Some changes have been applied to version 4.2.0-dev.2.
Please retry with this version. Another test could be made default value for samplingRate also to better locate the issue.
bitRate is ignored for WAV files.

I did not understand your last sentence.

> You should change encoder from aacLc to pcm(wav). Because the compressing encoder is working like a filter.

**Comment by youngjamespark** [comment]
Today, I checked your update.
I will try and update soon.
Thanks.

**Comment by youngjamespark** [comment]
I tried your last update and still hear.
My procedure is like the following:
1. git clone "your project"
2. change the setting in lib/src/record.dart : encoder = AudioEncoder.wav, samplingRate = 16000
3. you can hear the little noise during recorded voice
4. change the AudioRecorder.java based on my recommended code
5. try again to hear the noise

Please follow the above procedure. I am kind of audio engineer and I don't know what is the reason for the noise. But I can make an workround to avoid the situation.

**Comment by youngjamespark** [comment]
I am using your package for speech recognition and sampling rate is 16kHz in pcm mode.
I will make a PR.
By the way, I tried your code on iOS and it's working only if bitRate is 32000 with wav mode.
Anyway I am using your package well. 
Thanks

**Comment by llfbandit** [comment]
Be warned that there is no wav format for iOS. It falls back to pcm only.
