### ISSUE TITLE
please update record/record_linux/assets/fmedia/ - fmedia was rebuilded to support more linux distros

### ISSUE THREAD

**Issue by Alexqwesa** [llfbandit/record#76]
please update record/record_linux/assets/fmedia/ 
fmedia was recently rebuilded to support more linux distros 

[https://github.com/stsaz/fmedia/releases/tag/v1.28](https://github.com/stsaz/fmedia/releases/tag/v1.28)
quote from release 1.28:

>1 Jul 2022 update:
>Rebuilt fmedia-1.28-linux-amd64.tar.xz - now it runs on older Linux without glibc-2.3x.

For example: fmedia in current assets folder didn't work on opensuse 15.4, but latest build works!

**Comment by llfbandit** [comment]
Thanks for the report. On it !

**Comment by llfbandit** [comment]
Available from version 4.2.0-dev.2.

**Comment by Alexqwesa** [comment]
the package [https://pub.dev/packages/record_linux](https://pub.dev/packages/record_linux) still have old version of fmedia (updated >50 days ago),
and since record 4.2.0-dev.2 didn't provide fmedia itself, but depend on package record_linux... there was no update of fmedia(

**Comment by llfbandit** [comment]
Everything has been uploaded with 4.2.0-dev.3.

**Comment by llfbandit** [comment]
Sorry, don't why I closed this one.
