### ISSUE TITLE
Accessing Recorder Timing

### ISSUE THREAD

**Issue by Shawn-sudo** [llfbandit/record#77]
It would be nice to be able to access recorder timing, like the current time since the record started or the time when it started.

Especially when the record pauses and resumes in the middle, it gets hard to track timing.

Smth like this on iOS (AVAudioRecorder)
<img width="694" alt="Screen Shot 2022-07-04 at 9 59 26 AM" src="https://user-images.githubusercontent.com/60294318/177169994-c4f4fdaf-1950-477d-a73c-a6ed25b6d927.png">

**Comment by llfbandit** [comment]
Not planned for now.
The example already has this behaviour and there are existing packages to achieve this goal.
