### ISSUE TITLE
Resources from other platforms in appbundle

### ISSUE THREAD

**Issue by skaldek** [llfbandit/record#79]
Why are plugin resources required to work on other platforms supplied in an appbundle? Why do I need .exe and .dll files in android app? They take up quite a lot of space.

<img width="1028" alt="Screenshot 2022-07-07 at 16 05 52" src="https://user-images.githubusercontent.com/47306921/177795087-ab365143-0be2-4165-97be-33ad06a75392.png">

**Comment by llfbandit** [comment]
Wow, that was unexpected.
Those assets are available only in there respective package implementations... :(

Thanks for the report I'll dig into it.

**Comment by llfbandit** [comment]
Should be fixed in 4.3.0
