### ISSUE TITLE
Start recording right after opening the app

### ISSUE THREAD

**Issue by Shawn-sudo** [llfbandit/record#82]
Calling `record.start()` right after opening the app wouldn't work well, especially on iOS.

Detailed video: https://vimeo.com/730520317
In the video, the red, round button on the bottom of the home screen calls `record.start()`. Ending the record it would open a new page where the user can replay the recorded file. 

I think this occurs when `record.start()` is called before the mic is ready for the app.

**Comment by Shawn-sudo** [comment]
Also, I couldn't catch any exception thrown from `record.start()` when I wrapped around it with the `try-catch` thingy

**Comment by llfbandit** [comment]
Does flutter bindings are initialized at the very start of you program? I don't know what could be done additionally in such case.
Do you have logs?

**Comment by Shawn-sudo** [comment]
`WidgetsFlutterBinding.ensureInitialized();` is called before `runApp()` in my `main()`.

### Logs
I couldn't reproduce the error/bug on flutter debug mode, so I just launched the app on release mode. It may be missing some important logs.

There were no such log that was directly from this `record` package. All the record-related logs are from the `print()` thingy that **I** wrote, so it may miss some important info

```
2022-07-18 18:35:19.235688-0400 Runner[369:7175] Metal API Validation Enabled
2022-07-18 18:35:19.402055-0400 Runner[369:7175] FFmpegKitFlutterPlugin 0x281882960 created.

...some logs from firebase...
...logs from the flutter side of the app / not related to the record feature at all...

2022-07-18 18:35:20.254396-0400 Runner[369:7376] flutter: start record: /var/mobile/Containers/Data/Application/6FB9CB7C-ECE0-4337-9070-B4350C1A7DD6/Documents/records/2022-07-18_18:35:19.889345.m4a

2022-07-18 18:35:20.547147-0400 Runner[369:7376] flutter: error while initializing videoPlayerController file:///var/mobile/Containers/Data/Application/6FB9CB7C-ECE0-4337-9070-B4350C1A7DD6/Documents/records/2022-07-18_18:35:19.889345.m4a: PlatformException(VideoError, Failed to load video: Cannot Open, null, null)
```

Some observations:
- Sometimes, (not for the case that is shown in the log tho) it actually does start recording: the recorded audio file is only like 0.2 second long tho
- This weirdly never occurs on iOS simulator (debug mode) (maybe my finger is slow to reproduce when it's with a computer)

**Comment by Shawn-sudo** [comment]
When I do the same thing on Voice Memos in iOS, it seems to put some delay before starting the record. Maybe we can also wait until the mic gets ready, which is not sure how to achieve.

**Comment by Shawn-sudo** [comment]
I fixed it!

My app used to initialize [`video_player`](https://pub.dev/packages/video_player)s right after opening the app. Apparently, there was some conflict between [`video_player`](https://pub.dev/packages/video_player) and this package. I cannot comprehend what was the problem here, but when I made [`video_player`](https://pub.dev/packages/video_player)s to be lazily initialized (after play button is pressed), this bug disappeared.

I'll close this issue as not planned, because I avoided, but not fixed, this issue.
