### ISSUE TITLE
Cannot upload audio through Multipart File on Web

### ISSUE THREAD

**Issue by gabrieluca** [llfbandit/record#83]
I need to upload the recorded audio on **Web platform** through a HTTP request. 
I'm using the following code to convert it into bytes:

```
final Uint8List bytes = await XFile(audioPath).readAsBytes();
```
Which returns this _NativeUint8List:_
<img width="533" alt="bytes_conversion" src="https://user-images.githubusercontent.com/61849372/179399997-7511a258-5bd0-40de-96a2-61e707ad2ed7.png">

Then I use _MultipartFile.fromBytes_, but I get the following error:
<img width="586" alt="multipart_file_error" src="https://user-images.githubusercontent.com/61849372/179400079-2297d8bb-5d73-43fd-8130-56d7e39e016d.png">

**Comment by llfbandit** [comment]
How this issue is related to the package?

**Comment by gabrieluca** [comment]
Do you know how I can parse the object URL in a way it can be uploaded via HTTP?

**Comment by llfbandit** [comment]
Sorry, irrelevant here.
