### ISSUE TITLE
Unable to get microphone audio from connected bluetooth headset

### ISSUE THREAD

**Issue by premingiet** [llfbandit/record#84]
I have connected Bluetooth headset to my phone, but still audio is received from phone internal microphone only. How do i switch it to Bluetooth microphone ? Or maybe add some option to choose a microphone from list of input devices. I think adding option to choose which device to take input from will help a lot. Currently its unusable for me because Bluetooth microphone is not supported.

**Comment by KieranSteyn** [comment]
I also need to be able to use a bluetooth device. Would be super grateful if you could add device selection for android/ios.

**Comment by KieranSteyn** [comment]
I have some time and can help with the development. let me know if you need a hand.

**Comment by premingiet** [comment]
yes my platform is android. But i think this is a necessary feature. I am actually developing for both iOS and Android, but as soon as i realised its not working for android, i didn't test for iOS either. I mean it needs to work for both platforms, orelse what's the point of making a cross platform app without support for 1 platform.

**Comment by llfbandit** [comment]
OK so if you're in a rush please fill a PR

**Comment by llfbandit** [comment]
@KieranSteyn any help is very welcome for sure. You may focus on ios mic selection (code is nearly available) or implement Bluetooth feature on Android (which is the main purpose of this issue).

**Comment by llfbandit** [comment]
Unfortunately, recording from bluetooth on Android is very limited.
Sample rate must be set to 8kHz which is very low even for voice recording and number of channels to 1 only (mono).
https://developer.android.com/reference/android/media/AudioManager#startBluetoothSco()

**Comment by niktimmans** [comment]
@llfbandit 
Hello, is there any chance to see some code for android implementation. I'm okay with 8 kHz, just need it for Android by any means

**Comment by AliKhan6** [comment]
Hi, any update on this? it's still not working with Bluetooth

**Comment by bejaeger** [comment]
Would also like to use a bluetooth device for recording audio. Any news?

**Comment by patelnirav48** [comment]
@llfbandit Just wanted to check when this is going to available? 
Thank you for all your support.

**Comment by rezins** [comment]
> @llfbandit Just wanted to check when this is going to available? Thank you for all your support.

I've already modify this package so can record through microphone bluetooth . Check my repo: https://github.com/rezins/record.5.0.1 . I've also add pull request so the author can merge or not.

**Comment by wongcheehong** [comment]
@llfbandit please take a look on this

> > @llfbandit Just wanted to check when this is going to available? Thank you for all your support.
> 
> I've already modify this package so can record through microphone bluetooth . Check my repo: https://github.com/rezins/record.5.0.1 . I've also add pull request so the author can merge or not.

**Comment by darajava** [comment]
> @llfbandit please take a look on this
> 
> > > @llfbandit Just wanted to check when this is going to available? Thank you for all your support.
> > 
> > 
> > I've already modify this package so can record through microphone bluetooth . Check my repo: https://github.com/rezins/record.5.0.1 . I've also add pull request so the author can merge or not.

He closed my PR 10 minutes after I created it, but hasn't replied to this in 3 months. I wll try to use @rezins package as it also allows background recording in iOS, even if it means missing out on updates from this package.

**Comment by rezins** [comment]
Sorry for taking couple of weeks.
Please take a look [https://github.com/llfbandit/record/pull/284](https://github.com/llfbandit/record/pull/284)
