### ISSUE TITLE
android error

### ISSUE THREAD

**Issue by sungentim** [llfbandit/record#88]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3905397/179897901-264d4e9a-f84d-40c7-9ae0-b1ee4e73f2cf.png">

**Comment by llfbandit** [comment]
So what's the issue?
I think you should upgrade your android config (gradle plugin, targeted sdk, ...)

**Comment by llfbandit** [comment]
Please update your Android setup and in your case your gradle plugin:
classpath 'com.android.tools.build:gradle:7.2.1'
