### ISSUE TITLE
Required feature

### ISSUE THREAD

**Issue by csacchetti** [llfbandit/record#9]
I believe that the strength of this plugin is simplicity and essentiality, thanks.
But I wonder if it is possible to add the pause function in the recording, so as not to have to start another file every time?
Second feature that I think can make the plugin more complete is to provide access to audio level metering properties average power peak power.
Thanks again for your work

**Comment by llfbandit** [comment]
Hi, thanks for the the proposal.

Pause feature is doable on both platforms. Just need spare time to spend on this.
About stats, is this to allow some spectrum representation on UI?

**Comment by csacchetti** [comment]
No simply a bar that shows during recording, in real time, the volumes of the incoming voice.
I take this opportunity to ask a question. Is it complicated to add the timer with the recording time?

**Comment by csacchetti** [comment]
Thank you very much for adding the "pause" function. Up to now the best recording plugin was "Flutter audio recorder", but since 2019 there is no maintenance and therefore it is also without null safety. Now I would say that this plugin can become a reference. The only feature missing from "Flutter audio recorder" is: "provide access to audio level metering properties average power peak power". If it is not too demanding it could give an important function to this plugin. With the web it would surely be "flutter favorite".
In any case, congratulations. Now I add it to my app and if I find any problems I definitely report it. I think it is important to contribute, in your own small way, to the development of this plugin.

**Comment by csacchetti** [comment]
I forgot that Flutter audio recorder allows you to have the position of the recording and the duration. With time, these two functions are also very useful.

**Comment by llfbandit** [comment]
Current and top mal amplitudes are now available in v3.0.0
