### ISSUE TITLE
Can not find direct-sound.so file when running on Linux.

### ISSUE THREAD

**Issue by diasnrg** [llfbandit/record#90]
record plugin version: ^4.3.1
flutter SDK version: 3.1.0
OS: Ubuntu 20.04.4 LTS
Added the record plugin to my pubspec.yaml file.
Did not imported anywhere, just tried to run my application on Linux.
The running process stops with Error:
_**CMake Error at cmake_install.cmake:107 (file):
  file INSTALL cannot find
  "[projectPath]/linux/flutter/ephemeral/.plugin_symlinks/record_linux/linux/fmedia/mod/direct-sound.so":
  No such file or directory.**_
  
I tried to find the file **direct-sound.so** but could not, even in the record sources: https://github.com/llfbandit/record/tree/master/record_linux/linux/fmedia/mod

**Comment by llfbandit** [comment]
Thanks for the report.
CMakeLists.txt will be fixed in next version coming really soon.

**Comment by llfbandit** [comment]
Fixed in record_linux 0.3.2
