### ISSUE TITLE
record not allowing the app to build because of "A problem occurred evaluating project ':record'."

### ISSUE THREAD

**Issue by Wassiem-Ibr** [llfbandit/record#91]
**Package version**
record: ^4.1.1

**Describe the bug**
The bug appeared suddenly and it was working fine before.

**To Reproduce**
It appears when you build aab or run the app in debug and the app will exit with an exception.

**Expected behavior**
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Asus\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\record-4.3.1\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':record'.
> No signature of method: build_e7x449wsxzivqwprnkzdieufp.android() is applicable for argument types: (build_e7x449wsxzivqwprnkzdieufp$_run_closure2) values: [build_e7x449wsxzivqwprnkz
dieufp$_run_closure2@7390c4cd]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser -
 - Version -

**Additional context**
I tried deleting the package and deleting the content of pup folder in the directory above, but it didn't solve the problem, and it still persists.

can anyone help me with a solution for this bug?

**Comment by TimotheeR** [comment]
Hello Wassiem-Ibr,
I encounter the same problem as you. Did you close this issue because you solved it? 
If so, can you tell me how you did it.
Best regards

**Comment by Wassiem-Ibr** [comment]
Hello @TimotheeR 
Yes, I looked in the old bugs files here and I found a solution that requires me to change one line of code and the bug was resolved and the app ran just fine, I can't remember what was it but you can find it easily in the bugs achieve

**Comment by yswtrue** [comment]
Seams upgrade gradle to 7.3.3 works for me
