### ISSUE TITLE
ios not record

### ISSUE THREAD

**Issue by hatemragab** [llfbandit/record#92]
record: ^4.1.1

ios just record noise in the real device and nothing on simulator 
and i run on the M1 processor 
``` dart
  final res =
          await PermissionAsker.askPermission(permission: PermissionType.mic);
      if (res == 1) {
        final isAllow = await recorder.hasPermission();
        if (isAllow) {
          if (Platform.isIOS) {
            unawaited(
              recorder.start(),
            );
          } else {
            unawaited(
              recorder.start(
                encoder: AudioEncoder.aacHe,
                bitRate: 40000,
                samplingRate: 64100,
              ),
            );
          }
          return true;
        }
```
the stop function is 

``` dart
  Future<VoiceInfoData> stop() async {
    final path = await recorder.stop();
    if (path != null) {
      final uri = Uri.parse(path);
      final size = FileUtils.getFileSize(File(uri.path));
      return VoiceInfoData(
        duration: Duration.zero,
        path: uri.path,
        size: size,
      );
    }
    throw "record path is null here ! while stop the record";
  }
```
all works good on android!

**Comment by llfbandit** [comment]
Please ensure that it is reproducible with the example and version 4.3.2.
I'm not surprised that the simulator records anything.

By the way, `hasPermission` already asks for permission if not granted. You don't need external dependency for this.

**Comment by hatemragab** [comment]
Wow i have tried to run the example of the package and the same bug happened please check the example on mac M1 processor

**Comment by hatemragab** [comment]
https://user-images.githubusercontent.com/37384769/181368470-2b3efec8-e0af-488c-9402-c68c86eb0902.mp4

**Comment by llfbandit** [comment]
M1 processor is for your desktop OS, so the issue should not be related to this.
The file seems to be OK because it's played without issue apparently... I can't determine what's going on from the info given.
When recording, are the levels updated? I can't see from the video.
Music volume too low?...

**Comment by hatemragab** [comment]
My voice not recorded only noise it recorded

**Comment by hatemragab** [comment]
It was from my phone 
I tried another phone it working
Sorry 😐
