### ISSUE TITLE
The Android app can't be build due to an error related to record

### ISSUE THREAD

**Issue by ma7moudAziz** [llfbandit/record#93]
Hi @llfbandit, Kindly note that this library is working fine for ios with no issues, but as for Android I am receiving the following error on the build.

Kindly I need your assistance.
Regards.

Build file 'C:\Users\mahmo\Documents\Flutter\.pub-cache\hosted\pub.dartlang.org\record-4.3.2\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':record'.
> No signature of method: build_11o6g0ibbz3ipit255roz4f9q.android() is applicable for argument types: (build_11o6g0ibbz3ipit255roz4f9q$_run_closure2) values: [build_11o6g0ibbz3ipit255roz4f9q$_run_closure2@2d29f3c1]

**Comment by TimotheeR** [comment]
The same for me

**Comment by llfbandit** [comment]
Please update your Android setup and in your case your gradle plugin:
`classpath 'com.android.tools.build:gradle:7.2.1' `

**Comment by llfbandit** [comment]
Did you update gradle accordingly?
When setting the plugin to 7.2+, gradle should be in version 7.3.3+.
I use version 7.4.2 for the project.

More info here: https://developer.android.com/studio/releases/gradle-plugin
Otherwise, as usual, clean update, etc.

**Comment by RobotKSR** [comment]
I set gradle plugin version to 7.2.1, and gradle version in _gradle-wrapper.properties_ to 7.3.3 and then to 7.4.2.
I am running clean command also, for sure.
Every time it's giving me this console log:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_bxt4vv07u73ds9js00vvjhcp0.android() is applicable for argument types: (build_bxt4vv07u73ds9js00vvjhcp0$_run_closure2) values: [build_bxt4vv07u73ds9js00vvjhcp0$_run_closure2@721a46b2]
```

**Comment by llfbandit** [comment]
This is definitly an issue with Android setup, maybe kotlin version?
From your `android` folder, launching `./gradlew build --stacktrace` provide more info?

**Comment by ma7moudAziz** [comment]
Hi @llfbandit,
kindly note that when i updated the Android setup (gradle plug in) from 7.1.2 to 7.2.1 , the app was built successfully and the record function worked perfectly.

Thank you.
Regards.

**Comment by RobotKSR** [comment]
Finally, what I had to do to make app and 'record' plugin working with gradle plugin v7.2.1 and gradle v7.4.2  was to remove `useProguard true` from app-level build.gradle and update `com.huawei.agconnect:agcp` version in android-level build.gradle.
@llfbandit , thanks a lot for your support and for plugin, I hope my solution may also help someone.

**Comment by sejun2** [comment]
4.3.x has still problem...
 I just downgraded my app to 4.1.x

**Comment by bhautikGJ05** [comment]
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.version-check'.
   > Minimum supported Gradle version is 7.3.3. Current version is 6.7. If using the gradle wrapper, try editing the distributionUrl in D:\app ideas project\fitnow\fit_now\android\gradle\wrapper\gradle-wrapper.properties to gradle-7.3.3-all.zip

**Comment by MaddinMade** [comment]
> A problem occurred evaluating project ':app'.
> 
> > Failed to apply plugin 'com.android.internal.version-check'.
> > Minimum supported Gradle version is 7.3.3. Current version is 6.7. If using the gradle wrapper, try editing the distributionUrl in D:\app ideas project\fitnow\fit_now\android\gradle\wrapper\gradle-wrapper.properties to gradle-7.3.3-all.zip

Just do exactly what the error message says
