### ISSUE TITLE
flutter: MissingPluginException(No implementation found for method hasPermission on channel com.llfbandit.record)

### ISSUE THREAD

**Issue by saravp123** [llfbandit/record#94]
**Package version**
4.3.2

**Describe the bug**
Getting below error while trying to run the example app on Windows

**To Reproduce**
I just ran the sample app on Windows.  If any file has to be modified to provide microphone permissions let me know

**Expected behavior**
The app screen is just showing "Waiting to record".  I am expecting the recording to start

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - not applicable.  I am trying to run it as windows app
 - Version - Windows 10

**Smartphone (please complete the following information):**
 - NA.  I am facing issue while running this app on Windows laptop only

**Additional context**
None
![error](https://user-images.githubusercontent.com/39334476/182843576-6267232d-d882-414a-8162-3b8be218b9a1.jpg)

**Comment by llfbandit** [comment]
`flutter clean && flutter pub get && flutter pub upgrade` should help.
FYI, `hasPermission` on Windows (and linux) does nothing but returning `true`.

**Comment by llfbandit** [comment]
I just realized that your project is called `record_windows`? This is the name of the package for the Windows implementation... maybe this is a lead too.
