### ISSUE TITLE
WAV header data chunk size is consistently off by 44 bytes

### ISSUE THREAD

**Issue by sonsnix** [llfbandit/record#96]
**Package version**
4.3.2

**Describe the bug**
When recording a .wav file, the size of the data chunk provided in the wav header is off by 44 bytes (interestingly, that is the same size as the header).

**To Reproduce**
1. Record wav file on Android
2. Open wav file with HEX editor
3. Read out data chunk size information (byte 40-43)
4. Size equals overall file size, but should be file size minus header size (44 bytes)

**Expected behavior**
See step 4 above

As a consequence, packages like "wav" report the file to be corrupted, although it plays back fine with VLC etc.

**Desktop (please complete the following information):**
Flutter 3.0.5
Dart 2.17.6

**Smartphone (please complete the following information):**
 - Pixel 4a
 - Android 12

**Additional context**
HEX editor readout:
![image](https://user-images.githubusercontent.com/34959233/183647515-839b2573-843f-4d72-8996-d933b0ecf769.png)

Explorer readout:
![image](https://user-images.githubusercontent.com/34959233/183647608-55fd9504-cf73-4005-8271-36c21cdc9427.png)

**Comment by llfbandit** [comment]
Thanks for the report.
I guess I overwrite the first 44 data bytes when I build the header...

**Comment by bdremynoel** [comment]
Fix is available on master branch if you want to give it a try.

**Comment by sonsnix** [comment]
I tested the code snippet from the diff and with that it works well. Will upgrade to the newest version as soon as it is on pub.dev.

Thanks for the quick fix!

**Comment by llfbandit** [comment]
Thanks to you for the detailed decription and quick feedback.
Published in 4.3.3!
