### ISSUE TITLE
[Windows] Trying to record in wav or flac makes no result

### ISSUE THREAD

**Issue by nikitatg** [llfbandit/record#98]
Hi!
record's version is: 4.3.3 (record_windows version is 0.6.1 in pubspec.lock)

I've created an example project with source from https://pub.dev/packages/record/example
...and changed encoder to AudioEncoder.wav:
```dart
await _audioRecorder.start(encoder: AudioEncoder.wav);
```
Build project and tap "record" button, wait for a couple seconds, tap "stop" button. Debug log says 
```flutter: Recorded file path: C:\Users\user\AppData\Local\Temp\2b9e24fe.wav```
But there is no such file (or any another new files at this path).

Similar behavior is seen when set ```encoder: AudioEncoder.flac```

I've added code to check which encoders are supported in my case:
```dart
        for (var element in AudioEncoder.values) {
          isSupported = await _audioRecorder.isEncoderSupported(
            element,
          );
          if (kDebugMode) {
            print('${element.name} supported: $isSupported');
          }
        }
```
And obtained this:
```
flutter: aacLc supported: true
flutter: aacEld supported: false
flutter: aacHe supported: false
flutter: amrNb supported: false
flutter: amrWb supported: false
flutter: opus supported: true
flutter: vorbisOgg supported: true
flutter: flac supported: true
flutter: wav supported: true
flutter: pcm8bit supported: false
flutter: pcm16bit supported: false
```
P.S.: opus and vorbisOgg encoders works well.

 - OS: Windows 10 version 21H2
 - Flutter version 3.0.5
 - record package version 4.3.3
 - record_windows version is 0.6.1 (in pubspec.lock)

**Comment by llfbandit** [comment]
Version 4.4.0 has just been released.
Recording to FLAC format should now work out of the box.
For WAV format, fmedia should provide an output error if so.

**Comment by nikitatg** [comment]
I've discovered that situation is a little bit different from original subject.
Previous tests i make in debug mode. When I start to run test project in release mode, everithyng was broken.

(However i'm not quite shure tha it is a problem of this package. Maybe it's fmedia library)

What happens when running in release mode:
- about 1 of 10 attempts produces a file with record
- in most cases file is not created (if file was exist before, it will be deleted)
- regardless of encoder (aacLc, wav, flac)
- log contains no any error messages (i cloned "record" repo and change logging to see all in release mode)

If this bug doesn't concern you, can close this issue.

If interested, my test project is here https://github.com/nikitatg/record_testdrive (playback does not work at that example. must look for file on disk)
Launch with `flutter run -d windows --release`

**Comment by llfbandit** [comment]
I've encountered the behaviour few times during development.
As I use fmedia with the executable and pipe to communicate with, this makes really hard to dig in.
Recording for a short period of time tends to increase this situation (at least this is what I feel).

I leave the issue in its current state without further diagnotic. I may be not concerned, still I'll need to answer next same concerns.
If you think you'll overhelm this issue, feel free to open a discussion, to continue on this.
